### ISSUE TITLE
Upgrade to spring cloud 2022.0.0-M5

### ISSUE THREAD

**Issue by spencergibb** [spring-io/start.spring.io#1007]
spring-cloud-netflix has been added back to the release train.

**Comment by spencergibb** [comment]
I believe the eureka client and server were removed here https://github.com/spring-io/start.spring.io/commit/989abc2ed4ba97e7fdc8fa4235db3ce0250faf11#diff-967875aff743d8a8eb901165c8028a3817f04d3b8e3e182079fb9d99948591d5R1237-R1255

**Comment by snicoll** [comment]
Thanks @spencergibb
