### ISSUE TITLE
Could not get unknown property 'snippetsDir' for task ':test' of type org.gradle.api.tasks.testing.Test.

### ISSUE THREAD

**Issue by textbook** [spring-io/start.spring.io#101]
The REST Docs dependency doesn't work correctly out of the box with the Gradle Project option; the `build.gradle` file refers to a `snippetsDir` that isn't set anywhere:

```
test {
	outputs.dir snippetsDir
}

asciidoctor {
	inputs.dir snippetsDir
	dependsOn test
}
```

All other settings in the Initializr were the defaults:

 - **Project**: Gradle Project
 - **Language**: Java
 - **Spring Boot**: 2.1.4
 - **Project Metadata**: 
    - Group: `com.example`
    - Artifact: `demo`
 - **Dependencies**:
    - REST Docs

**Comment by snicoll** [comment]
@textbook thanks for the report! We've missed declaring the property and I think there is a limitation in the Gradle model at the moment.

I've raised https://github.com/spring-io/initializr/issues/893 - We'll follow-up here once we've made our mind on how to declare the `snippetsDir` property

**Comment by 18297093310** [comment]
test {
    outputs.dir snippetsDir
}

groovy.lang.MissingPropertyException: Could not get unknown property 'snippetsDir' for task

**Comment by snicoll** [comment]
This has been fixed by https://github.com/spring-io/start.spring.io/commit/325bbdf6222ed90c9814a600c3de518dc3a32990
