### ISSUE TITLE
Upgrade to Spring Cloud Azure 6.0.0-beta.3 for apps using Spring Boot 3.0

### ISSUE THREAD

**Issue by moarychan** [spring-io/start.spring.io#1026]
This version will only compatibility with Spring Boot 3.0.0-RC1 and Spring Cloud 2022.0-RC1.
- Maven: https://repo1.maven.org/maven2/com/azure/spring/spring-cloud-azure-dependencies/6.0.0-beta.3/
- Compatible Spring Boot version: https://github.com/Azure/azure-sdk-for-java/blob/spring-cloud-azure_6.0.0-beta.3/sdk/spring/CHANGELOG.md#600-beta3-2022-11-04

**Comment by snicoll** [comment]
@moarychan please provide a bit more information about the breaking changes going forward. The link to the changelog is appreciated but I'd prefer a summary of the impact here, if at all possible. Our verification checks are failing as cosmos is no longer available.

**Comment by moarychan** [comment]
@snicoll , I just check your new added compatibility range for version 6.0.0-beta.3 is `[3.0.0-M1,3.1.0-M1)`, the compatibilityRange should be `[3.0.0-M5,3.0.0-RC1)`, could you please double-check?
