### ISSUE TITLE
Upgrade to Native Build Tools 0.9.17 for Spring Boot 3 projects that use GraalVM Native Support

### ISSUE THREAD

**Issue by wilkinsona** [spring-io/start.spring.io#1027]

**Comment by snicoll** [comment]
This makes the experience different for Maven and Gradle users. Shouldn't this be changed only as RC2?

**Comment by wilkinsona** [comment]
If we wait till RC2, users of Boot snapshots with Gradle will see a failure as the method to configure the required Graal version doesn't exist in 0.9.16. This seemed like the most straightforward way to address that. I guess we could override the plugin version for Maven users temporarily but, as 0.9.17 is backwards compatible, that didn't seem necessary.

**Comment by snicoll** [comment]
You don't have to wait for RC2. The range is such that a snapshot is always after a milestone/rc. Switching to RC2 will also apply for the current snapshot.
