### ISSUE TITLE
Switch Gradle with Java to Kotlin Build Scripts

### ISSUE THREAD

**Issue by jamesward** [spring-io/start.spring.io#1031]
Gradle, JetBrains, and Google are all working towards helping move the Gradle ecosystem to a default of Kotlin build scripts.  We've done research indicating that users have a better overall developer experience with the Kotlin build scripts especially when editing build scripts in IntelliJ IDEA.  We know the editing experience isn't great right now in Eclipse but that is true for both Groovy build scripts and Kotlin build scripts.

Moving to a Kotlin build script default across the ecosystem will take around 6 months and has numerous pieces including documentation & StackOverflow updates, Android template updates, IntelliJ IDEA & Android Studio performance improvements with code hinting for Kotlin build scripts, and a number of other pieces.

Please consider moving start.spring.io's Gradle w/ Java usage to Kotlin build scripts to align with this broader direction.  Let us know if you need more details or have any questions.

Superceeds: https://github.com/spring-io/start.spring.io/issues/956

**Comment by wilkinsona** [comment]
I think the discussion should continue on #956 rather than splitting it across two issues. Personally, [my opinion](https://github.com/spring-io/start.spring.io/issues/956#issuecomment-1172370119) hasn't changed:

> The alternative is to switch the default for everyone so that all Java-based Gradle projects use the Kotlin DSL. My personal opinion is that we shouldn't do it as, outside of IntelliJ IDEA, IDE support for Kotlin is quite lacking making editing the build script harder. It's for this reason that Spring Boot's Gradle-based build uses the Groovy DSL – the core team and our contributors use a variety of IDEs and we want things to be as accessible as possible.

We're still using the Groovy DSL in Spring Boot's build and it's working well for us. We're happy to discuss this further, but let's have that discussion on #956 please.

**Comment by jamesward** [comment]
It seemed like that issue was more focused on giving users an option so they could select the build language as well.  But I'm happy to continue the discussion there.
