### ISSUE TITLE
Make invalid selections impossible

### ISSUE THREAD

**Issue by michael-simons** [spring-io/start.spring.io#1041]
The site lets you select Spring Boot 3 + JDK 11 or 8. The generate (Maven) project will still have JDK 17 defined in it. Not a big, but UX can be improved to disable invalid combinations.

**Comment by wilkinsona** [comment]
Thanks for the suggestion. Unfortunately, with all of the different clients (web UI, CLI, IDE plugins) it isn't possible to disable invalid combinations consistently. For now, we've settled on adding a note to the generated `HELP.md` that explains what has happened. https://github.com/spring-io/start.spring.io/issues/250 is tracking further improvements in this area.

**Comment by michael-simons** [comment]
Kinda odd that this works though 
![image](https://user-images.githubusercontent.com/526383/204332031-0c9c3862-b515-4014-97ee-ac9ecc6865e8.png)
But I see, I am not the only person who stumbled upon this 🤷

**Comment by wilkinsona** [comment]
Yeah, it is odd. There are some implementation details of how the service is implemented and describes it capabilities leaking out and that's unfortunate. The reason is works for dependencies is that the metadata allows a dependency to describe the versions of Spring Boot with which it is compatible. There's nothing similar for Java versions unfortunately but it would definitely be a nice thing to have. We'll have to see where #250 and our limited bandwidth takes us.

**Comment by michael-simons** [comment]
Thanks for the explanation, appreciated.

**Comment by lohitharg16** [comment]
how to resolve the build issue as i am default getting 17 and 
java: error: release version 17 not supported

Module demo SDK 11 is not compatible with the source version 17.

Upgrade Module SDK in project settings to 17 or higher. Open project settings.

**Comment by jeremy-brooks** [comment]
> how to resolve the build issue as i am default getting 17 and java: error: release version 17 not supported
> 
> Module demo SDK 11 is not compatible with the source version 17.
> 
> Upgrade Module SDK in project settings to 17 or higher. Open project settings.

@lohitharg16 I also encountered this and from reading the above comments, this is a limitation with the version of the UI where it cannot easily identify if the version of Java is compatible with the version of the spring framework version.

Below taken from : https://github.com/spring-projects/spring-framework/wiki/Spring-Framework-Versions#jdk-version-range

> 6.0.x is the main production line as of November 2022. This new generation of the framework comes with a JDK 17 and Jakarta EE 9 baseline.
> 5.3.x is the final feature branch of the 5th generation, with long-term support provided on JDK 8, JDK 11, JDK 17 and the Java EE 8 level.

You will see a note at the very top of your generated `HELP.md` file in the root of your project saying as much.

Just need to regenerate with a lower version of the spring framework selected is all. At least that is what the docs suggest anyway.
