### ISSUE TITLE
Spring Initializr does not generate the correct artifactId for MySQL support

### ISSUE THREAD

**Issue by dfcoffin** [spring-io/start.spring.io#1043]
The current version of the Spring Initializr does not generate the proper Gradle or Maven dependency for MySQL:

![image](https://user-images.githubusercontent.com/1829699/204118063-ed7f584f-751a-40e8-8a34-8ebb0e7d03b0.png)

![image](https://user-images.githubusercontent.com/1829699/204118072-f2ecd705-f90d-48e9-b86c-7545e77484b5.png)

**Comment by wilkinsona** [comment]
Those coordinates are [intentional](https://github.com/spring-io/start.spring.io/issues/1013). Why do you consider them to be incorrect?

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
