### ISSUE TITLE
Removing unsupported java versions for spring Initzializer 3.0.0

### ISSUE THREAD

**Issue by rhabichl** [spring-io/start.spring.io#1052]
# Feature-Request
## Problem
As mentioned in the [Release Notes,](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0.0-M1-Release-Notes) Spring 3.0.0 requires java 17 or higher. The Initializer still gives the possibility to choose Java version 8 or 11. Even though the output uses the correct version (Java 17),  the user is never notified that the Initializer altered the SDK version. 

## Solution
- Remove the options for Java version 11 and 8 when Spring Boot 3.0.0 or higher is selected 
- Notify the user, that Java version 17 is required for Spring Boot 3.0.0

**Comment by bclozel** [comment]
Duplicates #1041
