### ISSUE TITLE
Upgrade to Spring Cloud Azure 6.0.0-beta.4 for apps using Spring Boot 3.0

### ISSUE THREAD

**Issue by moarychan** [spring-io/start.spring.io#1057]
This is an upgrade for Spring Cloud Azure [6.0.0-beta.3](https://github.com/spring-io/start.spring.io/issues/1026), the artifact id `spring-cloud-azure-starter-data-cosmos` is still unavailable in `6.0.0-beta.4`. This version will only compatibility with Spring Boot 3.0.0-RC2 and Spring Cloud 2022.0-RC2.
- Maven: https://repo1.maven.org/maven2/com/azure/spring/spring-cloud-azure-dependencies/6.0.0-beta.4/
- Compatible Spring Boot version: https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/spring/CHANGELOG.md#600-beta4-2022-12-07

**Comment by bclozel** [comment]
Thanks for the heads up @moarychan, this change is in but it's not live yet. We're working on a CI pipeline issue.

**Comment by bclozel** [comment]
This is now live.

**Comment by moarychan** [comment]
Thanks @bclozel
