### ISSUE TITLE
When Java 19 is selected, the wrong version of Gradle is provided

### ISSUE THREAD

**Issue by bweston92** [spring-io/start.spring.io#1058]
Using the following [configuration][build_conf] where you can see "Java 19" is selected the following error occurs.

```
./gradlew clean

FAILURE: Build failed with an exception.

* What went wrong:
Could not open settings generic class cache for settings file '/home/bweston/Downloads/demo/settings.gradle' (/home/bweston/.gradle/caches/7.5.1/scripts/37hddx5idswb2jumnuf2jjnbj).
> BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 63

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 343ms
```

I looked into this and seen that [Gradle][gradle_compat] 7.5 does not support Java 19 and requires 7.6 as a minimum. 

[build_conf]: https://start.spring.io/#!type=gradle-project&language=java&platformVersion=3.0.0&packaging=jar&jvmVersion=19&groupId=com.tagrecruitments&artifactId=candreg&name=candreg&description=Candidate%20Registration%20API&packageName=com.tagrecruitments.candreg&dependencies=configuration-processor,web,data-jdbc,session
[gradle_compat]: https://docs.gradle.org/current/userguide/compatibility.html

**Comment by bweston92** [comment]
Bumping `gradle/wrapper/gradle-wrapper.properties` to `7.6` from https://services.gradle.org/distributions/ seemed to work.

**Comment by bclozel** [comment]
Closing in favor of spring-io/initializr#1361.
This is now live in production.

Thanks for raising this issue!
