### ISSUE TITLE
When selecting Java 11, Java 17 is provided instead.

### ISSUE THREAD

**Issue by eeganlf** [spring-io/start.spring.io#1063]
![image](https://user-images.githubusercontent.com/101604439/207505206-aa8f49a3-6f71-46ee-942d-cd800b3aa10e.png)
When selecting Java 11, Java 17 is provided instead. Please fix.

**Comment by ztomic** [comment]
You have selected Spring Boot 3.0.0, it is using Java 17 as baseline so it cannot be run at java 11, for java 11 you should choose Spring Boot 2.7.x

https://spring.io/blog/2022/11/24/spring-boot-3-0-goes-ga

**Comment by bclozel** [comment]
Duplicates #1041
