### ISSUE TITLE
Unable to compile spring boot 3.0.0 with kotlin+gradle (plugins web, security and thymeleaf)

### ISSUE THREAD

**Issue by alladdin** [spring-io/start.spring.io#1064]
When I tried to compile this [Spring Initializr](https://start.spring.io/#!type=gradle-project-kotlin&language=kotlin&platformVersion=3.0.0&packaging=jar&jvmVersion=17&groupId=com.example&artifactId=demo&name=demo&description=Demo%20project%20for%20Spring%20Boot&packageName=com.example.demo&dependencies=web,thymeleaf,security).

I get this error:
`Execution failed for task ':compileKotlin'.
> Error while evaluating property 'filteredArgumentsMap' of task ':compileKotlin'
   > Could not resolve all files for configuration ':compileClasspath'.
      > Could not resolve org.thymeleaf.extras:thymeleaf-extras-springsecurity6:3.1.0.RELEASE.
        Required by:
            project :
         > Could not resolve org.thymeleaf.extras:thymeleaf-extras-springsecurity6:3.1.0.RELEASE.
            > Could not parse POM https://repo.maven.apache.org/maven2/org/thymeleaf/extras/thymeleaf-extras-springsecurity6/3.1.0.RELEASE/thymeleaf-extras-springsecurity6-3.1.0.RELEASE.pom
               > Could not find org.springframework.security:spring-security-bom:6.0.0-RC2.
`

**Comment by bclozel** [comment]
Closing as a duplicate of thymeleaf/thymeleaf#932.
You can upgrade right away to Thymeleaf 3.1.1 locally to fix this. We'll release a new Spring Boot version with that fix next week.
