### ISSUE TITLE
Any plan for Spring Boot Starter For JWT

### ISSUE THREAD

**Issue by hannah23280** [spring-io/start.spring.io#1077]
Hi,
  I not sure if this is the correct forum to ask.  If not, do kindly let me which github forum is more suitable to me to post this.
 Is there any plan to create a spring boot starter for JWT?  Currently developer has to manually manage the libraries (and versions) for the usage of JWT.  I ask this, cos when i went to initializr website, and search for JWT, nothing come up.

**Comment by hannah23280** [comment]
Thanks. For JWTs, i following a course tutorial which uses

        implementation 'io.jsonwebtoken:jjwt-api:0.11.5'
	runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.11.5'
	runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.11.5'

May I ask, what starter to use, if we do not want to involve oauth2, but wanna deal with JWTs?  Possible to have a starter for JWT only, and the spring-boot-starter-oauth2-resource-server could simply include this JWT  starter

**Comment by wilkinsona** [comment]
Spring Security uses the Nimbus JOSE and JWT SDK to implement its JWT support so a starter that uses the `io.jsonwebtoken` dependencies wouldn't provide much benefit I'm afraid.

**Comment by hannah23280** [comment]
But that would need involve oauth2 ?  Any plan to put Nimbus JOSE and JWD SDK into a separate starter so that we can use them without involving oauth2?

**Comment by wilkinsona** [comment]
You don't need a starter to be able to do that. You can add a dependency on `com.nimbusds:nimbus-jose-jwt` to your application and use the SDK as needed.
