### ISSUE TITLE
bug: generated Kotlin projects with the org.hibernate.orm gradle plugin do not build

### ISSUE THREAD

**Issue by pettyalex** [spring-io/start.spring.io#1078]
This combination of dependencies will result in a project with the `id 'org.hibernate.orm' version '6.1.6.Final'` Gradle plugin, which requires the `'java'` Gradle plugin in order to build. This problem happens no matter what style of Gradle config is selected, groovy or kotlin:
<img width="1269" alt="image" src="https://user-images.githubusercontent.com/3219141/210601189-9b83bd9a-c24b-4a61-bacd-6c03074c26c6.png">

build.gradle has these plugins as generated:
```
plugins {
	id 'org.springframework.boot' version '3.0.1'
	id 'io.spring.dependency-management' version '1.1.0'
	id 'org.hibernate.orm' version '6.1.6.Final'
	id 'org.graalvm.buildtools.native' version '0.9.18'
	id 'org.jetbrains.kotlin.jvm' version '1.7.22'
	id 'org.jetbrains.kotlin.plugin.spring' version '1.7.22'
	id 'org.jetbrains.kotlin.plugin.jpa' version '1.7.22'
}
```

The problem can be fixed by adding the Java gradle plugin: `id 'java'`, or alternatively by this combination not including the hibernate gradle plugin. I do not fully understand why the hibernate gradle plugin is added only when graalvm native buildtools are selected, possibly this has something to do with the aot introspection phase.

The first gradle build fails like this:
```
./gradlew

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/alex/Downloads/demo 6/build.gradle' line: 6

* What went wrong:
An exception occurred applying plugin request [id: 'org.hibernate.orm', version: '6.1.6.Final']
> Failed to apply plugin 'org.hibernate.orm'.
   > Could not create an instance of type org.hibernate.orm.tooling.gradle.HibernateOrmSpec.
      > Extension of type 'JavaPluginExtension' does not exist. Currently registered extension types: [ExtraPropertiesExtension, SpringBootExtension, StandardDependencyManagementExtension, SourceSetContainer]

```

**Comment by wilkinsona** [comment]
This sounds like another symptom of https://hibernate.atlassian.net/browse/HHH-15557. I suspect it will work if the Kotlin plugins are applied before the `org.hibernate.orm` plugin and without explicitly applying the `java` plugin. Can you please try that, @pettyalex?

**Comment by pettyalex** [comment]
That uncovers another layer of failure with the Hibernate Gradle plugin. In order to progress past this, I have to disable the enhanchement configuration on the hibernate plugin config block:

```
hibernate {
	enhancement {
		lazyInitialization true
		dirtyTracking true
		associationManagement true
	}
}
```


This is documented here, and it looks like the defaults are actually true for all of these already, so perhaps while the Hibernate Gradle plugin is being updated and fixed for these problems, start.spring.io could omit the entire hibernate plugin config block?

https://docs.jboss.org/hibernate/orm/6.1/userguide/html_single/Hibernate_User_Guide.html#tooling-gradle


Here's the failure that I see without deleting the hibernate plugin configuration:
```
 ./gradlew --stacktrace

FAILURE: Build failed with an exception.

* What went wrong:
class org.jetbrains.kotlin.gradle.tasks.KotlinCompile_Decorated cannot be cast to class org.gradle.api.tasks.compile.AbstractCompile (org.jetbrains.kotlin.gradle.tasks.KotlinCompile_Decorated is in unnamed module of loader org.gradle.internal.classloader.VisitableURLClassLoader @577a3025; org.gradle.api.tasks.compile.AbstractCompile is in unnamed module of loader org.gradle.initialization.MixInLegacyTypesClassLoader @6bf0219d)

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Exception is:
java.lang.ClassCastException: class org.jetbrains.kotlin.gradle.tasks.KotlinCompile_Decorated cannot be cast to class org.gradle.api.tasks.compile.AbstractCompile (org.jetbrains.kotlin.gradle.tasks.KotlinCompile_Decorated is in unnamed module of loader org.gradle.internal.classloader.VisitableURLClassLoader @577a3025; org.gradle.api.tasks.compile.AbstractCompile is in unnamed module of loader org.gradle.initialization.MixInLegacyTypesClassLoader @6bf0219d)
        at org.hibernate.orm.tooling.gradle.HibernateOrmPlugin.lambda$prepareEnhancement$1(HibernateOrmPlugin.java:72)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at org.gradle.configuration.internal.DefaultListenerBuildOperationDecorator$BuildOperationEmittingInvocationHandler$1.lambda$run$0(DefaultListenerBuildOperationDecorator.java:255)

```

**Comment by wilkinsona** [comment]
The documentation to which you have linked states that those three properties all default to false:

> The extension is of type EnhancementSpec which exposes the following properties:
>
> - enableLazyInitialization
> Whether to incorporate lazy loading support into the enhanced bytecode
> 
> - enableDirtyTracking
> Whether to incorporate dirty tracking into the enhanced bytecode
> 
> - enableAssociationManagement
> Whether to add bidirectional association management into the enhanced bytecode
>
> Which all default to false (disabled).

As such, I don't think we can omit the block.

**Comment by wilkinsona** [comment]
https://hibernate.atlassian.net/browse/HHH-15707 is tracking the class cast exception. Downgrading the plugin to 6.1.4 appears to resolve the problem so that may be an option in the meantime. I don't think we should do that by default as I'm not sure that we can be certain that it's needed.

@pettyalex please vote for the Hibernate issue. Hopefully they'll be able to apply the proposed patch or a similar fix sometime soon.

**Comment by wilkinsona** [comment]
I've updated Boot's wiki to describe this known limitation (https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-with-GraalVM#hibernate).
