### ISSUE TITLE
Utilize Gradle Toolchain for Java/Gradle projects

### ISSUE THREAD

**Issue by mdeinum** [spring-io/start.spring.io#1079]
As Gradle has some nice support for toolchains which make it quite easy to setup a JDK automatically. I think when using Gradle (the default now) as a build system, a java toolchain could be added with the selected version of Java. 

That would make it easier to run, import etc. the Gradle project, especially if the user doesn't have the proper JDK installed, then Gradle will download a version and use it. It also allows to run Gradle with for instance JDK11 and run the compile/test etc with the JDK provided in the toolchain.

**Comment by wilkinsona** [comment]
Duplicates https://github.com/spring-io/initializr/issues/1227 and https://github.com/spring-io/initializr/issues/1187.
