### ISSUE TITLE
Add spring-cloud-kubernetes entry

### ISSUE THREAD

**Issue by joshiste** [spring-io/start.spring.io#108]
Currently the starters from [spring-cloud-kubernetes](https://github.com/spring-cloud/spring-cloud-kubernetes) are missing.

**Comment by snicoll** [comment]
@joshiste please take the time to read the new issue section that defines a specific template for new entries proposal. Creating an empty issue here and ignoring the template is not going to get us anywhere.

Maintainer of Spring Cloud Kubernetes are probably the ones to ask as we prefer maintainer to make the request anyway.

**Comment by joshiste** [comment]
@snicoll sorry, I was just lazy, as it's one of the spring-cloud projects and didn't fill the template. I'll ask the maintainers if they plan to add this.
