### ISSUE TITLE
For Spring Boot Version 3.x (and higher) java versions below 17 can be selected

### ISSUE THREAD

**Issue by tho-myr** [spring-io/start.spring.io#1087]
i don't know if this is intentional or if it is possible to use spring boot 3.x and higher with java versions below 17

![2023-01-11_09h38_27](https://user-images.githubusercontent.com/105883588/211758106-790f984f-30ad-44dd-ac64-ea9b2c6d1bcf.png)

**Comment by wilkinsona** [comment]
Duplicates #1041.
