### ISSUE TITLE
Upgrade to Spring Cloud Azure 5.0.0 for apps using Spring Boot 3.0

### ISSUE THREAD

**Issue by moarychan** [spring-io/start.spring.io#1090]
We finally decided not to skip the major version 5.0, and use version 5.x to support Spring boot 3. 

This is an upgrade for [Spring Cloud Azure 5.0.0 GA](https://github.com/Azure/azure-sdk-for-java/issues/31895), the artifact id `spring-cloud-azure-starter-data-cosmos` is still unavailable in `5.0.0`.

- Maven: https://repo1.maven.org/maven2/com/azure/spring/spring-cloud-azure-dependencies/5.0.0/
- Compatible Spring Boot version: https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/spring/CHANGELOG.md#500-2023-01-17

**Comment by moarychan** [comment]
Hi @bclozel , I found an outdated content for `azure-support`, could you help to update this reference link information? The details as below:

**description**: `Spring Cloud Azure Reference Documentation` -> `Spring Cloud Azure developer guide`
**href**: `https://microsoft.github.io/spring-cloud-azure/current/reference/html/index.html` - > `https://aka.ms/spring/msdocs/developer-guide`

**Comment by bclozel** [comment]
@moarychan Yes! This will be taken care of in #1097
