### ISSUE TITLE
Update description of MySQL dependency to indicate that it's JDBC-only

### ISSUE THREAD

**Issue by mitu2** [spring-io/start.spring.io#1092]
My selected configuration link [URL](https://start.spring.io/#!type=maven-project&language=java&platformVersion=3.0.1&packaging=jar&jvmVersion=17&groupId=com.example&artifactId=demo&name=demo&description=Demo%20project%20for%20Spring%20Boot&packageName=com.example.demo&dependencies=data-r2dbc,mysql,devtools,data-jpa,webflux)

Generated pom
``` xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>3.0.1</version>
    <relativePath/> <!-- lookup parent from repository -->
  </parent>
  <groupId>com.example</groupId>
  <artifactId>demo</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <name>demo</name>
  <description>Demo project for Spring Boot</description>
  <properties>
    <java.version>17</java.version>
  </properties>
  <dependencies>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-data-jpa</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-data-r2dbc</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-webflux</artifactId>
    </dependency>

    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-devtools</artifactId>
      <scope>runtime</scope>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>com.mysql</groupId>
      <artifactId>mysql-connector-j</artifactId>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-test</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.projectreactor</groupId>
      <artifactId>reactor-test</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
      </plugin>
    </plugins>
  </build>

</project>

```

The result did not generate the r2dbc dependency corresponding to mysql. I tried to select another SQL drive, and the others are normal

**Comment by wilkinsona** [comment]
Thanks for reporting this. The description of the MySQL Driver is now inaccurate as there's no up-to-date R2DBC Driver for R2DBC. https://github.com/mirromutth/r2dbc-mysql is the MySQL Driver implementation but it only supports R2DBC 0.8.x. Spring Boot 2.7.x requires R2DBC 0.9 and 3.0.x requires 1.0. We'll update the description to indicate that it's JDBC-only.

**Comment by mitu2** [comment]
okay


在 2023年1月18日，17:51，Andy Wilkinson ***@***.***> 写道：

﻿

Thanks for reporting this. The description of the MySQL Driver is now inaccurate as there's no up-to-date R2DBC Driver for R2DBC. https://github.com/mirromutth/r2dbc-mysql is the MySQL Driver implementation but it only supports R2DBC 0.8.x. Spring Boot 2.7.x requires R2DBC 0.9 and 3.0.x requires 1.0. We'll update the description to indicate that it's JDBC-only.
