### ISSUE TITLE
Upgrade to Okta Spring Boot 3.0.0 not listed

### ISSUE THREAD

**Issue by arvindkrishnakumar-okta** [spring-io/start.spring.io#1099]
I submitted #1096 and #1098 yesterday in an effort to add the latest Okta Spring Boot version 3 SDK (upgraded to work with Spring Boot 3). 

But I don't see this change effected/listed in [start.spring.io](https://start.spring.io/) UI:

![image](https://user-images.githubusercontent.com/61501885/213691160-db285e53-0c05-4bc0-8717-d49462a71df6.png)

![image](https://user-images.githubusercontent.com/61501885/213691328-810141f0-13b3-4b1f-b376-f087211a9a6b.png)
 
Can you please check and let me know if I am missing something here?

cc: @bclozel @snicoll

**Comment by bclozel** [comment]
Thanks @wilkinsona

**Comment by arvindkrishnakumar-okta** [comment]
@bclozel I still don't see it, should I have to wait for sometime for deployments to take effect?

**Comment by bclozel** [comment]
It's live in production, maybe our CDN is caching some metadata right now?

![image](https://user-images.githubusercontent.com/103264/213700391-abf0b25a-78df-4f8c-9757-04ad1d0bc9b5.png)
