### ISSUE TITLE
Upgrade to Wavefront for Spring Boot 3.0.1

### ISSUE THREAD

**Issue by oppegard** [spring-io/start.spring.io#1102]
A new version of [Wavefront for Spring Boot](https://github.com/wavefrontHQ/wavefront-spring-boot/tree/springboot3) with Boot 3 compatibility has been released. When the "Wavefront" entry is chosen, we'd like the following two dependencies added:

```xml
<dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>com.wavefront</groupId>
      <artifactId>wavefront-spring-boot-bom</artifactId>
      <version>3.0.1</version>
      <type>pom</type>
      <scope>import</scope>
    </dependency>
  </dependencies>
</dependencyManagement>

...

<dependency>
  <groupId>com.wavefront</groupId>
  <artifactId>wavefront-spring-boot-starter</artifactId>
</dependency>
```

This will bring parity from the prior Spring Boot 2 experience, which auto-provisions a freemium Wavefront account.

**Comment by bclozel** [comment]
Thanks for letting us know @oppegard, this is now live in production.

**Comment by oppegard** [comment]
@bclozel I was trying out the updated Initialzr and am confused by the results. Prior to the update, when I selected Wavefront in a vanilla Boot 3 app the following dependencies were added:

- spring-boot-starter-actuator
- micrometer-registry-wavefront

Now the behavior is:
- spring-boot-starter-actuator
- wavefront-spring-boot-starter
- wavefront-spring-boot-bom

Should `micrometer-registry-wavefront` remain an explicit dependency that's added by Initalizr? If not, should I change `wavefront-spring-boot-starter` to make it a required dependency rather than optional at https://github.com/wavefrontHQ/wavefront-spring-boot/blob/springboot3/wavefront-spring-boot/pom.xml#L37-L41?

**Comment by oppegard** [comment]
@bclozel another Spring team member pointed out micrometer-registry-wavefront is in fact required in this module: https://github.com/wavefrontHQ/wavefront-spring-boot/blob/springboot3/wavefront-spring-boot-starter/pom.xml#L30.

Please don't take any action yet while I sort through this mess of modules.

**Comment by oppegard** [comment]
@bclozel all that's needed is:

- wavefront-spring-boot-bom
- wavefront-spring-boot-starter

The wavefront-spring-boot-starter includes both spring-boot-starter-actuator and micrometer-registry-wavefront, so neither are needed as an explicit dependency in the project generated by start.spring.io.

**Comment by bclozel** [comment]
The current behavior generates the following:

```
ext {
  set('wavefrontVersion', "3.0.1")
}

dependencies {
  implementation 'org.springframework.boot:spring-boot-starter-actuator'
  runtimeOnly 'com.wavefront:wavefront-spring-boot-starter'
  testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

dependencyManagement {
  imports {
    mavenBom "com.wavefront:wavefront-spring-boot-bom:${wavefrontVersion}"
  }
}
```

I believe we should keep the actuator starter dependency as it's for a different configuration.

**Comment by oppegard** [comment]
Ok, looks good to me. Thanks!
