### ISSUE TITLE
Update the doc link - Wavefront for Spring Boot

### ISSUE THREAD

**Issue by shavidissa** [spring-io/start.spring.io#1107]
Hello,

We have a new guide for Spring Boot 3. Can we please update link [1] to [2] for Spring Boot 3 components, please?

[1] https://docs.wavefront.com/wavefront_springboot.html - old content for Spring Boot 2
[2] https://docs.wavefront.com/wavefront_springboot3.html 

CC: @snicoll 

<img width="632" alt="update-link" src="https://user-images.githubusercontent.com/22474854/216183760-e7bc9ff4-724b-4175-ace6-10f94dc7ad48.png">

**Comment by bclozel** [comment]
Thanks for letting us know @shavidissa !
This change is now live.
