### ISSUE TITLE
The Java version is not considered in generation

### ISSUE THREAD

**Issue by renanlJ** [spring-io/start.spring.io#1123]
The selected version is not the same in pom.xml file

![screen_generation](https://user-images.githubusercontent.com/25470307/222309661-3669173f-c01d-436f-a361-09c379c344a3.JPG)

![pomxml](https://user-images.githubusercontent.com/25470307/222309685-b0836b26-db19-45a9-875e-caea9e0eb2c5.JPG)

**Comment by bclozel** [comment]
Spring Boot 3 requires Java 17 as a baseline so the server is fixing this invalid combination for you. The alternative would be a broken application.
This information is currently not reflected on the web UI as the metadata sent to clients does not contain all the information needed. See #1041 for more details on that.
