### ISSUE TITLE
Add support for Spring Data JDBC

### ISSUE THREAD

**Issue by belaso** [spring-io/start.spring.io#113]

**Comment by snicoll** [comment]
We've added support for Spring Data JDBC as a core starter but there isn't a dedicated entry for it. We do have a `JDBC` entry that represents the "base jdbc" starter (i.e. without Spring Data).

We should first work on #79 and make sure the names/grouping are explicit enough if we decide to keep two entries for this.

**Comment by schauder** [comment]
Is there a way I can help with this?

**Comment by snicoll** [comment]
Thanks for offering to help @schauder. We need to make up our mind as how to present this so help on getting a proper description + links to a sample would be useful.

**Comment by schauder** [comment]
This is the way I'd phrase it. HTH.

## JDBC API

Basic Database Connectivity API that defines how a client may connect an query a database.

This includes the popular `JdbcTemplate` making low level work with databases painless.


## Spring Data JDBC

Repositories as inspired by Domain Driven Design implemented directly with JDBC.

### Introductory Blog articles

https://spring.io/blog/2018/09/17/introducing-spring-data-jdbc
https://spring.io/blog/2018/09/24/spring-data-jdbc-references-and-aggregates

### Example project to get started

https://github.com/spring-projects/spring-data-examples/tree/master/jdbc/basics
