### ISSUE TITLE
Use Spring Boot 3.1's dependency management for Testcontainers

### ISSUE THREAD

**Issue by wilkinsona** [spring-io/start.spring.io#1139]
Once https://github.com/spring-projects/spring-boot/issues/34712 has been implemented, Spring Boot 3.1 will provide dependency management for Testcontainers. When generating a Spring Boot 3.1-based application, it will no longer be necessary to declare the Testcontainers bom in the `pom.xml` or `build.gradle`.

**Comment by snicoll** [comment]
It looks like this is available since Spring Boot `3.1.0-M2`.
