### ISSUE TITLE
When I run project I got this error

### ISSUE THREAD

**Issue by henish1400** [spring-io/start.spring.io#1140]
![image](https://user-images.githubusercontent.com/102351385/227106746-6c73bb1c-cf68-4232-b629-f6c046229d30.png)

**Comment by maciejwalkowiak** [comment]
@henish1400 you must have Java 17+ installed on your machine to build Spring Boot 3 application

**Comment by bclozel** [comment]
@maciejwalkowiak is right, Spring Boot 3 requires Java 17. This is not necessarily reflected in the web UI right now.

Duplicates #1041 
Also see https://github.com/spring-io/start.spring.io/issues/1123#issuecomment-1451398722
