### ISSUE TITLE
Add Spring Authorization Server

### ISSUE THREAD

**Issue by wilkinsona** [spring-io/start.spring.io#1144]
Spring Boot 3.1.0-M2 has added a new starter, `spring-boot-starter-oauth2-authorization-server`, for Spring Authorization Server. We should offer a corresponding dependency on start.spring.io.

**Comment by jongwooo** [comment]
Can I work on this issue?

**Comment by sjohnr** [comment]
Hi @wilkinsona, I believe this should be unblocked now. Is it ready to be taken up?

**Comment by sjohnr** [comment]
Thanks. @jongwooo did you still want to take this on? Otherwise, I'm happy to.

**Comment by jongwooo** [comment]
@sjohnr Thank you for letting me know! Do you mind if I give it a try and let you know?
