### ISSUE TITLE
Upgrade to Spring Cloud Azure 4.7.0

### ISSUE THREAD

**Issue by chenrujun** [spring-io/start.spring.io#1150]
1. Maven: https://repo1.maven.org/maven2/com/azure/spring/spring-cloud-azure-dependencies/4.7.0/
2. Compatible Spring Boot version: https://github.com/Azure/azure-sdk-for-java/blob/spring-cloud-azure_4.7.0/sdk/spring/CHANGELOG.md#470-2023-03-23

**Comment by snicoll** [comment]
Thanks for letting us know. We have a problem with our CI/CD infra at the moment so the changes will not show up shortly, as usual.
