### ISSUE TITLE
Add grafana-opentelemetry-starter

### ISSUE THREAD

**Issue by zeitlinger** [spring-io/start.spring.io#1161]
Hello,

I'm Gregor - working OpenTelemetry Java instrumentation at Grafana Labs.

The [Grafana LGTM stack](https://grafana.com/go/webinar/getting-started-with-grafana-lgtm-stack/) is a popular observability solution for OpenTelemetry, supporting logs, metrics, and tracing (available as OSS, Enterprise and Cloud).

The [grafana-opentelemetry-starter](https://github.com/grafana/grafana-opentelemetry-starter) bundles together 
- the new micrometer tracing in Spring Boot 3 for tracing
- the existing micrometer for metrics (it would be possible to switch to micrometer OTLP when https://github.com/spring-projects/spring-boot/pull/34508 is part of Boot 3.1)
- a [custom integration](https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/logback/logback-appender-1.0/library) for logs 

## Well-established project with a vibrant community

The starter itself is new, but the projects that comprise the LGTM stack have vibrant communities:
- [loki](https://github.com/grafana/loki) for logs
- [mimir](https://github.com/grafana/mimir) for metrics
- [tempo](https://github.com/grafana/tempo) for tracing
- [grafana](https://github.com/grafana/grafana) for the whole visualization, dashboards, explore, etc.

## Licence

- starter: [Apache 2.0](https://github.com/grafana/grafana-opentelemetry-starter/blob/main/LICENSE)
- opentelemetry-java-instrumentation: [Apache 2.0](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/LICENSE)
- opentelemetry-java: [Apache 2.0](https://github.com/open-telemetry/opentelemetry-java/blob/main/LICENSE)

## Issue Tracker URL

- https://github.com/grafana/grafana-opentelemetry-starter/issues

## Continuous integration

- Github actions: https://github.com/grafana/grafana-opentelemetry-starter/blob/main/.github/workflows/ci.yml
- Dependabot: https://github.com/grafana/grafana-opentelemetry-starter/blob/main/.github/dependabot.yml
- Compatibility should be achieved using Spring Boot's dependency management without overriding: [config](https://github.com/grafana/grafana-opentelemetry-starter/blob/main/build.gradle#L35-L53)

## Maven Central

- [Maven Central](https://central.sonatype.com/artifact/com.grafana/grafana-opentelemetry-starter/1.0.0)

## Configuration metadata

[spring-boot-configuration-processor](https://github.com/grafana/grafana-opentelemetry-starter/blob/main/build.gradle#L47)

## Version mappings

The starter supports Boot 3.0.4+

**Comment by zeitlinger** [comment]
Hi, is there anything I can do or that is missing?

**Comment by snicoll** [comment]
@zeitlinger I don't know as we haven't got the time to review the proposal yet. Sorry, and thank you for your patience.

**Comment by zeitlinger** [comment]
friendly ping :smile:

**Comment by jonatan-ivanov** [comment]
My two cents/questions (sorry for the delay):

- Is this starter considered stable? From the version number, it seems so but I'm not sure I see how the `-alpha` versions will not break the users in the future.
- Why the `snapshots` repo is needed?
- Micrometer has OTLP support, I'm not sure I understand why the OTel Metrics SDK (Micrometer bridge) is needed (basically `Observation API -> Micrometer Metrics API -> Registry` vs. `Observation API -> Micrometer Metrics API -> Micrometer Bridge (registry) -> OTel SDK -> OTel exporter`), it seems to me that it introduces unnecessary complexity.

**Comment by zeitlinger** [comment]
> * Is this starter considered stable? From the version number, it seems so but I'm not sure I see how the `-alpha` versions will not break the users in the future.

alpha is needed for internal configuration - the user visible configuration (in application.properties) is controlled by us, so we can keep it backwards compatible. I'm happy to dive into the details - but it's a longer explanation :smile: 

> * Why the `snapshots` repo is needed?

This was from early local testing - can be removed if necessary

> * Micrometer has OTLP support, I'm not sure I understand why the OTel Metrics SDK (Micrometer bridge) is needed (basically `Observation API -> Micrometer Metrics API -> Registry` vs. `Observation API -> Micrometer Metrics API -> Micrometer Bridge (registry) -> OTel SDK -> OTel exporter`), it seems to me that it introduces unnecessary complexity.

support for headers was missing in boot 3.0. With could create a new version targeting 3.1 to remove this complexity.
It would take away the possibility to use the otel env vars, but I'm not sure how much user value this feature.

**Comment by zeitlinger** [comment]
> I'm not sure this is true for logging, users need to interact with the OTel appender, don't they? There is not layer between the users and OTel that would prevent them experiencing breaking changes, right?

The main issue with logs was the stability of the SDK - which is [stable](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/sdk.md) now.
The appender is from the java agent repo - and therefore is still in alpha.

We could make a `GrafanaAppender` that simply extends `OpenTelemetryAppender` to guard against incompatible changes in the appender (e.g. a renamed property) - not sure if that's necessary. 

> > support for headers was missing in boot 3.0. With could create a new version targeting 3.1 to remove this complexity.
> 
> I would say support for headers was missing in Micrometer 1.10. You can use Micrometer 1.11 with Boot 3.0 (it's a drop-in replacement) and set-up headers from java (instead of a property), should still be a one-liner).

OK, didn't know.

> > It would take away the possibility to use the otel env vars, but I'm not sure how much user value this feature.
> 
> The OTLP registry does support OTel env vars. If users report that something is missing, we can add them but for Boot users I would highly recommend using Boot properties instead of OTel env vars.

OK, I'll make a version that's using this approach - would it make sense to call it "3.1" to align with the boot version?

**Comment by zeitlinger** [comment]
> The page you linked is about the specification of the SDK (markdown file) not the implementation (code/artifacts in Maven Central). I guess what the users will interact with is the [logback](https://search.maven.org/artifact/io.opentelemetry.instrumentation/opentelemetry-logback-appender-1.0/1.26.0-alpha/jar) and [log4j2](https://search.maven.org/artifact/io.opentelemetry.instrumentation/opentelemetry-log4j-appender-2.17) appenders (they are alpha right now). I think we should ask the Java SIG about them because maybe they are effectively stable just in the wrong place right now (moving should be ok/relatively quick I guess) and/or maybe there are plans to make the user-facing things stable. Based on the SDK spec being stable, I'm positive that the logging implementation pieces will stabilize pretty quickly.

good idea - added it to the agenda next week.
I've already seen that the Java SDK in in RC and will become stable next month.

> Oh one more thing: since boot supports both logback and log4j2, I think adding a short section to the docs how to replace the OTel logback support to the OTel log4j support might be a good idea (exclude the former, include the latter).

I think we can just include both since the appenders are very lightweight.

**Comment by snicoll** [comment]
This request has been opened for quite some time and we need feedback provided by @jonatan-ivanov to be processed before we can consider this again. I am going to close this now as we've discussed this internally and we'd like the integration to be more consistent with other similar entries first.
