### ISSUE TITLE
Add settings into application.properties file

### ISSUE THREAD

**Issue by maxkraft7** [spring-io/start.spring.io#1162]
When configuring a new spring project it would be a great addition if the `application.properties` File is already populated with some default values. To avoid different packages overriding different values, each package could have the option to add it's own profile. So if you for example add a H2-Driver it could also automatically create a `application-h2.properties` File and if multiple profiles are available it should be selectable which one should be the default. 

I always forget that I manually have to add the properties there.

**Comment by snicoll** [comment]
Thanks but we believe that default values are the one provided by Spring Boot. We've already had suggestions to fill the config with commented property for "documentation purpose", or to automatically infer a mandatory value based on a selected dependency. None of those were really compelling.

What property would you like to see added if H2 is selected?

**Comment by maxkraft7** [comment]
That Spring Boot provides default values is in general a good assumption. However in combination with H2 it leads to the program being not startable if any interaction with repositories takes place. 

For H2 specifically the bare minimum to get a in-memory database up and running would be very helpful. Like this for example:
```properties
spring.datasource.url=jdbc:h2:mem:h2db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=user
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
```

**Comment by snicoll** [comment]
> the bare minimum to get a in-memory database up and running would be very helpful.

None of the configuration options you've highlighted are necessary. Spring Boot will auto-configure in-memory H2 with JPA if H2 and JPA is selected. I am going to close this now but if you can provide an example where adding a configuration is mandatory and isn't something the user has to opt-in too, we can address that specifically. It probably won't be here.
