### ISSUE TITLE
Vaadin production profile should not set productionMode

### ISSUE THREAD

**Issue by snicoll** [spring-io/start.spring.io#1164]
Running an empty Maven-based Vaadin app with `-Pproduction` leads to:

```
[WARNING] The productionMode parameter no longer has any effect. Production mode is automatically enabled when you run the build-frontend target.
```

cc @mstahv

**Comment by mstahv** [comment]
Yeah, that is no more needed with Vaadin 24 and above. Now that I made #1165 to resolve this, started to think if that should be conditional in case somebody still makes Spring Boot 2.x + Vaadin 23.x project 🤔

**Comment by mstahv** [comment]
Or then postpone the removal of the parameter until Spring Boot 2.x is no more supported.

**Comment by snicoll** [comment]
I am in favor of the condition. Having a fresh project that triggers a warning is really nasty. Do you want to work on that or should I takeover?
