### ISSUE TITLE
Add missing quotes for consistency

### ISSUE THREAD

**Issue by jongwooo** [spring-io/start.spring.io#1188]
> compatibilityRange: 2.1.0.M2

In `./start-site/.../resources/application.yml`, the value of `compatibilityRange` is enclosed in quotation marks. However, in the case of the `OAuth2 Resource Server`, the quotes are missing. For consistency, the quotes should be added.

see [#1180 (comment)](https://github.com/spring-io/start.spring.io/pull/1181#discussion_r1201638045)

**Comment by snicoll** [comment]
@jongwooo thanks! For the record, there is no need to create both an issue and a PR as the latter supersedes the former. Going forward, you can submit the PR directly unless you want to validate that it is a valid concern (which we've already established in the other PR).

Superseded by #1189

**Comment by jongwooo** [comment]
@snicoll Thank you for letting me know:)
