### ISSUE TITLE
Tables in HELP.md do not preview correctly

### ISSUE THREAD

**Issue by wilkinsona** [spring-io/start.spring.io#1203]
When exploring [this project](https://start.spring.io/#!type=gradle-project&language=java&platformVersion=3.1.0&packaging=jar&jvmVersion=17&groupId=com.example&artifactId=demo&name=demo&description=Demo%20project%20for%20Spring%20Boot&packageName=com.example.demo&dependencies=docker-compose,postgresql,data-elasticsearch) and viewing a preview of HELP.md, the table of services does not render correctly:

<img width="852" alt="Screenshot 2023-05-31 at 19 01 23" src="https://github.com/spring-io/start.spring.io/assets/914682/8204c1c2-1768-468e-9512-22cc13d08437">

**Comment by snicoll** [comment]
We've moved to a bullet list.
