### ISSUE TITLE
Client does not build if node-gyp is not installed

### ISSUE THREAD

**Issue by snicoll** [spring-io/start.spring.io#1206]
Since the upgrade to a more recent version of Node, `node-gyp` needs to be available in the path. It looks like the frontend plugin installed it but it doesn't seem to be included in the execution path.

**Comment by pmverma** [comment]
We have deployed this repo with a bit of customization and now, our build is failing for the same reason.
Is there any workaround available apart from using build image with node-gyp installed?

**Comment by bendem** [comment]
fibers uses node-gyp but doesn't depend on it, it seems to cause this issue.

**Comment by bendem** [comment]
So I've looked around and I can't see fibers used anywhere. Removed it from package.json and everything is fine. Might want to check if there are other libraries that are not used by the project but still installed.

**Comment by snicoll** [comment]
I am not used to this and I thought a clean build would fix it but the build was cached. Turns out the update does take gyp into account in a weird way
