### ISSUE TITLE
Fix compatiblity range for Okta Spring Boot

### ISSUE THREAD

**Issue by arvindkrishnakumar-okta** [spring-io/start.spring.io#1207]
Presently, Okta Spring Boot Starter does not show up for Spring Boot version 3.1.0:

Looks like the entry in https://github.com/spring-io/start.spring.io/pull/1200/files isn't right?

**Comment by snicoll** [comment]
@arvindkrishnakumar-okta that's because the range wasn't updated. I missed it while reviewing but I wouldn't have if I had done the change myself. Running the site locally and verify that your PR does what you intend before submitting should help with that. Thanks!
