### ISSUE TITLE
Consider using latest Gradle release when generating projects

### ISSUE THREAD

**Issue by rpalcolea** [spring-io/start.spring.io#1209]
Hi folks,

I noticed that creating a new project with Spring Boot 3.1.x + Gradle results in using Gradle 7.6.1 where latest is 8.1.1

I'm wondering if you have considered creating new projects using latest gradle available in https://services.gradle.org/versions/current

**Comment by wilkinsona** [comment]
Some projects, for example those that use Spring REST Docs, use the `org.asciidoctor.jvm.convert` plugin. Unfortunately, there's no non-alpha release of that plugin that is compatible with Gradle 8.x. I would prefer the version of Gradle to be constant, irrespective of the dependencies that are chosen, so the latest 7.x release is our best option at the moment.

@ysb33r @aalmiray are there any plans for a 4.0.0 release of `org.asciidoctor.jvm.convert`? Anything we can do to help?

**Comment by lenis0012** [comment]
@wilkinsona this should really be considered a bug.

Spring Initializr gives the option for creating a project with Java 20, but Gradle 7.x does not support Java 20.
Java 20 support was added in Gradle 8.1. (see https://github.com/gradle/gradle/issues/23488).

Currently start.spring.io cannot create a working project for Gradle with JDK 20

**Comment by wilkinsona** [comment]
> Unfortunately, there's no non-alpha release of that plugin that is compatible with Gradle 8.x.

I think I was mistaken. A Gradle 7.6.x build produces deprecation warnings for an incompatibility with Gradle 8:

> The `JavaExecHandleBuilder.setMain(String)` method has been deprecated. This is scheduled to be removed in Gradle 8.0. Please use the `mainClass` property instead.

However, this hasn't come to pass as https://github.com/gradle/gradle/commit/f2d6771b41e1ec8b158262c584c04bc98831040a was added specifically to get things working again with Asciidoctor.

I think we should be able to upgrade to Gradle 8.1.

**Comment by wilkinsona** [comment]
Superseded by https://github.com/spring-io/initializr/issues/1433.
