### ISSUE TITLE
Improve Elasticsearch test application

### ISSUE THREAD

**Issue by eddumelendez** [spring-io/start.spring.io#1220]
Current implementation uses Elasticsearch 8 image. However, Elasticsearch 8 has security enabled by default. 

Some proposals:
* Disable security via env var `xpack.security.enabled=false`
* Add customizer setting the `SSLContext` and credentials properties

```java
@TestConfiguration
static class SSL {

	@Bean
	public RestClientBuilderCustomizer customizer() {
		return new RestClientBuilderCustomizer() {
			@Override
			public void customize(RestClientBuilder builder) {

			}

			@Override
			public void customize(HttpAsyncClientBuilder builder) {
				builder.setSSLContext(elasticsearch.createSslContextFromCa());
			}
		};
	}

}
```

* Use Elasticsearch 7 image

See https://github.com/spring-projects/spring-boot/issues/35926

**Comment by snicoll** [comment]
Thanks for the report. The customizer is a bit too involved, I think. Let's see how the Spring Boot issue you've raised pan out and we'll adapt. In the meantime, I've downgraded.
