### ISSUE TITLE
Upgrade to Spring Cloud Azure 4.9.0-beta.1

### ISSUE THREAD

**Issue by Netyyyy** [spring-io/start.spring.io#1233]
1. Maven: https://repo1.maven.org/maven2/com/azure/spring/spring-cloud-azure-dependencies/4.9.0-beta.1/
2. Compatible Spring Boot version: https://github.com/Azure/azure-sdk-for-java/blob/spring-cloud-azure_4.9.0-beta.1/sdk/spring/CHANGELOG.md#490-beta1-2023-06-28

**Comment by wilkinsona** [comment]
Why do we need this issue as well as #1232? Doesn't 4.9.0 supersede 4.9.0-beta.1?

**Comment by Netyyyy** [comment]
> 

Well, this is because we released a beta version of `spring-cloud-azure-starter-openai` in 4.9.0-beta.1, which is not yet included in 4.9.0.

**Comment by Netyyyy** [comment]
> Why do we need this issue as well as #1232? Doesn't 4.9.0 supersede 4.9.0-beta.1?

Well, this is because we released a beta version of `spring-cloud-azure-starter-openai` in 4.9.0-beta.1, which is not yet included in 4.9.0.

**Comment by wilkinsona** [comment]
Given that 4.9.0-beta.1 and 4.9.0 support the same Spring Boot versions, we can't offer both at the same time. I'd also prefer not to offer a beta version. Should this be closed in favor of #1232?

**Comment by Netyyyy** [comment]
> Given that 4.9.0-beta.1 and 4.9.0 support the same Spring Boot versions, we can't offer both at the same time. I'd also prefer not to offer a beta version. Should this be closed in favor of #1232?

OK, close the beta version.
