### ISSUE TITLE
Update screenshot  to include a more recent GA version of Spring Boot

### ISSUE THREAD

**Issue by knlkshyp** [spring-io/start.spring.io#1242]
At page https://github.com/spring-io/start.spring.io/blob/main/USING.adoc, the current screenshot shows Spring Boot version 2.4.0 and has not been updated since long.
<img width="1440" alt="start-spring-io-spring-version-old" src="https://github.com/spring-io/start.spring.io/assets/15921119/03c9f1ad-1fcb-4f83-90ce-6db9fd02ae26">

Atleast this should be updated to the current major version of Spring Boot i.e. 3.x.x

**Comment by CodeWithSouma** [comment]
I want to fix this issue

**Comment by snicoll** [comment]
Thanks @CodeWithSouma the issue is yours.

**Comment by snicoll** [comment]
Closing in favor of PR #1249
