### ISSUE TITLE
Spring Pulsar should be enabled for Spring Boot 3.0.0 -> 3.1.x

### ISSUE THREAD

**Issue by onobc** [spring-io/start.spring.io#1244]
The `0.2.x` line of Spring Pulsar framework works w/ Spring Boot `3.0.x` and `3.1.x`.

However, currently it is constrained to `3.0.x` [as follows](https://github.com/spring-io/start.spring.io/blob/8188faf2e0ab2910dc491c361ea9bf4a7bfd042b/start-site/src/main/resources/application.yml#L779):
```
compatibilityRange: "[3.0.0,3.1.0-M1)"
```

This  range needs to be extended to allow `3.1.x` as follows:
```
compatibilityRange: "[3.0.0,3.2.0-SNAPSHOT)"
```

It is expected to be disabled with SB `3.2.x`.

**Comment by snicoll** [comment]
Thanks for letting us know @onobc. For the record, we use exclude range on the first milestone of the next generation (see the other examples in the metadata file).

We consider a snapshot to be always the most recent artifact for a given version so your suggestion would have allowed any milestones of `3.2.0` to be selected.
