### ISSUE TITLE
Harmonize description of Mustache with other template engine entries

### ISSUE THREAD

**Issue by manueljordan** [spring-io/start.spring.io#1246]
It seems it is a bug

At https://start.spring.io when the dialog window to include a Dependency is opened, if is written the `Web` search key then appears a list of options based on Web as expected... for example `Thymeleaf` and `Apache FreeMarker`.

*but* Why `Mustache` does not appear? Of course if in the search text box is written at least the `mus` term then `Mustache` appears

**Comment by snicoll** [comment]
I don't think it is. Mustache is in the "Template Engines" group where it belongs. Thymeleaf has "web" in its description which explains why it shows up. Same for Freemarker but I would argue relying on that is the wrong expecation.

Anyway, Mustache works for web and non web environment so I don't think we need to stick to that specifically.

**Comment by wilkinsona** [comment]
> Anyway, Mustache works for web and non web environment so I don't think we need to stick to that specifically.

As do Thymeleaf and Freemarker and their descriptions state as much:

https://github.com/spring-io/start.spring.io/blob/fe713f2d9030791ec487dbb5e2ec5772046398a5/start-site/src/main/resources/application.yml#L379

https://github.com/spring-io/start.spring.io/blob/fe713f2d9030791ec487dbb5e2ec5772046398a5/start-site/src/main/resources/application.yml#L370

I think there's an inconsistency here that it would be good to address. I would do so by revising the description of Mustache.

**Comment by wilkinsona** [comment]
This is the current description for Mustache:

> Logic-less Templates. There are no if statements, else clauses, or for loops. Instead there are only tags.

@snicoll WDYT about changing this to:

> Logic-less templates for both web and standalone environments. There are no if statements, else clauses, or for loops. Instead there are only tags.
