### ISSUE TITLE
I am not able to create a Spring Boot 3 application with Azure Cosmos DB

### ISSUE THREAD

**Issue by diepet** [spring-io/start.spring.io#1252]
When I try to create a Spring Boot 3 app using Azure Cosmos DB I receive an incompatibility error (see attached image).

![boot3cosmosdb](https://github.com/spring-io/initializr/assets/5221672/afd7a2b3-104d-4b43-95ee-2756c20d0362)

But, since Spring Azure Cloud 5.3.0, Azure Cosmos DB is fully supported in Spring Boot 3.x

Check this official article from Microsoft for confirm: [https://techcommunity.microsoft.com/t5/apps-on-azure-blog/announcing-spring-cloud-azure-4-9-0-and-5-3-0-now-generally/ba-p/3865649](https://techcommunity.microsoft.com/t5/apps-on-azure-blog/announcing-spring-cloud-azure-4-9-0-and-5-3-0-now-generally/ba-p/3865649)

Could you kindly fix/update the metadata?

Thanks in advance for your support

**Comment by wilkinsona** [comment]
@snicoll should this have been updated as part of #1234?

**Comment by snicoll** [comment]
Probably, I wish this was a bit more explicit though. I'll take care of it.
