### ISSUE TITLE
Upgrade to Picocli 4.7.4

### ISSUE THREAD

**Issue by snicoll** [spring-io/start.spring.io#1257]

**Comment by snicoll** [comment]
@remkop Looking at the [README](https://github.com/remkop/picocli/tree/main/picocli-spring-boot-starter), the starter does not seem to be tested with Spring Boot 3. I can see that we made it available with Spring Boot 3 when we upgraded to `4.7.0`. I can only assume that it was because the used of [`@AutoConfiguration` ](https://github.com/remkop/picocli/pull/1778).

It would be nice to test it with Spring Boot 3 and follow along as we're working on 3.2 already and the entry is disabled with the default Spring Boot version on the site

(cc @bclozel)

**Comment by remkop** [comment]
@snicoll @bclozel 

I fixed the picocli build so that it uses the most recent Spring version and stays up-to-date when running and testing on Java 17+.

I updated the [README](https://github.com/remkop/picocli/tree/main/picocli-spring-boot-starter) accordingly.
Thanks for the heads-up!
