### ISSUE TITLE
Upgrade to Spring Cloud Services 4.0.3

### ISSUE THREAD

**Issue by snicoll** [spring-io/start.spring.io#1258]

**Comment by snicoll** [comment]
@kvmw we'd like such issue to be created by the project team as we don't have the resource to figure out this out. Right now both TAS entries are disabled with the default version, which led me to research this. 

FYI, our policy is to remove entries that are not upgraded regularly. Thanks!

**Comment by kvmw** [comment]
Thanks @snicoll. I'll take care of this in the future releases.
