### ISSUE TITLE
Add support for java-cfenv

### ISSUE THREAD

**Issue by markpollack** [spring-io/start.spring.io#126]
The java-cfenv library is the replacement for the cloud foundry connector libraries, which are now in maintenance mode.  New functionality will be added to only to the java-cfenv library, for example for volume services and support for CF's SSO based on Spring Security 5 oauth.

The java-cfenv library provides a more Boot centric way to connect to Cloud Foundry services.  You can read more about it from the blog https://spring.io/blog/2019/02/15/introducing-java-cfenv-a-new-library-for-accessing-cloud-foundry-services and on the github site - https://github.com/pivotal-cf/java-cfenv

**Comment by making** [comment]
waiting for https://github.com/pivotal-cf/java-cfenv/issues/76
cc: @dyroberts

**Comment by pivotal-david-osullivan** [comment]
Hi all, adding support for java-cfenv was previously waiting on https://github.com/cloudfoundry/java-buildpack/issues/779, however this is no longer blocked as per the [latest comment](https://github.com/cloudfoundry/java-buildpack/issues/779#issuecomment-1084682829).

Could adding this to the Initializr be revisited?

**Comment by wilkinsona** [comment]
My reading of https://github.com/cloudfoundry/java-buildpack/issues/779 is that decision has been made about the path things are going to take, but no steps down that path have been taken. As I understand it, that means that the buildpacks will still use Spring Auto Reconfiguration by default and that users would still have to disable SAR to use java-cfenv so things haven't really changed for users.

**Comment by bclozel** [comment]
Spring Auto Reconfiguration & Spring Cloud Connectors will be still the default until March 2023, we need to wait for this new date to consider a change here.
https://github.com/cloudfoundry/java-buildpack/issues/951#issuecomment-1305937379

**Comment by snicoll** [comment]
This was opened 4 years ago without any actionable step so I am going to close this now.

**Comment by anthonydahanne** [comment]
Just an update on what the [Java Buildpack for CloudFoundry](https://github.com/cloudfoundry/java-buildpack) injects in 2024 to a spring boot app (that neither contains SAR / SCC nor Java-cfenv)
* Spring Boot 2: it'll still get SAR / SCC
* [Spring Boot 3 and later](https://github.com/cloudfoundry/java-buildpack/blob/main/docs/framework-java-cfenv.md): it'll get java-cfenv

Back to start.spring.io, that really does not matter if it does not provide the option for users to add Java-cfenv; it will be injected by the CF JBP at deployment time.
