### ISSUE TITLE
I am selecting JDK 11 but the downloaded project contains the pom.xml with version JDK 17 by default.

### ISSUE THREAD

**Issue by ppdmartell** [spring-io/start.spring.io#1270]
Greetings, I am using start.spring.io for a small example exercise and even when I select the JDK 11, the project gets downloaded as configured for JDK 17, like if it were bugged. I have tried three times. Maybe it's just me being wrong here.

![Screenshot 2023-08-03 at 09-23-12 Spring Initializr](https://github.com/spring-io/start.spring.io/assets/10564444/83e1a3cc-476a-43b0-8f1a-117bcc4be399)

![Screenshot from 2023-08-03 09-24-48](https://github.com/spring-io/start.spring.io/assets/10564444/fbf39e03-cea3-4789-bac2-302a97a593ca)

**Comment by wilkinsona** [comment]
Duplicates #1041.
