### ISSUE TITLE
Upgrade to Sentry 6.28.0

### ISSUE THREAD

**Issue by snicoll** [spring-io/start.spring.io#1272]
ping @adinauer - should we upgrade? 

We don't have an automated process to upgrade third party dependencies like Sentry so we need your help to let us know when a new release is out.

**Comment by adinauer** [comment]
@snicoll please wait for `6.28.0` which will be released soon.

**Comment by adinauer** [comment]
For the future, do you mind, if we simply open a PR to bump the version whenever there's significant changes in our SDK?

**Comment by snicoll** [comment]
I don't mind a PR at all, but I think it's a bit odd to create a new project that uses a version that's behind. I suppose your users want the latest for new projects, irrespective of it having a significant change or not. In short, I prefer a PR when a new version is out, unless the version has known issues.

**Comment by snicoll** [comment]
Closing in favor or PR #1274
