### ISSUE TITLE
Use reactive variant of Spring Cloud Resilience4J with a reactive web application

### ISSUE THREAD

**Issue by mraible** [spring-io/start.spring.io#1300]
Is it possible to get `spring-cloud-starter-circuitbreaker-reactor-resilience4j` from http://start.spring.io? It seems that there's only `spring-cloud-starter-circuitbreaker-resilience4j` available. I can easily change the dependency after, but it'd be cool if I could do something like this and get the reactor version:

```shell
https http://start.spring.io/starter.zip bootVersion==3.1.3 \   
  artifactId==api-gateway name==api-gateway baseDir==api-gateway \   
  dependencies==cloud-eureka,cloud-gateway,cloud-resilience4j | tar -xzvf -
```

**Comment by snicoll** [comment]
Thanks for the report. When we detect a webflux application, we swap the starter to the reactor variant automatically. We can refine a bit more if that turns out to be incomplete.
