### ISSUE TITLE
Set spring.application.name in application.properties

### ISSUE THREAD

**Issue by snicoll** [spring-io/start.spring.io#133]

**Comment by snicoll** [comment]
@OlgaMaciaszek do you think this is still applicable? I remember that using the `artifactId` as a default value for this property was a good think. I wonder though if Spring Cloud at large is affected or only a specify subset of modules?

**Comment by OlgaMaciaszek** [comment]
Makes sense to me. It's used for bootstrapping when working with SC Config and also for service discovery.

**Comment by mhalbritter** [comment]
I wonder if we should set that by default for every application. Some components, unrelated to Cloud, make use of that application name, e.g. the distributed tracing or the log correlation feature.

**Comment by jonatan-ivanov** [comment]
Always setting it would make sense to me, e.g.: reusing the name field from the project metadata section.

**Comment by OlgaMaciaszek** [comment]
One of the things to keep in mind is that we were planning this for a major release. At this point we have a default when that is missing, so in order to avoid lack of compatibility, it should go along with a Cloud major.

**Comment by spencergibb** [comment]
@mhalbritter I believe it would be ok in a minor. This is just setting a property, not changing an API. If a user wants the previous behavior, they can delete the property. Maybe we could schedule this to coincide with the 2024.0 Spring Cloud release train Q4 2024 compatible with boot 3.4?

**Comment by mhalbritter** [comment]
I'll bring it up in our next meeting and let you know what we decided. Thanks for all the input!

**Comment by mhalbritter** [comment]
@OlgaMaciaszek @spencergibb I don't quite understand what is needed on cloud side for this to work.

My plan is to always add the `spring.application.name` in the `application.properties`, regardless of selected dependencies. Are there any objections from your side?

@OlgaMaciaszek 

> One of the things to keep in mind is that we were planning **this** for a major release.

I don't understand what is "this" here?

**Comment by OlgaMaciaszek** [comment]
Having that change added; but after more discussion in the team, we think it's ok to add this at any point.

**Comment by mhalbritter** [comment]
Great, thanks!

**Comment by mhalbritter** [comment]
Done in d3e96c1b1bf3c89a59aa07f9c2939168830f66a5.
