### ISSUE TITLE
Add timefold-solver to start.spring.io

### ISSUE THREAD

**Issue by ge0ffrey** [spring-io/start.spring.io#1331]
[Timefold](https://timefold.ai) is an open source planning optimization solver that is used across the globe, often with Spring.
It's the continuation/fork of OptaPlanner, backed by a dedicated open source planning optimization company and it is now 100% independent of IBM/Red Hat.

GAV: https://central.sonatype.com/artifact/ai.timefold.solver/timefold-solver-spring-boot-starter

- [X] Code of Conduct

- [X] Well-established project with a vibrant community
https://github.com/TimefoldAI/timefold-solver - 360 stars in 5 months
https://stackoverflow.com/questions/tagged/timefold - 68 questions in 5 months
[Month](https://github.com/TimefoldAI/timefold-solver/releases) - monthly releases with multiple contributors

- [X] Ongoing maintenance
https://github.com/TimefoldAI/timefold-quickstarts/tree/stable/technology/java-spring-boot - we regularly update the spring version both in the solver repo and in the quickstarts repo. We will update it here too.

- [X] Licence
https://github.com/TimefoldAI/timefold-solver/blob/main/LICENSE.txt - Apache License

- [X] Issue Tracker URL
https://github.com/TimefoldAI/timefold-solver/issues

- [X] Continuous integration
https://github.com/TimefoldAI/timefold-quickstarts/tree/stable/.github/workflows GitHub actions run both maven and gradle builds on the spring boot quickstarts
https://github.com/TimefoldAI/timefold-quickstarts/blob/stable/technology/java-spring-boot/pom.xml#L21 this quickstart cleanly imports spring-boot-dependencies without nasty overrides

- [X] Maven Central
https://central.sonatype.com/artifact/ai.timefold.solver/timefold-solver-spring-boot-starter

- [X] Starter and all of its dependencies are available on Maven Central.

- [X] Configuration metadata
If you starter provides `@ConfigurationProperties` it should provide metadata for those
properties to enable auto-completion in the IDE. Metadata can be provided by adding
field level documentation on each of the properties and adding the
`spring-boot-configuration-processor` to your build.

- [X] Starter provides metadata, including documentation, for all its configuration
properties.
https://timefold.ai/docs/timefold-solver/latest/integration/integration#integrationWithSpringBoot We are considering to make Spring integration a top level chapter in the docs, as many users are looking for it

- [X] Build system integration
We don't have custom timefold build plugins

- [X] Version mappings
spring-boot 2.x: timefold-solver 0.8.x
spring-boot 3.x: timefold-solver 1.x

- [X] Links to additional resources

* Reference documentation: https://timefold.ai/docs/timefold-solver/latest/quickstart/spring-boot/spring-boot-quickstart#springBootJavaQuickStart
* Sample: https://github.com/TimefoldAI/timefold-quickstarts/tree/stable/technology/java-spring-boot

**Comment by wilkinsona** [comment]
@ge0ffrey I don't think it's a blocker for this by any means, but I have just noticed that your configuration property descriptions contain some javadoc syntax. This results in descriptions like this appearing in a user's IDE:

```
A classpath resource to read the solver configuration XML. Defaults to {@value #DEFAULT_SOLVER_CONFIG_URL}.
If this property isn't specified, that {@value #DEFAULT_SOLVER_CONFIG_URL} file is optional.
```

I'd recommend rewriting the descriptions to avoid using any javadoc tags. The example above would read something like this instead:

```
A classpath resource to read the solver configuration XML. Defaults to solverConfig.xml.
If this property isn't specified, that solverConfig.xml file is optional.
```

**Comment by ge0ffrey** [comment]
@wilkinsona Thank you!
We're tracking the configuration property javadoc syntax issue here:
  https://github.com/TimefoldAI/timefold-solver/issues/387
I am hoping we can get that fixed for 1.4.0

I'll look into your other questions in a minute.

**Comment by ge0ffrey** [comment]
>     * Is I/O the right group for the dependency to go in? While not a perfect match, it feels like the best of the options available.

From the current categories, I agree that `I/O` is the best match. Timefold basically takes a planning problem as input and ouputs a planning solution. Maybe, over time, as more starters are added (such as langchain4j), it could make sense to make a dedicated `AI` category?

>     * Are the links in the generated HELP.md the best they could be?

Where can I find that generated HELP.md file? The 2 links in application.yml are perfect, so I presume the HELP.md will be too?

> When Timefold Solver is added to an app it will fail to start due to a missing `@PlanningSolution`. I think we should try to help users move on from that.

I believe this probably bug, let me confirm if we'll fix it upstream:
The spring boot starter should not fail if no classes have a `@PlanningSolution` or `@PlanningEntity` annotation and no `SolverManager`, `SolutionManager`, etc is autowired/injected. It should just do nothing.
https://github.com/TimefoldAI/timefold-solver/issues/388

> We could link to https://timefold.ai/docs/timefold-solver/latest/configuration/configuration, possibly in place of the link to https://timefold.ai/docs/timefold-solver/latest/quickstart/spring-boot/spring-boot-quickstart as it's covered by the link to the sample.

Over time, I feel like we need a dedicated "Spring" chapter in the Timefold Solver documentation, with a quick start, list of configuration properties, etc. Most people have trouble finding the config properties section: https://timefold.ai/docs/timefold-solver/latest/integration/integration#integrationWithSpringBoot (it's well hidden). If that happens, I'll provide a PR to update the links in application.yml (although will likely redirect too).

**Comment by wilkinsona** [comment]
Thanks, @ge0ffrey. With the changes coming in https://github.com/TimefoldAI/timefold-solver/issues/388 I think we're good here. We can refine as needed based on feedback and as Timefold evolves.

**Comment by wilkinsona** [comment]
This change is now live.

**Comment by ge0ffrey** [comment]
Thank you, Andy!
