### ISSUE TITLE
Local Spring Boot Starter image

### ISSUE THREAD

**Issue by dcyrille18** [spring-io/start.spring.io#1353]
Refering to the same problem of the following issue https://github.com/spring-io/initializr/issues/310#issue-188610357

I'm trying to run the initializr-service behind a corporate proxy and I am getting some proxy exception, I resolved the one concerning the spring-boot versions by setting ```initializr.env.springBootMetadataUrl=""``` in the corresponding application.yml file but now, the next error arrived when I try to generate an archive.

Is it possible to have the archive of the desired spring-boot versions directly embedded in the jar ?

Thanks.

**Comment by snicoll** [comment]
> I don't know if you can move this issue ?

I just did that.

> But now I have an some other errors due to my proxy, when I try to generate my project, such as, for example:

Yes, start.spring.io is resolving a number of things using [`initializr-version-resolver`](https://github.com/spring-io/initializr/tree/main/initializr-version-resolver) and that downloads maven poms (BOMs) to read metadata in them. Those contributors require an access to Maven Central. 

If you want to run start.spring.io behind a corporate proxy, there are a number of contributions that wouldn't work anymore. If you search for all usage of `io.spring.initializr.versionresolver.MavenVersionResolver` you'll find them. You could decide to disable them or replace them in your fork with an hard-coded version.

This project is our production version and we don't intend to make it as flexible as the library. I am going to close this and I hope the above is helpful.

**Comment by snicoll** [comment]
Sorry answering my own question now that I see the end of your command. If you need to configure the proxy, this is addressed in the reference guide I shared earlier:

> If you are behind a proxy, or need to customize the RestTemplate that is used behind the scenes, you can define a RestTemplateCustomizer bean in your configuration

**Comment by cdromas** [comment]
I deactivated all MavenVersionResolver and it's now working for our test. We will see how to do this more neatly later.
Thank you for your support @snicoll
