### ISSUE TITLE
Unable to use both Java 21 and Spring Data JPA

### ISSUE THREAD

**Issue by arkadiusz97** [spring-io/start.spring.io#1354]
I want to create a new Spring Boot project which utilizes the newest Spring Data JPA and Java 21 by creating it in start.spring.io with a settings as below:
![284061929-3c941f05-dbd9-45c2-bcad-94d7567adc79](https://github.com/spring-io/initializr/assets/32438274/2c8db8de-98dd-4a15-ab0a-173dad9df844)
![284061959-b1852fce-90e3-425d-8e18-1df99d6d85f7](https://github.com/spring-io/initializr/assets/32438274/2acf32fd-74c6-4594-9bcf-9fff5ac7055c)
I didn't change anything in the project and, when I'm trying to run it, I have following error:
```
Unsupported Java. 
Your build is currently configured to use Java 21.0.1 and Gradle 8.4.

Possible solution:
 - Use Java 20 as Gradle JVM: Open Gradle settings 
 - Open Gradle wrapper settings, change `distributionUrl` property to use compatible Gradle version and reload the project
```
Remove dependency 'org.springframework.boot:spring-boot-starter-data-jpa' resolves this problem and project compiles and runs. Also after downgrade Java version from 21 to 17 this problem went away.

**Comment by snicoll** [comment]
This, unfortunately, has nothing to do with Spring. Gradle does not yet fully support Java 21 (without the use of toolchain, that is). 

That being said, I did create an app with the same dependencies and Java 21 and building on the command line works, importing the project in IntelliJ IDEA 2023.2.5 works as well. 

I don't really understand why removing Data JPA would change anything here as the error message is unrelated to Spring.

How can I reproduce this?

**Comment by arkadiusz97** [comment]
@snicoll I'm also using IntelliJ IDEA 2023.2.5. I've created repository with unchanged code from start.spring.io https://github.com/arkadiusz97/start-spring-io-issue-1354
I'm sending video, where this problem can be seen and resolved by removing dependency for JPA.
https://github.com/spring-io/start.spring.io/assets/32438274/dfcefc07-f8b6-4797-a230-7c66e180012b

**Comment by snicoll** [comment]
@arkadiusz97 unfortunately, I can't reproduce this. I cloned your project, opened it in IDEA and run the main class and it all worked.

I don't think this issue belongs here, this might be something specific to your IDE configuration. You could perhaps confirm that by running `./gradlew bootRun` in a shell and see it doesn't fail as above.
