### ISSUE TITLE
No Spring Boot 2 options

### ISSUE THREAD

**Issue by Mehdi-HAFID** [spring-io/start.spring.io#1357]
today I saw that options for Boot 2 version are missing. and this post says a new version is out https://spring.io/blog/2023/11/23/spring-boot-2-7-18-available-now but it does not show up in the list
![Screenshot 2023-11-23 143107](https://github.com/spring-io/initializr/assets/25527904/c2eb0f6e-1c62-43e9-8869-9fc61cfc153b)

**Comment by snicoll** [comment]
This is the expected behavior. Spring Boot 2.x is now out of OSS support. The blog post that you've linked is [stating as much](https://spring.io/blog/2023/11/23/spring-boot-2-7-18-available-now#end-of-open-source-support-for-spring-boot-2x). With it being out of support, we've stopped offering that version.

**Comment by shortthirdman** [comment]
@snicoll What if many projects will still need Spring Boot 2.x (x = 6, 7)? How can we generate them? Please suggest a workaround though we all know we can manually provide versions in the `build.gradle` and/or `pom.xml`.

**Comment by mhalbritter** [comment]
Spring Boot 2.6.x and 2.7.x is [out of OSS support](https://spring.io/projects/spring-boot#support). There are commercial support options available.

If you are still using 2.6.x and 2.7.x without a commercial subscription, you'll using an unsupported version of Spring Boot (meaning you won't get bug fixes and security fixed and 3rd party dependency version upgrades). This is not something we want to encourage, therefore we don't show you these options on start.spring.io. If you really really want to do that and take the responsibility for bad stuff that will eventually happen, then create a project with a supported version from start.spring.io and change the version of spring boot in the `pom.xml` or `build.gradle` to 2.6.x or 2.7.x
