### ISSUE TITLE
Use of Kotlin 1.9.20 should not downgrade project to Java 17

### ISSUE THREAD

**Issue by anderius** [spring-io/start.spring.io#1358]
When [I select SB 3.2.0, Java 21 and Kotlin](https://start.spring.io/#!type=gradle-project-kotlin&language=kotlin&platformVersion=3.2.0&packaging=jar&jvmVersion=21&groupId=com.example&artifactId=demo&name=demo&description=Demo%20project%20for%20Spring%20Boot&packageName=com.example.demo), I get a project with Java 17. The HELP.md contains an explanation:

`The JVM level was changed from '21' to '17', review the [JDK Version Range](https://github.com/spring-projects/spring-framework/wiki/Spring-Framework-Versions#jdk-version-range) on the wiki for more details.`

On the linked page, however, I find no explanation for why Java 21 was not selected.

As far as I know, the bundled version of Kotlin, 1.9.20, supports Java 21.

**Comment by snicoll** [comment]
Good catch. That check is overdue and we'll have to adapt it.
