### ISSUE TITLE
Upgrade to Timefold 1.5.0

### ISSUE THREAD

**Issue by zepfred** [spring-io/start.spring.io#1383]
Maven: https://repo1.maven.org/maven2/ai/timefold/solver/timefold-solver-spring-boot-starter/1.5.0/
Compatible Spring Boot version: https://github.com/TimefoldAI/timefold-solver/commits/1.5.x/ and https://github.com/TimefoldAI/timefold-solver/pull/443

**Comment by snicoll** [comment]
> Compatible Spring Boot version

Sorry, I am not sure what I should be looking in the first commit. I can see there was an upgrade to `3.2.0` but that doesn't tell me anything about the previous generation. Is `1.5.0` still compatible with `3.1.x`?

**Comment by zepfred** [comment]
> > Compatible Spring Boot version
> 
> Sorry, I am not sure what I should be looking in the first commit. I can see there was an upgrade to `3.2.0` but that doesn't tell me anything (I could find) about the previous generation. Is `1.5.0` still compatible with `3.1.x`?

Hey @snicoll. Yes, the version `1.5.0` is compatible with Spring-boot `3.1.x`.
