### ISSUE TITLE
Devtools dependency is not flagged optional with Maven

### ISSUE THREAD

**Issue by sathishk** [spring-io/start.spring.io#140]
As per the dev tools documentation at https://docs.spring.io/spring-boot/docs/current/reference/html/using-boot-devtools.html

> Flagging the dependency as optional in Maven or using a custom`developmentOnly` configuration in Gradle (as shown above) is a best practice that prevents devtools from being transitively applied to other modules that use your project.
> --
> 

But when i include dev tools in internalizr we get only 

```
 <dependency>
 			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-devtools</artifactId>
			<scope>runtime</scope>
		</dependency>
```

We need to add 

`<optional>true</optional>`

**Comment by snicoll** [comment]
@sathishk good catch, thank you for reporting it!
