### ISSUE TITLE
Use local storage to remember user choices

### ISSUE THREAD

**Issue by mhalbritter** [spring-io/start.spring.io#1403]
If a user changed e.g. Gradle to Maven last time, there is a high chance that they want it the next time, too. So we should remember the choices for:

- Java (version)
- Project
- Language
- Maybe Spring Boot version?

We could take a look what a IDE remembers.

**Comment by 4121nnn** [comment]
Hi ,

I hope you're doing well!

After reviewing the requirements , I took the initiative to implement this feature.

Here's a summary of what I've done:

Implemented local storage caching for form state in start.spring.io.
Utilized prefixes to avoid key collisions in local storage.
Thoroughly tested the functionality across different scenarios to ensure reliability.
Caching implemented to these fields:
    Project, Language, Spring boot, Packaging and Java version.

I believe that this feature aligns well with the goals of the project and could greatly enhance the user experience. Before proceeding further, I wanted to confirm if you're open to accepting this contribution.

If you agree, I can proceed with opening a pull request. Alternatively, if you have any specific requirements or suggestions, please let me know, and I'll be happy to accommodate them.

Looking forward to your guidance on this matter.

Best regards,
Nurshat

**Comment by 4121nnn** [comment]
Hi mhalbritter,

I hope you're doing well!

After reviewing the requirements , I took the initiative to implement this feature.

Here's a summary of what I've done:

Implemented local storage caching for form state in start.spring.io.
Utilized prefixes to avoid key collisions in local storage.
Thoroughly tested the functionality across different scenarios to ensure reliability.
Caching implemented to these fields:
Project, Language, Spring boot, Packaging and Java version.

I believe that this feature aligns well with the goals of the project and could greatly enhance the user experience. Before proceeding further, I wanted to confirm if you're open to accepting this contribution.

If you agree, I can proceed with opening a pull request. Alternatively, if you have any specific requirements or suggestions, please let me know, and I'll be happy to accommodate them.

Looking forward to your guidance on this matter.

Best regards,
Nurshat

**Comment by mhalbritter** [comment]
Hey @4121nnn, thanks for your initiative. Please open a pull request!

**Comment by mhalbritter** [comment]
Superseded by https://github.com/spring-io/start.spring.io/pull/1459.

**Comment by mhalbritter** [comment]
Superseded by #1462.
