### ISSUE TITLE
Fix broken link to Spring REST Docs reference documentation in help.md

### ISSUE THREAD

**Issue by LuizyHub** [spring-io/start.spring.io#1407]
Hello,

I've noticed that the generated `help.md` file contains a broken link to the `Spring REST Docs` Reference Documentation. The issue seems to stem from an incorrect link suffix in the `application.yml` file.

**Location of the Issue:**
The incorrect link is located in the `application.yml` file, specifically at this URL: [https://github.com/spring-io/start.spring.io/blob/c3d09e30c9bab9fc0310ed6ad552711468871b23/start-site/src/main/resources/application.yml#L1056](https://github.com/spring-io/start.spring.io/blob/c3d09e30c9bab9fc0310ed6ad552711468871b23/start-site/src/main/resources/application.yml#L1056)

**Suggested Fix:**
The current suffix in the URL is `html5`, which leads to a non-functional link. Changing the suffix from `html5` to `htmlsingle` should resolve the issue and direct users to the correct `Spring REST Docs` Reference Documentation.

**Impact:**
This broken link may hinder users from accessing valuable documentation for `Spring REST Docs`, potentially affecting their development experience.

I believe this is a straightforward fix and would like to contribute by resolving this issue. Please let me know if I can be assigned to this issue to work on the correction. I appreciate your consideration and look forward to contributing to the start.spring.io project.

Thank you!

**Comment by mhalbritter** [comment]
Hey @LuizyHub, thanks for that issue. I should have read through the whole issue instead of quickly fixing it and pushing the fix. Sorry about that, I'll revert it and let you have a go on the fix!

**Comment by LuizyHub** [comment]
@mhalbritter Thanks to giving me chance to contribute!
here is my pull request
https://github.com/spring-io/start.spring.io/pull/1409

**Comment by mhalbritter** [comment]
Superseded by #1409.
