### ISSUE TITLE
Display generated build file (pom.xml / gradle.build)

### ISSUE THREAD

**Issue by qwertukg** [spring-io/start.spring.io#141]
It will be good if u will provide an ability to download only pom.xml (or just render it) without generating all files

**Comment by justin-wesley** [comment]
@snicoll Since the **Explore the Project** feature has been implemented, should this issue be closed? I love the **Explore the Project** feature by the way.

**Comment by wilkinsona** [comment]
Yes, I think it should. Thanks. Closing in favour of https://github.com/spring-io/start.spring.io/pull/160.
