### ISSUE TITLE
When Flyway and a JDBC driver are selected, automatically add the corresponding flyway-database-* dependency

### ISSUE THREAD

**Issue by wilkinsona** [spring-io/start.spring.io#1434]
Flyway 10 is more modular and has split database-specific code out into a number of separate modules. When a version of Spring Boot that uses Flyway 10 is selected, we should add the flyway-database-* module that matches the JDBC driver that's been chosen.

**Comment by wilkinsona** [comment]
Boot 3.3.0-SNAPSHOT is now using Flyway 10.10.

**Comment by mhalbritter** [comment]
There's:

- flyway-database-db2
- flyway-database-derby
- flyway-database-hsqldb
- flyway-database-informix
- flyway-database-mongodb
- flyway-database-oracle
- flyway-database-postgresql
- flyway-database-redshift
- flyway-database-saphana
- flyway-database-snowflake
- flyway-database-sybasease
