### ISSUE TITLE
Combination OpenAI + Spring Reactive Web just doesn't run

### ISSUE THREAD

**Issue by dims12** [spring-io/start.spring.io#1439]
Choose 2 specified dependencies and run an application from scratch. It will fail with

Parameter 2 of method openAiChatClient in org.springframework.ai.autoconfigure.openai.OpenAiAutoConfiguration required a bean of type 'org.springframework.web.client.RestClient$Builder' that could not be found.

**Comment by wilkinsona** [comment]
Please report this to the [Spring AI project](https://github.com/spring-projects/spring-ai). The `openAiChatClient` bean should back off in the absence of a `RestClient.Builder`.
