### ISSUE TITLE
Upgrade to Solace Spring Cloud 4.0.0

### ISSUE THREAD

**Issue by mayur-solace** [spring-io/start.spring.io#1446]
- Upgrade to solace-spring-cloud [v4.0.0](https://github.com/SolaceProducts/solace-spring-cloud/releases/tag/4.0.0) when including Cloud Stream & Solace.

FYI @snicoll. Thanks in advance.

**Comment by snicoll** [comment]
@mayur-solace thanks and congrats on the release, but there's no need to mention me. The team already received a notification when you created the issue.
