### ISSUE TITLE
Support for Axon Framework

### ISSUE THREAD

**Issue by OLibutzki** [spring-io/start.spring.io#1468]
[Axon Framework](https://github.com/AxonFramework/AxonFramework) is a mature library which supports Spring Boot by providing auto-configurations, see [Spring Boot Integration](https://docs.axoniq.io/reference-guide/axon-framework/spring-boot-integration).

It would be great if Spring Initializr natively supported setting up an Axon Spring Boot project.

**Comment by wilkinsona** [comment]
If you would like us to consider adding Axon to https://start.spring.io, please encourage the project's maintainers to open a [new entry proposal](https://github.com/spring-io/start.spring.io/issues/new?assignees=&labels=type%3A+entry-proposal&projects=&template=add-entry-proposal.md).
