### ISSUE TITLE
Add Docker Compose support for Spring AI vector DBs

### ISSUE THREAD

**Issue by mhalbritter** [spring-io/start.spring.io#1481]
See https://github.com/spring-projects/spring-ai/commit/9c1b1b84ee4f75c54621c1d29d3b5de33f1af226

**Comment by eddumelendez** [comment]
Hi @mhalbritter, I already have a branch for this. Will share it later today

**Comment by mhalbritter** [comment]
Superseded by https://github.com/spring-io/start.spring.io/pull/1484.
