### ISSUE TITLE
Could Not Resolve Dependencies (Tag Mismatch Error)

### ISSUE THREAD

**Issue by Praval791** [spring-io/start.spring.io#1485]
When attempting to build the demo project, the build fails due to unresolved dependencies. The specific error message is as follows:
```bash
[ERROR] Failed to execute goal on project demo: Could not resolve dependencies for project com.example:demo:jar:0.0.1-SNAPSHOT: The following artifacts could not be resolved: org.apache.tomcat.embed:tomcat-embed-core:jar:10.1.24, net.bytebuddy:byte-buddy:jar:1.14.16: Could not transfer artifact org.apache.tomcat.embed:tomcat-embed-core:jar:10.1.24 from/to central (https://repo.maven.apache.org/maven2): GET request of: org/apache/tomcat/embed/tomcat-embed-core/10.1.24/tomcat-embed-core-10.1.24.jar from central failed: Tag mismatch -> [Help 1]
```

**Steps to Reproduce:**

- Download the project from [start.spring.io](https://start.spring.io/) with the following settings:
![image](https://github.com/spring-io/start.spring.io/assets/94207665/a40fe86e-4bfb-4478-a33f-5589956e5ec7)
- Extract the downloaded zip file.
- Navigate to the project directory.
- Run the build command (e.g., mvn clean package).

**Expected Result:**

The project should build successfully without any dependency resolution errors.

**Actual Result:**

The build fails with an error indicating that certain artifacts could not be resolved due to a tag mismatch when attempting to transfer from the central repository.

**Environment:**

Maven Version: 3.8.7
Java Version: 17.0.2
Operating System: windows

**Comment by mhalbritter** [comment]
I've just tested it and it works fine on my machine. Might be a problem with your environment. Can you download https://repo.maven.apache.org/maven2/org/apache/tomcat/embed/tomcat-embed-core/10.1.24/tomcat-embed-core-10.1.24.jar directly?

**Comment by Praval791** [comment]
@mhalbritter Yeah! The same thing is working on my other devices. Later I found out that the problem was with my proxy, I have removed that and now it is working as it should be.

**Comment by wilkinsona** [comment]
Thanks for letting us know.
