### ISSUE TITLE
Spring Cloud Dependency management plugin is not being set up for the Spring Cloud Tools group

### ISSUE THREAD

**Issue by OlgaMaciaszek** [spring-io/start.spring.io#149]
The build files are not set up correctly as the Spring Cloud bom is missing in Spring Cloud Tools group's configuration.

**Comment by wilkinsona** [comment]
Thanks, @OlgaMaciaszek. If you intend to open a pull request there's no need for an issue as well.

**Comment by OlgaMaciaszek** [comment]
Ah, ok. Thanks for the info.
