### ISSUE TITLE
Vaadin production profile includes vaadin-dev dependency

### ISSUE THREAD

**Issue by ZheSun88** [spring-io/start.spring.io#1492]
Hi, 

the generated vaadin project has an incomplete production file, which should be updated. 

the missing part is an `vaadin-core` dependency with `vaadin-dev` exclusion

one example profile can be see from [here](https://github.com/vaadin/skeleton-starter-flow-spring/blob/v24.4/pom.xml#L119...L150)

I can see the configuration is probably from [here](https://github.com/spring-io/start.spring.io/blob/main/start-site/src/main/java/io/spring/start/site/extension/dependency/vaadin/VaadinMavenBuildCustomizer.java#L30C2-L37C99), but this seems only managing the plugin tag instead of the dependency part.

can you help us to do that or point me how? 

Thanks.

**Comment by mhalbritter** [comment]
The profile generated now looks like this:

```xml
	<profiles>
		<profile>
			<id>production</id>
			<dependencies>
				<dependency>
					<groupId>com.vaadin</groupId>
					<artifactId>vaadin-core</artifactId>
					<exclusions>
						<exclusion>
							<groupId>com.vaadin</groupId>
							<artifactId>vaadin-dev</artifactId>
						</exclusion>
					</exclusions>
				</dependency>

			</dependencies>
			<build>
				<plugins>
					<plugin>
						<groupId>com.vaadin</groupId>
						<artifactId>vaadin-maven-plugin</artifactId>
						<version>${vaadin.version}</version>
						<executions>
							<execution>
								<id>frontend</id>
								<phase>compile</phase>
								<goals>
									<goal>prepare-frontend</goal>
									<goal>build-frontend</goal>
								</goals>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>
```

Is that fine? It executes the goals `prepare-frontend` and `build-frontend`, while your examples only have `build-frontend`.

**Comment by ZheSun88** [comment]
yeah, that seems fine. thanks a lot for the help.
