### ISSUE TITLE
Add option to generate gradle multimodule project

### ISSUE THREAD

**Issue by matthewadams** [spring-io/start.spring.io#1500]
This is a feature request to add an option to the generator underlying start.spring.io to produce a gradle multimodule project, containing a Spring Boot app and a library project that the Spring Boot app depends on.

We started with the project configuration produced by start.spring.io, which has a single Spring Boot project in the root.  Over time, we've spun out several libraries that our Spring Boot app depends on, and we did this into separate git repositories.  When we wanted to move to a monorepo, we had a lot of work to do to convert the project to a gradle multimodule project, where the root housed directories for our Spring Boot project and our library projects.  We now have a multimodule gradle project that includes not one, but two Spring Boot apps and many library jars, but we're still not sure we've employed gradle best practices with it.

It would be nicer if start.spring.io offered an option where it could produce a gradle multimodule project containing a root directory with subdirectories that contain the Spring Boot project and a second that contains a library project that the Spring Boot app depends on.  Then, as more libraries are needed, devs could use the existing library project as a template to copy & paste.

The generated project should employ all gradle best practices for multimodule projects, and support gradle groovy or gradle kotlin.

**Comment by wilkinsona** [comment]
Duplicates https://github.com/spring-io/initializr/issues/663.
