### ISSUE TITLE
Add option to include ProGuard code obfuscation to generated project

### ISSUE THREAD

**Issue by matthewadams** [spring-io/start.spring.io#1501]
This is a feature request to add a dependency (in the `Dependencies` list on the right side of start.spring.io) that adds ProGuard-based code obfuscation to the project.

As the pendulum swings from cloud back to on-premise due to the rise of edge computing, we are seeing the need to deploy our applications at a customer's site, and in some cases, we need to protect our intellectual property through code obfuscation.  The overwhelming choice for obfuscation of Java projects today appears to be [ProGuard](https://www.guardsquare.com/proguard) (GitHub project [here](https://github.com/Guardsquare/proguard)).  They even have a [Spring Boot example](https://github.com/Guardsquare/proguard/tree/master/examples/spring-boot), but it's somewhat out of date.

Please enhance start.spring.io to allow a user to add a dependency on ProGuard for code obfuscation, which would be correctly configured out of the box.

**Comment by mhalbritter** [comment]
Hello,

thanks for the proposal. We thought about that, and given the huge number of configuration options and the fact that ProGuard is not a spring-specific technology nor has explicit support for Spring, we decided to not add ProGuard on start.spring.io.

**Comment by matthewadams** [comment]
I totally understand.  Could you instead consider this a request for an authoritative article/blogpost/document jointly authored by spring & proguard folks on best obfuscation practices for spring boot applications?  We spent a lot of time on obfuscating our spring boot apps, and  it works, but we're still not sure we got it quite right.  We might be able to share our experiences with the article authors and help everyone out in the process.  WDTY?

**Comment by wilkinsona** [comment]
I don't know anything about Proguard or best practices for obfuscation. As far as I know, the same goes for the rest of the team. As such, I don't think we'd be adding anything by jointly authoring something. While the Proguard example is using Spring Boot 2.3, the layout of Spring Boot's uber jar hasn't changed since then so it should still be relevant.
