### ISSUE TITLE
Drop dev.hilla/hilla entry 

### ISSUE THREAD

**Issue by ZheSun88** [spring-io/start.spring.io#1505]
Hi, 
Since Vaadin 24.4 (going to be announced on Wednesday 12th June EEST), Vaadin becomes a Unified platform for the original vaadin and hilla (TypeScript frontend) products. 
so separate hilla entry is not needed any more.

in this case, we would like to drop the entry for hilla dependencies from https://start.spring.io/

**Comment by mhalbritter** [comment]
Superseded by #1507.
