### ISSUE TITLE
Cursor pointer is not displayed for theme switcher in mobile view

### ISSUE THREAD

**Issue by sanajitjana** [spring-io/start.spring.io#1510]
When switching between dark and light themes on the mobile header of the start.spring.io website, the theme change icon does not display a cursor pointer. This can be confusing for users as it does not indicate that the icon is clickable.

Proposed Solution:
Add CSS to ensure the cursor changes to a pointer when hovering over the theme change icon on mobile header.

I have already implemented the code for this enhancement and would like to open a Pull Request. Can I proceed with submitting a PR for this issue?

Thank you for considering my contribution.

**Comment by mhalbritter** [comment]
Hello,

yes, please submit a PR. Thanks!

**Comment by mhalbritter** [comment]
Superseded by #1512.
