### ISSUE TITLE
Upgrade to Solace Spring Cloud 4.1.0

### ISSUE THREAD

**Issue by Nephery** [spring-io/start.spring.io#1513]
Upgrade to [Solace Spring Cloud 4.1.0](https://github.com/SolaceProducts/solace-spring-cloud/releases/tag/4.1.0) when including Cloud Stream & Solace.
* Although the docs says that [Solace Spring Cloud 4.1.0 was built against Spring Boot 3.2.x and Spring Cloud 2023.0.1](https://github.com/SolaceProducts/solace-spring-cloud/tree/master/solace-spring-cloud-bom#spring-cloud-version-compatibility), as per the following test automation, we confirmed that this release will also work for Spring Boot 3.3.0 and Spring Cloud 2024.0.2:
  * https://github.com/SolaceProducts/solace-spring-cloud/pull/291

**Comment by mhalbritter** [comment]
Hello,

in the merged PR, there's a comment:

```
<!-- Remove this if the next version of solace-spring-boot works fine -->
```

So `solace-spring-cloud-bom` has been tested against 3.3.x, what about `solace-spring-boot-bom`? Can I mark this as 3.3.x ready, too?

**Comment by Nephery** [comment]
Ah, yeah. `solace-spring-boot-bom` is also compatible with Spring Boot 3.3.x since the automation here is passing: https://github.com/SolaceProducts/solace-spring-boot/pull/123
