### ISSUE TITLE
Move JacksonKotlinBuildCustomizer to the library

### ISSUE THREAD

**Issue by mbhave** [spring-io/start.spring.io#152]
Like `web` and `jpa`, the `json` facet is a core feature. The `KotlinJpaMavenBuildCustomizer` is [in the library](https://github.com/spring-io/initializr/blob/43b1148f64ee15ff83ce7dea930bf6638c365606/initializr-generator-spring/src/main/java/io/spring/initializr/generator/spring/code/kotlin/KotlinJpaMavenBuildCustomizer.java) and seems like this one should move too.

**Comment by snicoll** [comment]
As I've shared already, the line is usually draw is whether the code is declaring a dependency with maven coordinates. If they do, I believe the code should stick closer to the metadata that declares them. 

In the case of this customizer, we don't declare the jackson dependency at all so it's not a clear cut. Having said that, I'd be slightly more in favour of moving it.
