### ISSUE TITLE
History dialog body background does not adapt to dark theme

### ISSUE THREAD

**Issue by sanajitjana** [spring-io/start.spring.io#1521]
When switching the theme to dark mode on start.spring.io, the history dialog has an issue where its body background remains white, causing it to blend in with the text color and making it unreadable.

Steps to Reproduce:

1. Go to start.spring.io.
2. Switch to dark mode.
3. Click on the history button/icon to open the history dialog.

Expected Behavior:

The entire history dialog (header, body, list headings, etc.) should adapt to the dark theme, ensuring that all components are clearly visible and readable.

Actual Behavior:

- The dialog header, list headings, and more adapt correctly to the dark theme.
- However, the dialog body background remains white, causing the text to blend with the background, making it hard to read.

Screenshots:
![image](https://github.com/spring-io/start.spring.io/assets/76105799/83445527-1308-4cc8-8a5b-0c90e549fefc)

Additional Information:

Browser: Google Chrome
Operating system: Windows 11

Proposed Solution:

Ensure that the history dialog's body background color is adjusted to match the dark theme, ensuring readability and usability when the site is in dark mode.

PR Intent: I plan to create a Pull Request (PR) to fix the history dialog's body background not adapting to the dark theme on start.spring.io, improving usability in dark mode.

**Comment by mhalbritter** [comment]
> I plan to create a Pull Request (PR) to fix the history dialog's body background not adapting to the dark theme on start.spring.io, improving usability in dark mode.

Cool, thanks!

**Comment by mhalbritter** [comment]
Superseded by https://github.com/spring-io/start.spring.io/pull/1522.
