### ISSUE TITLE
HELP.md contains broken links to the Maven and Gradle plugin reference docs

### ISSUE THREAD

**Issue by victorgawk** [spring-io/start.spring.io#1529]
When generating code from [Spring initializr](https://start.spring.io/) using project `Gradle - Groovy`, language `Java`  and version `3.3.1`, inside `HELP.md` file there is two invalid URLs resulting in `404 Not Found` error:

- https://docs.spring.io/spring-boot/docs/3.3.1/gradle-plugin/reference/html/
- https://docs.spring.io/spring-boot/docs/3.3.1/gradle-plugin/reference/html/#build-image

Error when opening these links in Google Chrome:
![image](https://github.com/spring-projects/spring-boot/assets/6736720/8eab9cb4-05c7-4883-964d-40a2abab638b)

Code generation example:
https://start.spring.io/#!type=gradle-project&language=java&platformVersion=3.3.1&packaging=jar&jvmVersion=21&groupId=com.example&artifactId=demo&name=demo&description=Demo%20project%20for%20Spring%20Boot&packageName=com.example.demo&dependencies=

**Comment by wilkinsona** [comment]
There's a similar problem with Maven builds where the `HELP.md` contains the following links:

- https://docs.spring.io/spring-boot/docs/3.3.1/maven-plugin/reference/htmlsingle/
- https://docs.spring.io/spring-boot/docs/3.3.1/maven-plugin/reference/htmlsingle/#build-image

**Comment by rishiraj88** [comment]
@wilkinsona , @victorgawk ,

3 days back I cloned the spring-boot repo to my Windows workstation, but some filenames (filepaths) were too long for the OS to handle and clone those files.

I will try to clone relevant repositories with my Ubuntu VM this Friday evening.

Let's see if the main issue may be resolved quickly.

However, this was my observation over the issue at high level:
[Updated link for Gradle plugin documentation notes is this.](https://github.com/spring-projects/spring-boot/issues/41338#issuecomment-2213146498)

**Comment by wilkinsona** [comment]
@rishiraj88 this issue doesn't require changes to Spring Boot. It should be fixed by making changes in this repository. That said, in case you need to clone the Spring Boot repo in the future, please see https://github.com/spring-projects/spring-boot/wiki/Working-with-the-Code#cloning-the-git-repository-on-windows.

**Comment by philwebb** [comment]
The correct URLs are https://docs.spring.io/spring-boot/maven-plugin/index.html and https://docs.spring.io/spring-boot/gradle-plugin/index.html. We should fix the redirects.

**Comment by mhalbritter** [comment]
Superseded by https://github.com/spring-io/start.spring.io/pull/1541.
