### ISSUE TITLE
Inconsistent Display of Remove Dependency Button on Spring Initializr

### ISSUE THREAD

**Issue by br-lovanshi** [spring-io/start.spring.io#1540]
# Actual Behavior
When a user adds dependencies on the Spring Initializr and hovers over any dependency, the remove button (a red '-' symbol) appears for all dependencies. This creates a cluttered and odd appearance because only one dependency can be removed at a time.

## Expected Behavior
The remove dependency button should only be visible for the specific dependency being hovered over, not for all dependencies.

## Steps to Reproduce
1. Go to [Spring Initializr](https://start.spring.io/).
2. Add several dependencies to the project.
3. Hover over one of the dependencies.

Observe that the remove button appears for all dependencies instead of just the one being hovered over.

![image](https://github.com/user-attachments/assets/4cfb2cec-3e9e-4f56-81eb-3998c65446fc)

**Comment by wilkinsona** [comment]
You've described this as a bug, but I don't think it is. It's really a matter of opinion and personal preference. I can see the argument that it's cluttered, but I think there's also a counter argument that the current behavior makes it easier to discover how to remove a dependency. Let's see what the rest of the time thinks, in particular @oodamien.

**Comment by oodamien** [comment]
Hi,
It was a choice to show all the actions when hovering the right column, makes it easier to discover how to remove a dep.

**Comment by wilkinsona** [comment]
Thanks for the suggestion, @br-lovanshi, but we prefer the UI as it is.
