### ISSUE TITLE
Set Vaadin's launch-browser property automatically

### ISSUE THREAD

**Issue by ZheSun88** [spring-io/start.spring.io#1552]
Hi, 

Is is possible that we add a `application.properties` file into the generated project using vaadin dependency? 

if so, the content inside should be 

```
vaadin.launch-browser=true
```

Thanks

**Comment by mhalbritter** [comment]
Here's the documentation for that feature: https://vaadin.com/docs/latest/flow/integrations/spring/configuration#launch-browser-in-development-mode
