### ISSUE TITLE
Support org.testcontainers.kafka.KafkaContainer to generate test app

### ISSUE THREAD

**Issue by eddumelendez** [spring-io/start.spring.io#1596]
`org.testcontainers.kafka.KafkaContainer` supports [apache/kafka-native](https://hub.docker.com/r/apache/kafka-native) image, which is faster. And `org.testcontainers.kafka.KafkaContainer` is supported as part of Spring Boot 3.4.0.

My proposal is to generate test apps using `org.testcontainers.kafka.KafkaContainer` starting with Spring Boot 3.4.0-M1. For previous version keep providing `org.testcontainers.containers.KafkaContainer`.

I can contribute to it.

**Comment by mhalbritter** [comment]
Hey @eddumelendez, thanks for that idea. I'd be happy if you can contribute a PR :)

**Comment by mhalbritter** [comment]
Superseded by #1597.
