### ISSUE TITLE
The server API is not available.

### ISSUE THREAD

**Issue by thilinaucsc** [spring-io/start.spring.io#161]
![image](https://user-images.githubusercontent.com/17719452/59896479-6f53fa80-9406-11e9-9054-ba4e77c5486d.png)

**Comment by snicoll** [comment]
@thilinaucsc  thanks for reporting but this looks like a temporary (network?) glitch to me as I can't reproduce. Are you having this consistently and can you provide more details than a screenshot?

**Comment by thilinaucsc** [comment]
Now, this is working fine.
