### ISSUE TITLE
Filename of the zip file is different when unzipped

### ISSUE THREAD

**Issue by htztomic** [spring-io/start.spring.io#163]
The filename of the zip is produced by the artifactId but when the artifactId is invalid and gets sanitized by initializr-web, the base directory name is then changed to follow that convention. When the file is finally saved from the client side, the name isn't updated and therefore results in a zip file that has a different name when unzipped.

**Comment by snicoll** [comment]
@htztomic can you please provide an `artifactId` sample where that happens? It is likely to be a bug in the library but I'd like to reproduce the problem you've described before moving this issue to the `initializr`repo.

**Comment by htztomic** [comment]
@snicoll One example would be `demo trial` as an `artifactId`, it generates a project called `demo trial.zip` but the root file when unzipped is `demo-trial` which is the sanitized name.

**Comment by snicoll** [comment]
Thanks for the feedback. I agree that consistency between the file name and the `artifactId` is a good thing.

**Comment by snicoll** [comment]
superseded by https://github.com/spring-io/initializr/pull/1492
