### ISSUE TITLE
Generate starter project into the developer's repository

### ISSUE THREAD

**Issue by Marcjazz** [spring-io/start.spring.io#1692]
Spring Initializr should offer the possibility to connect to the developer's account, create and initialize the repository from the [start.sping.io](https://start.spring.io/) UI.

**Comment by snicoll** [comment]
I suppose you mean create a repository from GitHub? Please clarify.

**Comment by Marcjazz** [comment]
Yes,I'm suggesting to give developers the possibility to checkout the generated source code in a new GitHub repository instead of always downloading the compressed file.

**Comment by snicoll** [comment]
Thanks. That's a duplicate of https://github.com/spring-io/initializr/issues/751
