### ISSUE TITLE
Override outdated Spring Kafka version with Spring Boot 1.5.x

### ISSUE THREAD

**Issue by garyrussell** [spring-io/start.spring.io#17]
Spring Boot 1.5.x pulls in spring-kafka 1.1.x which is no longer supported; the preferred version for Boot 1.5.x is spring-kafka 1.3.x (currently 1.3.8).

See [the project page](https://spring.io/projects/spring-kafka).

It would be preferable if initializr could override the version rather than each user having to do it manually.

**Comment by snicoll** [comment]
Thanks for letting us know @garyrussell. The version is now overridden when using Spring Boot 1.x.
