### ISSUE TITLE
Add support for Apache Geode

### ISSUE THREAD

**Issue by jxblum** [spring-io/start.spring.io#176]
Please add support for _Spring Boot for Apache Geode_ (SBDG), version `1.1.0.M3` to the _Initializer_.

**Name**: _Spring Boot for Apache Geode_ 

> NOTE: open to suggestions if this name present a problem.

**Description**: "_Apache Geode is a data management platform that helps users build real-time, highly concurrent, highly performant and reliable Spring Boot applications at scale._"

_Request Details_:

1. **Code of Conduct**

SBDG follows the same "_Code of Conduct_" that all Spring projects follow:

https://github.com/spring-projects/spring-boot-data-geode#code-of-conduct

2. **Established Project & Vibrant Community**

Sent details in email on Apache Geode privately.

The SBDG project can be found on [GitHub](https://github.com/spring-projects/spring-boot-data-geode).  

Currently: **15 Watchers**, **14 Stars**, **19 Forks**, **5 live contributors**... in ~2 years since the project's [inception](https://github.com/spring-projects/spring-boot-data-geode/commits/master?after=7dc26510400a1d62df8df4c4ce5ee115ec83ccc0+594).  I say approximately because I did not start actively working on the project until ~May/June 2018.  Since that time, I have made good progress.

Most _StackOverflow_ activity (AFAIK) occurs with the [#spring-data-gemfire tag](https://stackoverflow.com/questions/tagged/spring-data-gemfire).

The project is used extensively, internally @ Pivotal, especially with new PCF/PCC customers, but even within Apache Geode community looking to evaluate the technology in a Spring context.

3. **Ongoing Maintenance**

SBDG has **11 releases**: https://github.com/spring-projects/spring-boot-data-geode/releases

We closed **27 Issues** (only **4 Issues** open): https://github.com/spring-projects/spring-boot-data-geode/issues

We closed **9 PRs** (**0 PRs** open): https://github.com/spring-projects/spring-boot-data-geode/pulls

SBDG currently has **598 quality commits**: https://github.com/spring-projects/spring-boot-data-geode/commits/master

4. **License**

SBDG uses the [Apache 2 License](https://github.com/spring-projects/spring-boot-data-geode#license) and [here](https://github.com/spring-projects/spring-boot-data-geode/blob/master/LICENSE).

5. **Issue Tracker URL**

https://github.com/spring-projects/spring-boot-data-geode/issues

6. **Continuous Integration**

SBDG uses both [Travis CI](https://travis-ci.org/spring-projects/spring-boot-data-geode) and [Jenkins](https://jenkins.spring.io/job/spring-boot-data-geode/).

7. **Maven Central**

SBDG `1.0.1.RELEASE` is in Maven Central, [here](https://search.maven.org/search?q=spring-geode-starter).

SBDG `1.1.0.M3` is available in [repo.spring.io](https://repo.spring.io/libs-milestone/org/springframework/geode/spring-geode-starter/).

8. **Configuration metadata**

SBDG does support `@ConfigurationProperties`.

[Documentation](https://docs.spring.io/spring-boot-data-geode-build/current/reference/html5/#geode-configuration) for _configuration metadata_.

Technical bits for _configuration metadata_: [here](https://github.com/spring-projects/spring-boot-data-geode/tree/master/spring-geode-autoconfigure/src/main/java/org/springframework/geode/boot/autoconfigure/configuration) & [here](https://github.com/spring-projects/spring-boot-data-geode/blob/master/spring-geode-autoconfigure/src/main/resources/META-INF/additional-spring-configuration-metadata.json).

9. **Version mappings**

This [Wiki page](https://github.com/spring-projects/spring-boot-data-geode/wiki/Spring-Boot-for-Apache-Geode-and-Pivotal-GemFire-Version-Compatibility-Matrix) might explain this best.

_In a nutshell_:

SBDG `1.0.x` is based on [Spring Boot 2.0.x](https://github.com/spring-projects/spring-boot-data-geode/blob/1.0.x/gradle.properties#L8).
SBDG 1.1.x is based on [Spring Boot 2.1.x](https://github.com/spring-projects/spring-boot-data-geode/blob/master/gradle.properties#L8).
SBDG 1.2.x is (will be) based on [Spring Boot 2.2.x](https://github.com/jxblum/spring-boot-data-geode/blob/1.2.x/gradle.properties#L8).

I am moving quickly to a SBDG `1.1 GA` so that I can base SBDG `master` on Spring Boot `2.2.x`, at which point, I will be aligned with Spring Boots development/release cycle.  See the SBDG [Milestones](https://github.com/spring-projects/spring-boot-data-geode/milestones) and  [Spring Release Calendar](https://spring-calendar.cfapps.io/) for the (tentative) schedule of releases.

10. **Links to additional resources**

Documentation: https://github.com/spring-projects/spring-boot-data-geode#documentation
Samples: https://docs.spring.io/spring-boot-data-geode-build/1.1.x/reference/html5/#geode-samples
Apache Geode Website: https://geode.apache.org/
Pivotal Cloud Cache: https://pivotal.io/pivotal-cloud-cache
Switching from Apache Geode (open source) to Pivotal Cloud Cache (commercial): https://docs.spring.io/spring-boot-data-geode-build/1.1.x/reference/html5/#geode-gemfire-switch

[SBDG Starter](https://github.com/spring-projects/spring-boot-data-geode/tree/master/spring-geode-starter-session) for Spring Session when using Apache Geode: https://github.com/spring-projects/spring-session-data-geode

[SBDG Starter](https://github.com/spring-projects/spring-boot-data-geode/tree/master/spring-geode-starter-test) for SDG Test: https://github.com/spring-projects/spring-test-data-geode

Let me know if there are any questions or you need additional information.

Thank you.

**Comment by snicoll** [comment]
Thanks for the proposal and providing the information that we need. I've been looking at the experience using the starter, especially in combinations with other starters and I've faced an issue that surfaces in Apache Geode itself.

Geode has a hard-dependency on Log4j at the moment, which means that we can't use the regular Slf4j bridge to route log to our default implementation (Logback). The team is ready to go the extra mile to add support here by swapping the logging system for the application to log4j2 when Geode is selected. While this is highly unusual, we understand that the team would like to get rid of this hard dependency, which means we can ultimately remove that special case.

Unfortunately, swapping the logging system to log4j2 also removes our default log format, see https://github.com/spring-projects/spring-boot-data-geode/issues/42 (which has a link to an issue to Apache Geode itself). We're not really sure how to proceed with this one.

**Comment by jxblum** [comment]
I am not sure where we stand on this request?

I think we have gone as far as we can with the logging issues caused by Apache Geode in SBDG [Issue #42 ](**url**).  The Apache Geode team is putting together changes to logging that will makes it way into Apache Geode `1.10`, as well as a patch release to Apache Geode `1.9` (should be `1.9.1`).

However, SBDG `1.1` is based on Spring Boot `2.1` and Spring Data (Geode) **Lovelace**/`2.1`, where SDG **Lovelace**/`2.1` is based on Apache Geode 1.6, which cannot change, in order to have proper alignment.  In addition, SBDG `1.1` is already at release candidates.

SBDG `1.2` will be based on Spring Boot `2.2` and Spring Data (Geode) **Moore**/`2.2`, which is based on Apache Geode `1.9`.  Therefore, SDG **Moore**/`2.2` release will be able to pick up subsequent versions of Apache Geode, containing the Log4j fixes.

I have already done what I can on the SBDG `1.1` development branch, `master` ([for example](https://github.com/spring-projects/spring-boot-data-geode/blob/master/spring-geode-starter/spring-geode-starter.gradle#L9)).  It is not possible with Apache Geode `1.6`, to exclude the `org.apache.logging.log4j:log4j-core` dependency from the Apache Geode transitive dependencies.

Additionally, I have already prepared an SBDG `1.2` [branch](https://github.com/jxblum/spring-boot-data-geode/tree/1.2.x) in my personal _GitHub_ repo, so that when I pull the release trigger on SBDG `1.1 GA`, tentatively [scheduled](https://github.com/spring-projects/spring-boot-data-geode/milestone/14) for next *Wednesday, August 14th*, I can follow that up with a SBDG `1.2 M1` release, which essentially aligns SBDG `1.2` on Spring Boot `2.2` with Spring Data (Geode) **Moore**/`2.2` with Apache Geode `1.9`.  I have also properly [removed](https://github.com/jxblum/spring-boot-data-geode/blob/1.2.x/spring-geode/spring-geode.gradle#L17) the Log4j core dependency from SBDG, so that the Log4j impl does not interfere with Spring Boot logging, as much as is possible.

Anyway, let me know how I can help move this request forward.  I think I am doing everything on my end, but if that is not the case, please let me know.

With the [EOL](https://spring.io/blog/2019/08/06/it-is-time-goodbye-spring-boot-1-x) of Spring Boot `1.5.x`, Spring Initializer now sits without any support for either Pivotal GemFire (understood) or Apache Geode.

Thank you!

**Comment by snicoll** [comment]
> I am not sure where we stand on this request?

I think the most accurate information is available in the issue you've referenced (https://github.com/spring-projects/spring-boot-data-geode/issues/42). I think I am also doing everything on my end, testing the developer experience with Spring Boot and providing feedback to the Geode team. Once we are in a situation where the logging infrastructure is not overridden by `geode-core` we can move things forward here. Given the geode team offered to backport the necessary changes, I am hopeful we can get resolution in the coming weeks.

**Comment by jxblum** [comment]
Please keep in mind that SBDG `1.1` will still be (indirectly) based on Apache Geode `1.6`, which will not solve the logging issues, at least not in the way we expect (i.e. we need to exclude the `org.apache.logging.log4j:log4j-to-slf4j` dependency).

SBDG `1.2`, which will be (indirectly) based on Apache Geode `1.9`, will still require us to exclude the `org.apache.logging:log4j:log4j-core` dependency.

The Apache Geode team is backing porting a few changes that will 1) Avoid the `ClassCastException` (when using the bridge) and 2) make the `log4j-core` dependency "optional".

It will not be until Apache Geode `1.11` that the Log4j dependency in Apache Geode will be broken out into a separate module (e.g. `geode-logging`).  Apache Geode has already cut their `1.10` branch and starting their voting process on `1.10`, so the logging modularization won't happen until `1.11`.  This also means it will be Spring Data **Neuman**/`2.3`, Spring Boot `2.3` ad SBDG `1.3` that picks up Apache Geode `1.11` since SD **Moore**/`2.2` is already fixed on Apache Geode `1.9`.

**Comment by jxblum** [comment]
I only ask where this stands because we are now without any coverage on either Apache Geode or Pivotal GemFire (understandable), which is a stepping stone for users migrating  Pivotal CloudCache.

I cannot even select the Spring Data module for Apache Geode. :(

**Comment by snicoll** [comment]
I've indicated [in my previous comment](https://github.com/spring-io/start.spring.io/issues/176#issuecomment-519806893) that this issue is waiting for a resolution of https://github.com/spring-projects/spring-boot-data-geode/issues/42. I've just added the `status: blocked` label to make that more explicit.

**Comment by snicoll** [comment]
An  update, the issue has been resolved, it would be nice (even though not totally mandatory) to get a milestone before adding the entry. 

@jxblum can you please share when you expect to release the next milestone?

**Comment by snicoll** [comment]
I went ahead and added the proposal with `1.2.0-SNAPSHOT` for now. We'll move to `1.2.0.M2` as soon as it's out.
