### ISSUE TITLE
Shortcut button for exploring the project is misleading

### ISSUE THREAD

**Issue by mulderbaba** [spring-io/start.spring.io#178]
by default command + space on mac opens up the spotlight input box and currently the explore button has the shortcut depicted on the UI as command + space. It would make more sense to have it as control + space.

**Comment by oodamien** [comment]
Hi @ mulderbaba, thanks for the feedback.
We will revisit the shortcuts.

**MAC OS:**
Cmd+Enter: Download
Ctrl+Space: Explore

**Windows:**
Ctrl+Enter: Download
Ctrl+Space: Explore

**Comment by snicoll** [comment]
Closing in favour of PR #179
