### ISSUE TITLE
Option to exclude Maven/Gradle wrappers

### ISSUE THREAD

**Issue by justin-wesley** [spring-io/start.spring.io#181]
I'm not sure how many people are like me who just delete the script and wrapper directory after they download the zip file. I would like to propose an option to exclude these Maven/Gradle wrappers.

**Comment by wilkinsona** [comment]
Thanks for the suggestion.

start.spring.io deliberately takes an opinionated view of an application and how it should be built. The team's opinion is that the vast majority of applications should use the build system's wrappers. This matches Gradle's [opinon](https://docs.gradle.org/current/userguide/gradle_wrapper.html) that "the recommended way to execute any Gradle build is with the help of the Gradle Wrapper".

Given our opinion and Gradle's recommendation, offering a configuration option that we believe will rarely be used cannot be justified. If you do not want to use the wrappers you can continue to delete them as you have been doing or you could run your own instance with different opinions.
