### ISSUE TITLE
Spring Boot 2.2 apps should use spring-data-rest-hal-explorer rather than spring-data-rest-hal-browser

### ISSUE THREAD

**Issue by wilkinsona** [spring-io/start.spring.io#184]
The following warning is generated at startup with the current configuration:

```
2019-07-08 10:58:52.310  WARN 40615 --- [           main] o.s.d.rest.webmvc.halbrowser.HalBrowser  : Spring Data REST HAL Browser is deprecated! Prefer the HAL Explorer (artifactId: spring-data-rest-hal-explorer)!
```

**Comment by wilkinsona** [comment]
We shouldn't rush to do this. After making the recommended switch both Chrome and Safari on macOS beach ball and the browser process consumes 100% CPU.

**Comment by snicoll** [comment]
@wilkinsona do you remember the version you used or if there is an update for this one?

**Comment by wilkinsona** [comment]
🤦‍♂ That would have been a good thing to note, wouldn't it. Sorry, I can't remember now.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by dennishendriksen** [comment]
Workaround:
```xml
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-data-rest</artifactId>
	<exclusions>
		<!-- exclude deprecated module in favor of spring-data-rest-hal-explorer -->
		<exclusion>
			<groupId>org.springframework.data</groupId>
			<artifactId>spring-data-rest-hal-browser</artifactId>
		</exclusion>
	</exclusions>
</dependency>
<dependency>
	<groupId>org.springframework.data</groupId>
	<artifactId>spring-data-rest-hal-explorer</artifactId>
</dependency>
```

**Comment by snicoll** [comment]
Oops. I've overlooked this one. This has been superseded by #516 as the browser is deprecated for a while now and removed in Spring Data `2020.0`.
