### ISSUE TITLE
Add ability to a multi-module project

### ISSUE THREAD

**Issue by MaksimRT** [spring-io/start.spring.io#190]
Hi!

Right now I can create a single project.

I want to have ability to create a multi-module project with Maven or Gradle.

Thanks in advance!

**Comment by wilkinsona** [comment]
Thanks for the suggestion. We're already considering this enhancement in the Initializr issue tracker: https://github.com/spring-io/initializr/issues/663. Please feel free to comment on that issue if you have any suggestions or use cases that haven't already been captured.

**Comment by dvsingh9** [comment]
@wilkinsona thank you so much. I opened same issue 2 May 2018 finally its there, great job
