### ISSUE TITLE
Add links to Maven/Gradle plugin documentation in HELP.md

### ISSUE THREAD

**Issue by cicoub13** [spring-io/start.spring.io#202]
I think it could be a good enhancement to generate a README.md with project name, simple instructions (build, test, ...) 📝

**Comment by mbhave** [comment]
We discussed this on the call today and agreed that adding links to our Gradle/Maven plugin documentation makes sense. Any other information about getting started can start getting noisy for anyone who isn't a first time user. We'll limit the scope of this issue to the Gradle/Maven plugin documentation links.

@snicoll Could you transfer it to start.spring.io please?

**Comment by mbhave** [comment]
Sorry, I just realized it is in start.spring.io already 😄

**Comment by snicoll** [comment]
Fixed by 9e06f45
