### ISSUE TITLE
JSF client server web Application

### ISSUE THREAD

**Issue by lodhipr** [spring-io/start.spring.io#205]
I am here to request you to provide me a simple example of web application which can process  through spring boot and follow this type of mechanism like i have add 3 tier architecture of connection.

Architecture: (3-tier)

Server1: database
Server2: app-tier (EAR with Remote EJB + Hibernate) with security 
Server3: web-tier (WAR with JSF 2.0(or any other) + Primefaces 7.0(or any other)) 
Client: Browser

Here Database are stored in one server (Named as Server1),
Server2 are designed to connect through database on Server1,
server3 are designed for interection of client with application.
I have searched an example which perform these three tasks in single Server , for illustration i have added a link of that. please see and provide me a helpful response.

https://examples.javacodegeeks.com/enterprise-java/jsf/jsf-crud-application-example/

**Comment by snicoll** [comment]
@lodhipr unfortunately, providing examples is not what this project is about. For questions in general, please ask on StackOverflow.
