### ISSUE TITLE
Add support for RESTEasy

### ISSUE THREAD

**Issue by asoldano** [spring-io/start.spring.io#22]
I'd like the RESTEasy starter (https://github.com/resteasy/resteasy-spring-boot) to be integrated in start.spring.io; the project was initially created at PayPal (https://github.com/paypal/resteasy-spring-boot) and then donated to Red Hat, where it's currently maintained by the same team (currently reporting to me) of the RESTEasy core.
The most recent release of the starter pulls Spring Boot 2.0.3.RELEASE and RESTEasy 3.6.0.Final (released on June 29th); on master we're already pulling the latest SpringBoot (2.0.4) and RESTEasy core (3.6.1.Final, released yesterday) and  we definitely want to stay in synch in the future.
Please tell which additional information / action from our side you need. Thanks.

**Comment by snicoll** [comment]
@asoldano we've reviewed this and noticed you don't have a compatibility build against Spring Boot 2.1 (the current production line). We've also put a process in place in the meantime that we'd like you to follow to validate we have all we need. You can follow the process by creating a new issue and selecting the "New entry proposal" option. Thank you.

**Comment by asoldano** [comment]
@snicoll OK. The upgrade to Spring Boot 2.1 is already being worked. Will have someone from the team open up a new proposal with the new process as soon the 2.1 upgrade is complete.
