### ISSUE TITLE
HighlightJS not being added in current asciidoctor-maven-plugin dependency

### ISSUE THREAD

**Issue by Turbots** [spring-io/start.spring.io#221]
When choosing Spring REST Docs, the Spring Initializr configures the asciidoctor-maven-plugin for us.

However, the current version `1.5.3` does not add the highlight JS files to the outputted HMTL documentation.

When upgrading to the latest `1.5.8` version, it does work.
Problem was also reported here on SO: https://stackoverflow.com/questions/52669916/asciidoctor-does-not-highlight-source-code-by-highlightjs

**Comment by wilkinsona** [comment]
See https://github.com/spring-projects/spring-restdocs/pull/620 for some background.
