### ISSUE TITLE
Improve search so that matching tokens in the name take precedence over matching in the group

### ISSUE THREAD

**Issue by snicoll** [spring-io/start.spring.io#229]
We use the name of the group as a search token. Let's assume that you have a group named `Foo` and an entry (anywhere) named `My FooLib`. 

Right now if I type `foo`, `My FooLib` isn't first because all entries of the `Foo` group matched and the result list depends on the order of declaration. 

We should put `MyFooLib` at the top here since it's a better match for such query.

**Comment by snicoll** [comment]
I would argue that a search token matching the name should have precedence over a token matching the description only

**Comment by oodamien** [comment]
We are using [js-search](https://github.com/bvaughn/js-search).
We kept this library from the old version. There is no option to filter by field priority.
2 options:
1. Migrate to a new library
2. Perform a second time the search only on the title and apply a sort between the 2 collections

**Comment by snicoll** [comment]
@oodamien thanks for the feedback. Right now, `keywords` and `weight` are no longer honoured by the new client. I think we should improve the relevance of search results and making sure an entry that matches the name takes precedence over one that matches (only) the description would be a first good step.

**Comment by snicoll** [comment]
If we want to revisit the customizations we applied to the old UI, the "weight" and kewyords" we had are available [in this commit](https://github.com/spring-io/start.spring.io/commit/703dff5711430cc03dc9e759690996175dc42490).

**Comment by snicoll** [comment]
There hasn't been a lot of complains and the review of the metadata (harmonization + polish of description) has largely made this a non-issue. Closing.
