### ISSUE TITLE
Add support for Spring Cloud Function with AWS

### ISSUE THREAD

**Issue by OlgaMaciaszek** [spring-io/start.spring.io#23]
The dependencies to look for during the automated verification could be: `spring-cloud-function-adapter-aws` + a Spring Cloud Function starter.  In this case AWS-specific setup for Function could be added to build files.

For `pom.xml` entries in dependencies:
```xml
<dependencies>
	<dependency>
		<groupId>org.springframework.cloud</groupId>
		<artifactId>spring-cloud-function-adapter-aws</artifactId>
	</dependency>
	<dependency>
		<groupId>com.amazonaws</groupId>
		<artifactId>aws-lambda-java-events</artifactId>
		<version>${aws-lambda-events.version}</version>
		<scope>provided</scope>
	</dependency>
	<dependency>
		<groupId>com.amazonaws</groupId>
		<artifactId>aws-lambda-java-core</artifactId>
		<version>1.1.0</version>
		<scope>provided</scope>
	</dependency>
</dependencies>
```

```xml
<dependencyManagement>
	<dependencies>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-function-dependencies</artifactId>
			<version>${spring-cloud-function.version}</version>
			<type>pom</type>
			<scope>import</scope>
		</dependency>
	</dependencies>
</dependencyManagement>
```

- I understand we will have to provide a better versioning mechanism here (a bom?), but I would wait with working out the details of that till and if it's agreed that this new functionality will be added at all. If the user is going to use functions on AWS, they will most likely require these dependencies to create a sensible project.

and plugin changes:
```xml
<build>
	<plugins>
		<plugin>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-maven-plugin</artifactId>
			<dependencies>
				<dependency>
					<groupId>org.springframework.boot.experimental</groupId>
					<artifactId>spring-boot-thin-layout</artifactId>
					<version>${wrapper.version}</version>
				</dependency>
			</dependencies>
		</plugin>
		<plugin>
			<groupId>org.apache.maven.plugins</groupId>
			<artifactId>maven-shade-plugin</artifactId>
			<configuration>
				<createDependencyReducedPom>false</createDependencyReducedPom>
				<shadedArtifactAttached>true</shadedArtifactAttached>
				<shadedClassifierName>aws</shadedClassifierName>
			</configuration>
		</plugin>
	</plugins>
</build>
```
This is to ensure that we don't generate and send over to Lambda the typical SpringBoot fatjars, but much ligher jars, appropriate for the serverless approach.

For gradle, we would also have additional dependencies:

```groovy
compile("org.springframework.cloud:spring-cloud-function-adapter-aws:${springCloudFunctionVersion}")
compileOnly("com.amazonaws:aws-lambda-java-events:${awsLambdaEventsVersion}")
compileOnly("com.amazonaws:aws-lambda-java-core:${awsLambdaCoreVersion}")
```
and plugin setup:

```groovy
buildscript {
    dependencies {
        classpath "com.github.jengelman.gradle.plugins:shadow:${shadowVersion}"
		classpath("org.springframework.boot.experimental:spring-boot-thin-gradle-plugin:${wrapperVersion}")
	}
}

apply plugin: 'com.github.johnrengelman.shadow'
apply plugin: 'org.springframework.boot.experimental.thin-launcher'

shadowJar {
  classifier = 'aws'
  dependencies {
    exclude(dependency("org.springframework.cloud:spring-cloud-function-web:${springCloudFunctionVersion}"))
  }
  // Required for Spring
  mergeServiceFiles()
  append 'META-INF/spring.handlers'
  append 'META-INF/spring.schemas'
  append 'META-INF/spring.tooling'
  transform(PropertiesFileTransformer) {
    paths = ['META-INF/spring.factories' ]
    mergeStrategy = "append"
  }
}
```
This is to ensure that we don't generate and send over to Lambda the typical SpringBoot fatjars, but much ligher jars, appropriate for the serverless approach.
- again, approach to versioning to be proposed once a decision is taken if we are going to work on it or not. 
Handling it for the regular dependencies shouldn't be a problem, however, we would have to think how we could handle it for the gradle plugins, since the buildscript dependencies will probably not work with dependency management.

Full setup [here](https://github.com/spring-cloud/spring-cloud-function/blob/master/spring-cloud-function-samples/function-sample-aws/build.gradle).

**Comment by snicoll** [comment]
Thanks but I am not sure I got the use case: what "cloud aws" entry are you talking about? Right now, Spring Cloud AWS  doesn't have a general "AWS support" like the other have so it's harder for the user to signal this. 

> Full setup here.

Rather than a full setup, can you please indicate what specifically the build should contain. You mentioned shadow jar plugin but it's unclear why that's necessary or what the actual use case is.

I can also see hardcoded version in this build which is something that I am not keen to do without some additional justification.

**Comment by OlgaMaciaszek** [comment]
>Thanks but I am not sure I got the use case: what "cloud aws" entry are you talking about? 
- As indicated below, I'm thinking, we could use `spring-cloud-function-adapter-aws` to check that the user is intending to use Function on AWS. Wdyt?

**Comment by snicoll** [comment]
> Btw., it seems we will have to add a checkbox for that as well.

That is exactly the point I am trying to make. This issue can't move forward until we have a proper representation of the input.

**Comment by OlgaMaciaszek** [comment]
Sure, will do a separate issue for that checkbox and link it here.

**Comment by OlgaMaciaszek** [comment]
> You mentioned shadow jar plugin but it's unclear why that's necessary or what the actual use case is.

We can't send typical SprinbBoot fatjars to AWS; the shade plugin is used to package into a ligther jar. It's also the recommended way to go suggested in various articles in AWS docs.

**Comment by snicoll** [comment]
There is no `cloud-aws` checkbox. 

I had the same idea, that's what I was referring to in a previous comment:

> Right now, Spring Cloud AWS doesn't have a general "AWS support" like the other have so it's harder for the user to signal this.

If we want to pursue, my vote is to align and use that indeed as a signal. But we need to figure out the minimum viable project that is required for this to be satisfactory. The build you referenced is quite dense and I am not too happy applying all those customizations here. Let's chat a bit more about why there are there and why we need them.

**Comment by dsyer** [comment]
If you think that is dense wait till you see the Azure one. Seriously though, it is only one extra plugin (plus the dependencies). Is that a problem?

**Comment by snicoll** [comment]
> Is that a problem?

I don't know yet. I've asked for more details [in a previous comment](https://github.com/spring-io/start.spring.io/issues/23#issuecomment-446592176) (rather than a full build that may contain some noise). Once we have that we can discuss on the actual requested change.

**Comment by OlgaMaciaszek** [comment]
@snicoll I will edit it and provide separate code snippets for the changes - I just thought a sample pom/ build files would be more readable than a list of code snippets.

**Comment by snicoll** [comment]
> I just thought a sample pom/ build files would be more readable than a list of code snippets.

I agree it is more readable but it's harder to know what's actually required and why. We'd need some context for each code snippet.

**Comment by snicoll** [comment]
This one hasn't seen much traction and it goes in the same "too much configuration" bucket IMO. I am going to decline this for the same reason expressed in a similar issue https://github.com/spring-io/start.spring.io/issues/25#issuecomment-462968108.

**Comment by dsyer** [comment]
I wish you’d reopen. I’m not sure traction is a good metric for when to close, and how do you define that anyway? IMO there would be demand for ready-made Lambda projects. If we are adding generator features to initializr and we can’t support simply adding a few plugins to the build, then maybe there is a problem with the generator?

**Comment by snicoll** [comment]
As indicated in the linked issue, it is not about being able to support it or not but the amount of code and complexity we are willing to add here. I recommend the same approach as in #25: let's first see how we can reduce the amount of complexity that is required so that users that don't use the initializr can benefit from it and we can for sure reconsider this request.

**Comment by dsyer** [comment]
How is that going to happen though? What steps would you suggest to move towards a universe where such benefits are available?

**Comment by wilkinsona** [comment]
I'm not sure about Maven, but for Gradle I would write a plugin to shield users from the low-level details of how to create a Lambda-friendly jar by making it much more declarative than it is today. IMO, the current configuration expects that user to know too much about how to configure things rather than letting them focus on the what.
