### ISSUE TITLE
[Fishtown.SR4] release of the [spring-cloud-stream-starters] release train took place

### ISSUE THREAD

**Issue by spring-buildmaster** [spring-io/start.spring.io#231]
Release train [spring-cloud-stream-starters] in version [Fishtown.SR4] released with the following projects:

spring-boot-dependencies : `2.1.7.RELEASE`
spring-cloud-stream-dependencies : `Fishtown.SR4`
spring-boot-starter : `2.1.7.RELEASE`
spring-cloud-stream : `2.1.4.RELEASE`
spring-cloud-stream-starters : `Fishtown.SR4`
spring-cloud-build : `2.1.6.RELEASE`
spring-cloud-dependencies : `2.1.6.RELEASE`
spring-cloud-function : `2.0.1.RELEASE`
spring-boot : `2.1.7.RELEASE`
spring-cloud-stream-binder-kafka : `2.1.4.RELEASE`
spring-cloud-stream-binder-rabbit : `2.1.4.RELEASE`

**Comment by snicoll** [comment]
This shouldn't be necessary as we manage the version of Spring Cloud Stream via the general Spring Cloud release train.

I've opened https://github.com/spring-cloud/spring-cloud-release-tools/issues/160
