### ISSUE TITLE
[Germantown.SR1] release of the [spring-cloud-stream-starters] release train took place

### ISSUE THREAD

**Issue by spring-buildmaster** [spring-io/start.spring.io#232]
Release train [spring-cloud-stream-starters] in version [Germantown.SR1] released with the following projects:

spring-boot-dependencies : `2.1.7.RELEASE`
spring-cloud-stream-dependencies : `Germantown.SR1`
spring-cloud-stream : `2.2.1.RELEASE`
spring-boot-starter : `2.1.7.RELEASE`
spring-cloud-build : `2.1.6.RELEASE`
spring-cloud-stream-starters : `Germantown.SR1`
spring-cloud-dependencies : `2.1.6.RELEASE`
spring-boot : `2.1.7.RELEASE`
spring-cloud-stream-binder-rabbit : `2.2.1.RELEASE`
spring-cloud-stream-binder-kafka : `2.2.1.RELEASE`

**Comment by snicoll** [comment]
See https://github.com/spring-io/start.spring.io/issues/231#issuecomment-525631691
