### ISSUE TITLE
Make with success messages more concise

### ISSUE THREAD

**Issue by wilkinsona** [spring-io/start.spring.io#237]
There are a few actions in the UI that result in a with success message being displayed to those user. Those messages are the following:

- Your file has been copied in the clipboard with success.
- Your file has been downloaded with success.
- Your project has been generated with success
- Your project has been downloaded with success

I think the messages could be tightened up a bit and made more concise without losing any of their meaning. Here's an initial proposal:

- File copied to the clipboard.
- File downloaded.
- Project generated.
- Project downloaded.

The first could perhaps even be "File copied." if there's already enough context to make it clear that the destination is the clipboard. The would align it with the two downloaded messages that do not describe the destination. That would make the messages the following:

- File copied.
- File downloaded.
- Project generated.
- Project downloaded.

**Comment by snicoll** [comment]
I was also wondering if some of these messages could be removed completely. If we invoke the generate project action and, as a result, we download a file, isn't that enough signal for the user?

I've seen myself ignoring the green top header completely as my eye focused on the fact a new file was downloading....

**Comment by wilkinsona** [comment]
It does feel a little strange to display something that tells you that the UI element you just clicked on has worked. On further consideration, I would have no objection to removing all four messages. In fact, I think that's what I would prefer.

**Comment by oodamien** [comment]
We need at least to provide a feedback for the copy to clipboard.
There is no other feedback than this one.

**Comment by snicoll** [comment]
Closing in favour of PR #239
