### ISSUE TITLE
Add stub class extending AWS adapter SpringBootRequestHandler when both Cloud Function and Cloud AWS added

### ISSUE THREAD

**Issue by OlgaMaciaszek** [spring-io/start.spring.io#24]
The dependencies to look for during the automated verification could be: `spring-cloud-function-adapter-aws` + `spring-cloud-starter-function-webflux`. In this case a class stub extending `org.springframework.cloud.function.adapter.aws.SpringBootRequestHandler` could be added. Working stub available [here](https://github.com/spring-cloud/spring-cloud-function/blob/master/spring-cloud-function-samples/function-sample-aws/src/main/java/example/Handler.java).

**Comment by snicoll** [comment]
> `spring-cloud-function-adapter-aws` + `spring-cloud-starter-function-webflux`

None of those entries are available at the moment. How would a user end up with this combination in a project generated from start.spring.io?

**Comment by OlgaMaciaszek** [comment]
> None of those entries are available at the moment. How would a user end up with this combination in a project generated from start.spring.io?

yes, would have to either add new checkboxes for the adapters or, as @dsyer proposes, make the existing Azure Support checkbox smart enough that if you also choose "cloud-function" it would only add the Lambda stuff.

We could probably discuss it as part of this issue.

**Comment by dsyer** [comment]
Webflux is irrelevant, actually (it wouldn't be used in AWS anyway). So really we are looking at `cloud-function` (the existing checkbox) and "something new with AWS" to signal a Lambda. There needs to be a shade/shadow plugin configuration as well BTW (AWS doesn't know how to deploy fat jars).

**Comment by mbhave** [comment]
Closing in favor of #30. See [this comment](https://github.com/spring-io/start.spring.io/issues/26#issuecomment-447421325).
