### ISSUE TITLE
Fix "The server API is not available" error message to also refer to a connection problem

### ISSUE THREAD

**Issue by prasanjitachary** [spring-io/start.spring.io#247]

**Comment by snicoll** [comment]
The Web UI is not part of Initializr so I've moved the issue you've created to the appropriate issue tracker.

> How can we reproduce?

@prasanjitachary please make sure to review the complete message before replying. How can we reproduce this issue or what have you done to trigger it?

**Comment by snicoll** [comment]
@prasanjitachary gentle ping.

**Comment by snicoll** [comment]
In the absence of feedback, let's reuse this issue to improve the error message as we've got a few other reports. Turns out this was a network glitch (and not a server error) so we should update the error message to make sure users check their connectivity.

**Comment by snicoll** [comment]
Superseded by #267
