### ISSUE TITLE
Change build setup when both Cloud Function and Azure added

### ISSUE THREAD

**Issue by OlgaMaciaszek** [spring-io/start.spring.io#25]
The dependencies to look for during the automated verification could be: `spring-cloud-function-adapter-azure` + a Spring Cloud Function starter. In this case, Azure-specific setup for Function could be added to build file.

For `pom.xml`, we would need this dependency:

```xml
<dependencies>
	<dependency>
		<groupId>org.springframework.cloud</groupId>
		<artifactId>spring-cloud-function-adapter-azure</artifactId>
	</dependency>
</dependencies>

<dependencyManagement>
<dependencies>
	<dependency>
		<groupId>org.springframework.cloud</groupId>
		<artifactId>spring-cloud-function-dependencies</artifactId>
		<version>2.0.0.BUILD-SNAPSHOT</version>
		<type>pom</type>
		<scope>import</scope>
	</dependency>
</dependencies>
</dependencyManagement>
```
We would also need specific setup for the following plugins: `maven-clean-plugin`, `maven-resources-plugin`, `azure-functions-maven-plugin`, `maven-deploy-plugin`, `maven-dependency-plugin`:

```xml
<build>
		<pluginManagement>
			<plugins>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-clean-plugin</artifactId>
					<configuration>
						<filesets>
							<fileset>
								<directory>${basedir}</directory>
								<includes>
									<include>obj/**</include>
								</includes>
							</fileset>
							<fileset>
								<directory>${basedir}</directory>
								<includes>
									<include>extensions.csproj</include>
								</includes>
							</fileset>
						</filesets>
					</configuration>
				</plugin>
				<plugin>
					<artifactId>maven-resources-plugin</artifactId>
					<version>3.0.2</version>
				</plugin>
				<plugin>
					<groupId>com.microsoft.azure</groupId>
					<artifactId>azure-functions-maven-plugin</artifactId>
					<version>1.0.0-beta-7</version>
					<dependencies>
						    <dependency>
								<groupId>javax.xml.bind</groupId>
								<artifactId>jaxb-api</artifactId>
								<version>2.3.1</version>
							</dependency>
					</dependencies>
				</plugin>
			</plugins>
</pluginManagement>
```
Add necessary jaxb-api dependency for the Azure Functions Maven plugin. Set up the Maven Clean plugin, to take into account the locations of the generated Azure-specific files.

 ```xml
<plugins>
	<plugin>
		<groupId>org.apache.maven.plugins</groupId>
		<artifactId>maven-dependency-plugin</artifactId>
		<executions>
			<execution>
				<id>copy-dependencies</id>
				<phase>prepare-package</phase>
				<goals>
					<goal>copy-dependencies</goal>
				</goals>
				<configuration>
					<outputDirectory>${stagingDirectory}/lib</outputDirectory>
					<overWriteReleases>false</overWriteReleases>
					<overWriteSnapshots>false</overWriteSnapshots>
					<overWriteIfNewer>true</overWriteIfNewer>
					<includeScope>runtime</includeScope>
				</configuration>
			</execution>
		</executions>
	</plugin>
	<plugin>
		<groupId>com.microsoft.azure</groupId>
		<artifactId>azure-functions-maven-plugin</artifactId>
		<configuration>
			<resourceGroup>${functionResourceGroup}</resourceGroup>
			<appName>${functionAppName}</appName>
			<region>${functionAppRegion}</region>
			<appSettings>
				<property>
					<name>FUNCTIONS_EXTENSION_VERSION</name>
					<value>beta</value>
				</property>
				<property>
					<name>MSDEPLOY_RENAME_LOCKED_FILES</name>
					<value>1</value>
				</property>
			</appSettings>
		</configuration>
		<executions>
			<execution>
				<id>package-functions</id>
				<goals>
					<goal>package</goal>
				</goals>
			</execution>
		</executions>
	</plugin>
	<plugin>
		<artifactId>maven-resources-plugin</artifactId>
		<executions>
			<execution>
				<id>copy-resources</id>
				<phase>package</phase>
				<goals>
					<goal>copy-resources</goal>
				</goals>
				<configuration>
					<overwrite>true</overwrite>
					<outputDirectory>
						${project.build.directory}/azure-functions/${functionAppName}
					</outputDirectory>
					<resources>
						<resource>
							<directory>${project.basedir}/src/main/azure</directory>
							<includes>
								<include>**</include>
							</includes>
						</resource>
					</resources>
				</configuration>
			</execution>
		</executions>
	</plugin>
	<plugin>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-maven-plugin</artifactId>
		<dependencies>
			<dependency>
				<groupId>org.springframework.boot.experimental</groupId>
				<artifactId>spring-boot-thin-layout</artifactId>
				<version>${wrapper.version}</version>
			</dependency>
		</dependencies>
	</plugin>
</plugins>
```
We add the Azure Functions plugin that will generate the function.json files necessary to run the functions in the  cloud and will scan the build output directory and copy any jars from there to the staging directory (`${project.basedir}/target/azure-functions/${function-app-name}/` by default). We confiugre it with the sepcific resource group, appName and region (possibly placeholders only to be overwritten by the user?). We then use the Maven Dependencies and Maven Resources plugins to copy the dependencies and resources to the Azure staging directory as well. We could also add config for the `maven-deploy-plugin` to skip the usual maven deployment.

We will probably have to provide a better versioning mechanism here (a bom?), but I would wait with working out the details of that till and if it's agreed that this new functionality will be added at all.

 Full setup available [here](https://github.com/spring-cloud/spring-cloud-function/blob/master/spring-cloud-function-samples/function-sample-azure/pom.xml).

**Comment by mbhave** [comment]
That is a lot of configuration. I'm not keen on adding so much code as part of project generation for multiple reasons. It could quickly get out of sync and maintenance overhead seems high. It also feels like we should try to improve the the developer experience for all users of Spring Cloud Function instead of hiding the complexity for projects generated on start.spring.io. 

I don't think we should do this in it's current form. The Spring Cloud Function issue tracker is probably the right place to discuss if the developer experience can be simplified for everyone so I'm going to close this issue.
