### ISSUE TITLE
Add spring-cloud-starter-loadbalancer

### ISSUE THREAD

**Issue by OlgaMaciaszek** [spring-io/start.spring.io#254]
We have just merged [a PR that adds spring-cloud-starter-loadbalancer](https://github.com/spring-cloud/spring-cloud-commons/pull/599). We would like to make it available via start.spring.io. Let me know if that's fine - I can create a PR.

**Comment by wilkinsona** [comment]
Sounds reasonable to me. Thanks for the offer of a PR. One thing to figure out is how to distinguish it from the existing Ribbon entry. We can do that as part of processing the PR once there's a proposal to review.

**Comment by OlgaMaciaszek** [comment]
The current one is named: Ribbon,  id: cloud-ribbon.
The new one could be named: Spring Cloud LoadBalancer, id: cloud-loadbalancer.

I don't think it should be a problem to have many load-balancers - we also have various discovery clients and 2 router implementations and it has never been an issue.

**Comment by wilkinsona** [comment]
Just to be clear (as I obviously wasn't above), I wasn't wondering if we should only offer one or the other, just that we should make sure the descriptions help users to pick one over the other.

**Comment by mbhave** [comment]
Thanks for the clarification, @wilkinsona. 

@OlgaMaciaszek We can review the PR when you have one.

**Comment by snicoll** [comment]
Closing in favour of PR #310
