### ISSUE TITLE
Add "spring-integration-test" when Spring Integration is selected

### ISSUE THREAD

**Issue by artembilan** [spring-io/start.spring.io#257]
The `spring-integration-test` brings many useful testing features for integration solutions: https://docs.spring.io/spring-integration/reference/html/#testing

So, would be great to have it included into `test` scope dependencies when we select Spring Integration from start.spring.io

**Comment by snicoll** [comment]
@artembilan thanks for the suggestion but this project is about the library, not what start.spring.io does on specific dependencies. I've moved the issue to the appropriate issue tracker.

**Comment by artembilan** [comment]
Thanks, @snicoll , for heads up!
Will know next time that start.spring.io is not just Initializr project any more 😄 

And sorry for noise.
