### ISSUE TITLE
Add stub class extending Azure adapter AzureSpringBootRequestHandler when both Cloud Function and Azure Support added

### ISSUE THREAD

**Issue by OlgaMaciaszek** [spring-io/start.spring.io#26]
The dependencies to look for during the automated verification could be: Azure Support + Spring Cloud Function starter. In this case a class stub extending `org.springframework.cloud.function.adapter.azure.AzureSpringBootRequestHandler` could be added. Working stub available [here](https://github.com/spring-cloud/spring-cloud-function/blob/master/spring-cloud-function-samples/function-sample-azure/src/main/java/example/FooHandler.java).

It could also contain a stub of an `execute(...)` method as in the example with the annotations, like below, but this might be too much auto-generated code, so should probably be discussed by the teams:

```java
@FunctionName("uppercase")
	public Bar execute(
			@HttpTrigger(name = "req", methods = { HttpMethod.GET,
					HttpMethod.POST }, authLevel = AuthorizationLevel.ANONYMOUS) Foo foo,
			ExecutionContext context) {
		return handleRequest(foo, context);
	}
```

**Comment by bclozel** [comment]
You're right @OlgaMaciaszek - this sounds like too much code generation to me.
If we go down that path, we could add a default Controller with a sample handler, maybe another one if we've got a view technology selected, add a few `@WebMvcTest` and more...

When we were tempted to do that in the past, it was usually a sign that we needed to:

* document things better in the project itself
* tweak the auto-configuration to add a missing default experience

We definitely don't want to be in a position where users need to change code we've generated when upgrading, or worse delete code they don't want right after project generation.

We're also considering adding pointers in a HELP.md file, inside the generated project. This might be another way to solve such issues.

I'll let the rest of the team comment on that.

**Comment by mbhave** [comment]
I agree with what @bclozel said. I'm not in favor of going in the direction of scaffolding projects. Adding links to documentation and samples in the `HELP.md` seems like the right fit for this use case. 

I'm also not sure how the Azure support dependency can be used for detecting this.

**Comment by mbhave** [comment]
I'm going to close this issue in favor of adding more information to the `Help.md`. If `cloud-function` is selected, the help can include links to documentation for functions on all supported platforms. If there's another dependency that indicates the intended platform, help will be filtered accordingly. For example if `cloud-function` + `aws-core` is selected, help will only have links to documentations/guides for AWS functions.
