### ISSUE TITLE
Add chose java version

### ISSUE THREAD

**Issue by sgrillon14** [spring-io/start.spring.io#265]
Can you add java version in form? exemple java 11.

If you give me a java 11 sample, I can develop this part and create a pull request.

**Comment by snicoll** [comment]
Thanks for the feedback. Please note this is the wrong place to report an enhancement of the Web UI as there is a dedicated project for start.spring.io (as indicated by the link in the upper right corner of the UI). I've moved the issue to the appropriate issue tracker for reference.
