### ISSUE TITLE
Include experimental starter for Spring Data R2DBC

### ISSUE THREAD

**Issue by mp911de** [spring-io/start.spring.io#269]
Please include a starter for Spring Data R2DBC.

Version requirement: >= Spring Boot 2.2 M6
Repository backing the starter: https://github.com/spring-projects-experimental/spring-boot-r2dbc
Starter artifact: `org.springframework.boot.experimental:spring-boot-starter-data-r2dbc`
Starter version: 0.1.0.BUILD-SNAPSHOT
BOM to import: `org.springframework.boot.experimental:spring-boot-bom-r2dbc`
Example application: https://github.com/spring-projects-experimental/spring-boot-r2dbc/tree/master/spring-boot-example-h2

Artifacts are available from repo.spring.io (R2DBC, starters and Spring Data R2DBC) and will be deployed on GA to Maven Central.

**Comment by snicoll** [comment]
Thanks @mp911de for your help this week on this topic. There is a now an entry and special handling for the four JDBC drivers that are on the site: h2, mysql, postgresql and sqlserver.
