### ISSUE TITLE
Add an entry to HELP.md that explains the transformation applied to an illegal package name to make it legal

### ISSUE THREAD

**Issue by wimdeblauwe** [spring-io/start.spring.io#276]
If I use dashes in my artifact name (e.g. `thymeleaf-live-reload`) and I expand the "Options", it shows something like `com.company.thymeleaf-live-reload` as 'Package Name', which is not a valid package name. Luckily, the generated package name is `com.company.thymeleaflivereload` so you get a correct package name. It would be good to also have it correct on the website itself.

**Comment by wilkinsona** [comment]
We discussed this today and the team is in agreement that we should not try to replicate the server-side rules on the client-side. We'll use this issue to track adding an explanation to the generated `HELP.md` file.

**Comment by wimdeblauwe** [comment]
I am totally ok with that, just wanted to point out the fact that most people need to do that when writing a client application in order to provide early feedback to their users. Even in a Spring application itself: there are validations done on the database level (e.g. with JPA annotations), but usually, there is also validation done at the (rest)controller level.

The way I usually see it is that server-side validation is the last line of defence and client-side is just "helping" the user as much as possible. So even if not _all_ server side rules are duplicated, it does not matter too much IMO.

But again, not trying to convince you here, just my 2 cents.

**Comment by snicoll** [comment]
Blocked by https://github.com/spring-io/initializr/issues/1005

**Comment by snicoll** [comment]
We've made great progress on https://github.com/spring-io/initializr/pull/1023. Unfortunately, the cleaning of the package name happens too soon for us to track it. It's now also blocked by https://github.com/spring-io/initializr/issues/1045
