### ISSUE TITLE
Building maven project for spring cloud contract with kotlin

### ISSUE THREAD

**Issue by eddumelendez** [spring-io/start.spring.io#278]
working in a project with `kotlin` and `spring-cloud-contract` the following changes were needed in a `maven` project. Contracts were defined in `kotlin` too

* Producer's `pom.xml`

```xml
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-contract-spec-kotlin</artifactId>
    <scope>test</scope>
</dependency>
<dependency>
    <groupId>io.rest-assured</groupId>
    <artifactId>spring-web-test-client</artifactId>
    <scope>test</scope>
</dependency>
```

Needed `io.rest-assured:spring-web-test-client` because was using `webflux`

```xml
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-compiler-plugin</artifactId>
    <executions>
        <!-- Replacing default-compile as it is treated specially by maven -->
        <execution>
            <id>default-compile</id>
            <phase>none</phase>
        </execution>
        <!-- Replacing default-testCompile as it is treated specially by maven -->
        <execution>
            <id>default-testCompile</id>
            <phase>none</phase>
        </execution>
        <execution>
            <id>java-compile</id>
            <phase>compile</phase>
            <goals>
                <goal>compile</goal>
            </goals>
        </execution>
        <execution>
            <id>java-test-compile</id>
            <phase>test-compile</phase>
            <goals>
                <goal>testCompile</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```

This dependency was also needed in `org.springframework.cloud:spring-cloud-contract-maven-plugin`

```xml
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-contract-spec-kotlin</artifactId>
    <version>...</version>
</dependency>
```

Also, upgrade dependency `<rest-assured.version>4.0.0</rest-assured.version>` was required.

* Consumer's `pom.xml`

```xml
<dependency>
    <groupId>org.jetbrains.kotlin</groupId>
    <artifactId>kotlin-scripting-compiler-embeddable</artifactId>
    <version>${kotlin.version}</version>
</dependency>
```

I am wondering if this is something will be provided by `start.spring.io` or it will be documented in `HELP.md`

**Comment by snicoll** [comment]
Thanks for the report @eddumelendez. We support tuning the build for such dependency so I think we should do our best to support that out of the box.

cc @OlgaMaciaszek

**Comment by eddumelendez** [comment]
I'll be submitting a PR to provide that

**Comment by snicoll** [comment]
@eddumelendez I've seen the commit and I missed it so I apologizes for not asking sooner. It looks like you have both java code and kotlin code in your project. Did I read this right? Can you please share a bit more info about your use case?

**Comment by eddumelendez** [comment]
@snicoll no worries. I worked on some demos and you can take a look into them [here](https://github.com/eddumelendez/kotlin-everywhere-gdglima-demo). These projects are full `kotlin` using `maven` as a build tool. What I was reporting is that there are missing configurations like dependencies or some tuning in the `maven-compiler-plugin`. PR #283 provides all the configuration needed for the producer and the consumer side when the language is `kotlin` and the build tool is `maven`. This is based on producer using the `spring-cloud-starter-contract-verifier` dependency and the consumer using the `spring-cloud-starter-contract-stub-runner` dependency

**Comment by snicoll** [comment]
Thanks. Let's continue the discussion on the PR

Closing in favour of PR #283
