### ISSUE TITLE
Mark Spring Cloud Netflix projects as maintenance mode

### ISSUE THREAD

**Issue by OlgaMaciaszek** [spring-io/start.spring.io#28]
Information about the tools being in maintenance mode should be added to the `help.md` file.

**Comment by mbhave** [comment]
In addition to this, I think we should disable these dependencies for Boot 2.2.x projects (Spring Cloud Hoxton). I also wonder if we should go a step further and disable them for Boot 2.1.x (Spring Cloud Greenwich).

**Comment by spencergibb** [comment]
No, not for Greenwich. We need to discuss for Hoxton.

**Comment by snicoll** [comment]
Sounds good, let us know what you decide and we can adapt.

@OlgaMaciaszek would you be willing to contribute a PR to add a blurb in `HELP.md`? We're going to roll-out the feature soon and we can include this one as well.

**Comment by OlgaMaciaszek** [comment]
Yes, @snicoll . Will do that.

**Comment by OlgaMaciaszek** [comment]
Submitted a PR, although, later on I think it should be considered to enable adding this warning section on top of `HELP.md` (ordering is currently not supported by Initializr).

**Comment by snicoll** [comment]
Closing in favour of PR #112
