### ISSUE TITLE
Dark UI toggle misplaced on Firefox

### ISSUE THREAD

**Issue by dreis2211** [spring-io/start.spring.io#287]
Hi,

I just noticed a tiny issue on https://start.spring.io on Firefox where the new and awesome Dark UI toggle reaches into its label. This doesn't happen on Chrome. This is especially visible if it's actually toggled and in Dark mode.

![grafik](https://user-images.githubusercontent.com/6304496/66261041-18acd980-e7c7-11e9-80af-a042b912cb25.png)

Cheers,
Christoph

**Comment by oodamien** [comment]
Thanks for the feedback @dreis2211.

**Comment by snicoll** [comment]
Closing in favour of PR #289
