### ISSUE TITLE
Make JUnit consistent between Spring Boot 2.2.x and Spring Cloud Contract Verifier 

### ISSUE THREAD

**Issue by eddumelendez** [spring-io/start.spring.io#294]
When entries `spring-boot``2.2.x` and `spring-cloud-contract-verifier` are selected JUnit is inconsistent since boot relies on JUnit 5 and verifier relies on JUnit 4. May the configuration regarding `testFramework` can be added.

**Comment by snicoll** [comment]
> JUnit is inconsistent since boot relies on JUnit 5 and verifier relies on JUnit 4. 

Sorry but I am not following that. As far as I know, Spring Cloud Contract has support for JUnit 5 for quite some time. Can you please explain what you mean by that?

**Comment by eddumelendez** [comment]
if you agree, I can send a PR for this later today

**Comment by snicoll** [comment]
Closing in favour of PR #296
