### ISSUE TITLE
Add Spring Security rsocket support when RSocket and Security are selected

### ISSUE THREAD

**Issue by snicoll** [spring-io/start.spring.io#298]
In order to get security support with RSocket, I understand that `spring-security-rsocket` should be added to the project.

I am suggesting start.spring.io does this automatically when the user has selected both RSocket and Security. 

cc @bclozel, @rwinch

**Comment by bclozel** [comment]
We've got both `'org.springframework.security:spring-security-rsocket'` and `'org.springframework.security:spring-security-messaging'` available. I'm not sure which should be added when, depending on the other dependencies chosen by developers.

**Comment by snicoll** [comment]
Thanks both, we'll update the conventions to do that then.
