### ISSUE TITLE
Web UI build does not work on Windows

### ISSUE THREAD

**Issue by zcy790811** [spring-io/start.spring.io#299]
On windows 10，when I make the program。execute command ./mvn install clean.
Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.7.5:yarn (yarn install) on project start-client: Failed to run task: 'yarn ' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]

**Comment by wilkinsona** [comment]
Can you share the complete output from the build? Hopefully something is logged earlier that shows why execution of `yarn` failed.

**Comment by snicoll** [comment]
I can reproduce on a Windows 7 VM but didn't manage to get a lot of output from the frontend-maven-plugin. It looks like this command is failing:

```
cross-env NODE_ENV=test import-sort -l "(src|utils|plugins)/**/*.js" && prettier --check "src/**/*.{{c,le,sc}ss,g?(raph)ql,htm?(l),js?(on|on5|onl|x|s),md?(x|wn),m?(ark)down,mkdn,ts?(x),vue,y?(a)ml}" && eslint "src"
```

**Comment by oodamien** [comment]
Tests done on Windows 7 (x64):
- Install `node` / `yarn`
- Run `yarn` and `yarn start` on start-client with success

**Comment by oodamien** [comment]
@zcy790811

We are still working on it. 
As a workaround, you can update the file `start-client/package.json`:
```
    "prebuild": "yarn run clean && yarn run lint && yarn run test",
```

to

```
    "prebuild": "yarn run clean && yarn run test",
```

**Comment by zcy790811** [comment]
> Can you share the complete output from the build? Hopefully something is logged earlier that shows why the execution of `yarn` failed.

Thanks a lot, I haved solved this problem, the reason is the network problem which could't download the full zip or tar.gz file.

**Comment by zcy790811** [comment]
> I can reproduce on a Windows 7 VM but didn't manage to get a lot of output from the frontend-maven-plugin. It looks like this command is failing:
> 
> ```
> cross-env NODE_ENV=test import-sort -l "(src|utils|plugins)/**/*.js" && prettier --check "src/**/*.{{c,le,sc}ss,g?(raph)ql,htm?(l),js?(on|on5|onl|x|s),md?(x|wn),m?(ark)down,mkdn,ts?(x),vue,y?(a)ml}" && eslint "src"
> ```

Thanks a lot, I haved solved this problem, the reason is the network problem which could't download the full zip or tar.gz file.

**Comment by zcy790811** [comment]
Thanks a lot, I haved solved this problem, the reason is the network problem which could't download the full zip or tar.gz file.

Now I am working on another problem. If I can't kill it, I will continue this topic.
