### ISSUE TITLE
Create bootstrap.properties when the Spring Cloud bootstrap context is available

### ISSUE THREAD

**Issue by snicoll** [spring-io/start.spring.io#301]
When the Spring Cloud bootstrap context is available, a `bootstrap.properties` is often used to provide dedicated settings such as the location of the config server to use. It would be nice if we generate that file.

I don't see an easy way to figure out that the bootstrap context is available based on the dependency. We may use a `facet` for that.

**Comment by dsyer** [comment]
A quick scan leads me to concolude that with the current checkboxes the ones that might use `bootstrap.properties` would be `cloud-*`, excluding `*=[function,stream,connectors]`.

**Comment by snicoll** [comment]
We're going away of the bootstrap context so I am going to close this now.
