### ISSUE TITLE
The `developmentOnly` configuration only works for devtools

### ISSUE THREAD

**Issue by hemeroc** [spring-io/start.spring.io#305]
**Setup:**

- ceate a new project
  - `gradle`, `kotlin`, `2.2.x`
  - `devTools` and `actuator` dependencies
- set the actuator dependency from `implementation` to `developmentOnly`
- run `./gradlew clean build`

**Expected behaviour:**

- devtools is not packaged within the jar
- actuator is not packaged within the jar 

**Current behaviour:**

- devtools is not packaged within the jar
- actuator is packaged within the jar 

```bash
$ jar tf build/libs/demo-0.0.1-SNAPSHOT.jar | grep -E "actuator|devtools"
BOOT-INF/lib/spring-boot-starter-actuator-2.2.0.RELEASE.jar
BOOT-INF/lib/spring-boot-actuator-autoconfigure-2.2.0.RELEASE.jar
BOOT-INF/lib/spring-boot-actuator-2.2.0.RELEASE.jar
```

---

Either I'm doing something completely wrong or there is a bug in the jar packaging or the behaviour is intended but then the name is misleading.

**Comment by wilkinsona** [comment]
It's development only in that it's on the classpath while you're developing and running your application, but it not on the classpath while you're testing your classpath. It's the `bootJar` task, via its `excludeDevtools` property (which defaults to try) that prevents the DevTools jar from  being packaged in `BOOT-INF/lib`.

[The name `developmentOnly` isn't perfect](https://github.com/spring-projects/spring-boot/issues/14451#issuecomment-421067494), but we've been unable to think of a better, reasonably concise name. If you'd like to suggest something we'd be more than happy to consider it.

**Comment by hemeroc** [comment]
Ok, now that makes a lot more sense. Thanks for clarification.
In my project I now excluded all `developmentOnly` dependencies with following code snippet:

```kotlin
tasks.withType<BootJar> {
    exclude { developmentOnly.resolvedConfiguration.files.contains(it.file) }
}
```

**Comment by wilkinsona** [comment]
Thanks for following up. You may be interested in [this Spring Boot issue](https://github.com/spring-projects/spring-boot/issues/16599). Once implemented, it should take care of all of this for you.
