### ISSUE TITLE
Add spring-javaformat as dependency option 

### ISSUE THREAD

**Issue by marceloverdijk** [spring-io/start.spring.io#306]
If selected, it should apply the checkstyle plugin automatically, and create a basic checkstyle.xml.

**Comment by snicoll** [comment]
@marceloverdijk request for adding entries have to be submitted on the `start.spring.io` project and there is a template you need to fill in. Before going there, I'd like the feedback on the team as I am not sure we want to add an option for javaformat at this point.

**Comment by marceloverdijk** [comment]
OK, I just found out about spring-javaformat recently. 
I don't know if it's meant for Spring projects only or also something for the community to use.
If the latter, than it might be good to publish the plugin to the Gradle Central Plugin Repository as well, similar as the `io.spring.dependency-management` plugin

**Comment by wilkinsona** [comment]
I'm not in favour of adding Spring Java Format. It feels too niche to me.

**Comment by snicoll** [comment]
Thanks for confirming Andy.
