### ISSUE TITLE
cloud-contract-verifier[Contract Verifier] + cloud-function[Function]: produces broken pom

### ISSUE THREAD

**Issue by kdvolder** [spring-io/start.spring.io#326]
This seems to be only a problem on `start-staging.spring.io` but not `start.spring.io`. I tried both this morning after seeing this test failure:

https://build.spring.io/browse/IDE-CONTINUOUSTESTING-JOB1-2683/test/case/289979021

**Comment by kdvolder** [comment]
Note: `cloud-function[Function] + web[Spring Web]` is also still a problem though the breakage seems different from the problem that I reported yesterday. The error is different than it was yesterday.

I can raise separate issues for these if you want, but our build seems to be experiencing problems with all 4 of these combinations, I am unsure if they are all caused by the same problem, or not.

```
cloud-function[Function] + web[Spring Web]: AssertionFailedError: Project creation failed
cloud-function[Function] + webflux[Spring Reactive Web]: AssertionFailedError: Project creation failed
cloud-contract-verifier[Contract Verifier] + cloud-function[Function]: AssertionFailedError: Project creation failed
cloud-contract-verifier[Contract Verifier] + session[Spring Session]: AssertionFailedError: Project creation failed
```

**Comment by snicoll** [comment]
staging is not updated as often as production as we use it to test new features before it hits production. I've refreshed staging so that should hopefully fix the problem the way I understood it. 

You may want to reconsider your test arrangement as relying on an external service you have no control over isn't great. Build/start the project from source is one option. We might also provide other options to start an instance in the near future (i.e. container image).

**Comment by kdvolder** [comment]
> staging is not updated as often as production as we use it to test new features before it hits production.

I would think this means it is in fact updated more often?

> You may want to reconsider your test arrangement

All things considered, I am happy with the current setup. I really don't need another snowflake deployment / build / setup to worry about and manage. 

And perhaps our tests running against your deployment may help catch the occasional bug in start.spring.io before it is deployed. That is an added bonus.

I don't mind raising an occasional ticket when I see an issue. It is a great trade-off for me not having to make sure we are running a recent / relevant version of the service ourselves somewhere.
