### ISSUE TITLE
Staging is not up-to-date with production

### ISSUE THREAD

**Issue by kdvolder** [spring-io/start.spring.io#329]
Similar to issue from a few days ago: https://github.com/spring-io/start.spring.io/issues/324

The error is different though so I assume it is actually a different problem / cause.

The pom produced looks like this:

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.2.1.RELEASE</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
	<groupId>com.example</groupId>
	<artifactId>boxinday</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>boxinday</name>
	<description>Demo project for Spring Boot</description>

	<properties>
		<java.version>1.8</java.version>
		<spring-cloud.version>Hoxton.RC1</spring-cloud.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-function-web</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
			<exclusions>
				<exclusion>
					<groupId>org.junit.vintage</groupId>
					<artifactId>junit-vintage-engine</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
	</dependencies>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-dependencies</artifactId>
				<version>${spring-cloud.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

</project>
```

Building the project on the CLI produces this:

```
$ ./mvnw clean package
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Non-resolvable import POM: Failure to find org.springframework.cloud:spring-cloud-dependencies:pom:Hoxton.RC1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced @ line 47, column 16
[ERROR] 'dependencies.dependency.version' for org.springframework.cloud:spring-cloud-function-web:jar is missing. @ line 27, column 15
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project com.example:boxinday:0.0.1-SNAPSHOT (/tmp/test-sts-ws/boxinday/pom.xml) has 2 errors
[ERROR]     Non-resolvable import POM: Failure to find org.springframework.cloud:spring-cloud-dependencies:pom:Hoxton.RC1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced @ line 47, column 16 -> [Help 2]
[ERROR]     'dependencies.dependency.version' for org.springframework.cloud:spring-cloud-function-web:jar is missing. @ line 27, column 15
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
```

**Comment by snicoll** [comment]
Thanks for the report. I’ve just tried and I don’t get that pom. The milestones repository is included and the project works for me. Can you describe how you generated this faulty project?

**Comment by kdvolder** [comment]
Sorry, actually on closer inspection, I guess it does look like the same error after all. The error did look different to me on friday. But the error I got today is again the same as it was in issue #321 

Anyhow it seems like https://github.com/spring-io/start.spring.io/issues/329 is not fixed yet on `start-staging.cfapps.io`.

**Comment by kdvolder** [comment]
> Can you describe how you generated this faulty project?

I used STS 4 'start.spring.io' wizard put pointing it at 'start-staging'. I leave all settings at default values except for adding the dependencies 'Function' and 'Web'.

**Comment by kdvolder** [comment]
Our wizard produces this url for the zip it downloads:

```
https://start-staging.cfapps.io/starter.zip?name=boxinday&groupId=com.example&artifactId=boxinday&version=0.0.1-SNAPSHOT&description=Demo+project+for+Spring+Boot&packageName=com.example.demo&type=maven-project&packaging=jar&javaVersion=1.8&language=java&bootVersion=2.2.1.RELEASE&dependencies=cloud-function&dependencies=web
```

When I download and import that zip to STS manually it has the error.

STS doing something wrong/strange/unusual to create the download url maybe?

**Comment by snicoll** [comment]
No, staging isn't simply in par with production (as I've indicated previously, see https://github.com/spring-io/start.spring.io/issues/326#issuecomment-552079631). I'd like to get some feedback from the team on this usage and how we can avoid this situation going forward.

**Comment by wilkinsona** [comment]
IMO, given how we use our staging environment as a place for prototyping and experimentation, it doesn't make sense for STS to be using it for testing. There's no guarantee that something that works or doesn't work in staging will or won't work in the production environment. I think it would be better to test against start.spring.io. IMO, it'd be even better still to use a mocked service for testing purposes.

**Comment by kdvolder** [comment]
> I think it would be better to test against start.spring.io.

That would be fine by me but Stephane has made it clear in the past he doesn't want this for it polutes the usage statistics.

> use a mocked service

Not sure what you mean exactly, but our tests require a 'real' service that produces 'real' projects that can be imported into Eclipse and compile.

I'm really reluctant to start managing our own instance of the service.

**Comment by snicoll** [comment]
We've discussed this one at our last meeting and we think it is not our responsibility to provide an instance of start.spring.io to the tooling team. In particular staging or dev can be out of sync or even not available at all. 

While we generally agree it’s ok to have a couple smoke tests to validate that the workflow works as expected, most tests should use mock objects. If the tooling team does not go in that direction, they’ll have to setup their own instance for that purpose. Our CI pipeline shows how the project is built (and deployed) so those bits can be reused if necessary.

**Comment by kdvolder** [comment]
> we think it is not our responsibility to provide an instance of start.spring.io

Fair enough. I understand that. But we are really only using the staging environment because you asked us to do this in the past. It is in fact more logical and easier for us to to just use the production instance.

It is after all precisely that instance that we really care about and want to ensure things are working properly with.

> While we generally agree it’s ok to have a couple smoke tests to validate that the workflow works as expected

Very well, we'll switch our tests back to use the production environment for the time being then. I'll discuss with our team if / how / when we want to setup our own instance.

> While we generally agree it’s ok to have a couple smoke tests to validate that the workflow works as expected, **most tests should use mock objects**

Sorry but that is just not possible. As I stated already the tests require that the service produces a real project.

**Comment by kdvolder** [comment]
Given the objections @snicoll raised against my switching back to using production instance.

I've setup a pipeline to deploy and build from master branch of start.spring.io. I did have to add `-Dmaven.test.skip=true` or the test-build seemed to just hang otherwise (see: https://ci.spring.io/teams/tools/pipelines/sts-start-spring-io/jobs/build-and-push/builds/11). Maybe that is something you might want to look into. 

Question. Is master the right branch to monitor / build? If not which branch would correspond more closely to what is actually deployed at 'start.spring.io'?
