### ISSUE TITLE
start.spring.io doesn't add dependencies

### ISSUE THREAD

**Issue by jakubnabrdalik** [spring-io/start.spring.io#337]
As of today (21.11.2019) start.spring.io doesn't add any dependencies I check on the GUI and instead always provides

```
dependencies {
  implementation 'org.springframework.boot:spring-boot-starter'
  implementation 'org.codehaus.groovy:groovy'
  testImplementation('org.springframework.boot:spring-boot-starter-test') {
    exclude group: 'org.junit.vintage', module: 'junit-vintage-engine'
  }
}
```

It takes other options into consideration though (java vs kotlin vs groovy, jdk version, maven/gradle).

**Comment by snicoll** [comment]
@jakubnabrdalik thank you very much for reporting it. This is an unfortunate regression of an infrastructure change of the WebUI. The problem only affects the WebUI and generation via the IDE and the command line still works as expected.

There is a CI job running to revert to the previous infrastructure until we figure out what happened. I'll keep this one open until the job completes and I've validated things work as expected again on start.spring.io.

**Comment by JaysonH91** [comment]
I'm getting the same issue as well

**Comment by snicoll** [comment]
@jakubnabrdalik the Web UI should work as expected. Thanks again for reporting it and feel free to comment here if you're still experiencing an issue.
