### ISSUE TITLE
gatsby-plugin-prefetch-google-fonts build failure

### ISSUE THREAD

**Issue by kdvolder** [spring-io/start.spring.io#348]
See https://ci.spring.io/teams/tools/pipelines/sts-start-spring-io/jobs/build-and-push/builds/25

Not sure what the problem is, but I figure you'd probably want to know there is a problem building master? Or maybe you already know, in which case, feel free to simply close and ignore this ticket.

**Comment by snicoll** [comment]
Yes, we are aware of the problem. Thanks, we can reuse this issue to track it.

**Comment by snicoll** [comment]
Closing in favour of PR #349
