### ISSUE TITLE
Indicate that Netflix entries are in maintenance mode

### ISSUE THREAD

**Issue by mbhave** [spring-io/start.spring.io#357]
We currently have multiple implementations for cloud circuit breaker and load balancer. We should guide users in the right direction by adding `[Maintenance]` on the Hystrix and Ribbon checkboxes. See [this comment](https://github.com/spring-io/start.spring.io/issues/319#issuecomment-560517649) for more background.

**Comment by snicoll** [comment]
There are a few others. For consistency with [what we write in HELP.md](https://github.com/spring-io/start.spring.io/blob/61026d723a9bfe925de98aacccbf0e1f28a659da/start-site/src/main/java/io/spring/start/site/extension/dependency/springcloud/SpringCloudNetflixMaintenanceModeHelpDocumentCustomizer.java#L42-L43) we should flag those too.

**Comment by snicoll** [comment]
That broke the help.md generation as " [Maintenance]" is added to the description of each affected dependency
