### ISSUE TITLE
Add reactor-kotlin-extensions to dependencies when creating a Kotlin + Webflux application

### ISSUE THREAD

**Issue by hantsy** [spring-io/start.spring.io#365]
I was trying to upgrade [my sample](https://github.com/hantsy/spring-kotlin-coroutines-sample) to the following newest stack:

* Spring 2.2.2.RELEASE
* Java 11
* Kotlin/Webflux

When I tried to refresh the APIs according to the changes in the new dependencies and  found 

`WebClient....exchange().test()` is marked as **deprecated**, and the new *reactor.kotlin.test* is from `reactor-kotlin-extensions`.

I think it should be added into dependencies when creating a Kotlin based Webflux app, because all Kotlin extensions for Reactor is moved to this archetype.

```xml
<!-- https://mvnrepository.com/artifact/io.projectreactor.kotlin/reactor-kotlin-extensions -->
<dependency>
          <groupId>io.projectreactor.kotlin</groupId>
          <artifactId>reactor-kotlin-extensions</artifactId>
          <version>1.0.1.RELEASE</version>
</dependency>
```

**Comment by snicoll** [comment]
Closing in favour of PR #391
