### ISSUE TITLE
Upgrade to Azure Spring 2.0.8

### ISSUE THREAD

**Issue by tedyoung** [spring-io/start.spring.io#37]
I just generated a Spring Boot 2.1.1 project with the Azure starter in Maven. However, the version for the Azure starter that was used was 2.0.5 (via the `azure.version` property):

```
<azure.version>2.0.5</azure.version>
```

However, the correct version should be 2.1.0 (and soon 2.1.1). And it looks like for Spring Boot 2.0, the latest Azure version is 2.0.8.

How do Azure folks, et al, communicate their new releases?

**Comment by snicoll** [comment]
Thanks for the report.
> How do Azure folks, et al, communicate their new releases?

They pushed PRs or create an issue in this repo (I've just moved your issue). I have no idea why they didn't do it.

paging @ZhijunZhao @sophiaso @yungez @aovechki @selvasingh @Matthew-Dong @yaweiw

**Comment by snicoll** [comment]
I won't upgrade to 2.1.0 for now, I've filled https://github.com/Microsoft/azure-spring-boot/issues/534
