### ISSUE TITLE
Maven projects are not including the packaging in the pom.xml file

### ISSUE THREAD

**Issue by DavidSoles** [spring-io/start.spring.io#376]
I've generated a couple of Spring Boot maven projects and none of them includes the packaging (Jar, War) in the pom.xml file. I don't know if this is by design or is a bug.

**Comment by snicoll** [comment]
The default packaging is `jar` so it makes sense not to add it. 

> I've generated a couple of Spring Boot maven projects and none of them includes the packaging (Jar, War) in the pom.xml file. 

I've just created a Maven project with `war` packaging and the following was added to the pom:

```xml
<packaging>war</packaging>
```

Can you please describe how I can reproduce the problem you've described? Thank you

**Comment by DavidSoles** [comment]
I'm not sure if it's really a bug but suddenly stop seeing the packaging line in the pom file generated from start.spring.io. I guess if `jar` is the default packaging method there is no problem then. I was used to see it as part of the file.
