### ISSUE TITLE
Unusual quote in "Spring Configuration Processor" description

### ISSUE THREAD

**Issue by AlexFalappa** [spring-io/start.spring.io#377]
The _Spring Configuration Processor_ dependency description contains left/right quotation marks characters. It seems they are not properly encoded in the JSON responses sent back by the service.

I should have ruled out encoding problems on my end thus I am opening this to kindly ask a check on server side. Are description strings encoded in UTF-8?

The problematic snippet is: ... offer contextual help and **“code completion”** when working with ...
“-”

**Comment by snicoll** [comment]
> It seems they are not properly encoded in the JSON responses sent back by the service.

I see the character is unusual but it looks legit in the json output to me so I don't think we should do anything here. I'll update the character though, thanks for the report!

**Comment by AlexFalappa** [comment]
Wow, that was quick!

Thanks @snicoll
