### ISSUE TITLE
Cannot find AOP starter in dependencies

### ISSUE THREAD

**Issue by AndreasVolkmann** [spring-io/start.spring.io#388]
I was trying to add the aop starter to my project, but couldn't find it in the dependencies on https://start.spring.io/. Also searched for aspect. 

It would be great to be able to add it to the project from the website instead of manually adding `implementation("org.springframework.boot:spring-boot-starter-aop")`.

**Comment by snicoll** [comment]
Thanks for the suggestion. This is a duplicate of #180.
