### ISSUE TITLE
Choice between tabs, spaces, and indentation?

### ISSUE THREAD

**Issue by sdoxsee** [spring-io/start.spring.io#392]
Would it be possible to choose spaces (and maybe indentation) instead of tabs when generating the application? Possibly a toggle between tabs/spaces and a defaulted dropdown for indentation characters.

**Comment by snicoll** [comment]
Thanks for the suggestion. FTR, request for start.spring.io should be created on the dedicated GitHub project, I've just moved the issue there.

We've discussed this in the past several times although I can't find an issue where the discussion is referenced. If you generate the project from your IDE, it should be easy to reformat the code against your preferences (IntelliJ IDEA has an option to do that automatically). I am not keen to add an option for such formatting preferences as there are many more options that users would like to customize and we want the project creation workflow to be as direct as possible. Thanks anyway.

**Comment by sdoxsee** [comment]
Sounds reasonable. Thanks!
