### ISSUE TITLE
Option for Creating a Spring Library

### ISSUE THREAD

**Issue by apinshrewon** [spring-io/start.spring.io#417]
Present options provide to create a Spring Applicaation. It would be nice, if we can add options for Spring Library.

**Comment by snicoll** [comment]
@apinshrewon thanks for the suggestion. What does that mean in practice?

**Comment by apinshrewon** [comment]
A quick start for creating a Spring Library for usage. Also, a standards for a Spring Library.

**Comment by snicoll** [comment]
Sorry I don't understand what that means. Perhaps you could share a  concrete example of what you mean?

**Comment by apinshrewon** [comment]
Presently, any one visiting https://start.spring.io/ can create a spring application.

Similarly, if any one wants to create a Spring based library (for business purpose. eg. any organization would like to create a commons [spring based] library for dependency in other spring based applications).

For that, you could add an option in UI, Purpose : [] Application [] Library.

May I know is it understandable, now!

**Comment by snicoll** [comment]
> May I know is it understandable, now!

We still need to guess but you probably mean that the repackage goal isn't involved and the bom is imported in a way that you can have a custom parent (or not parent at all). We've discussed that today and we're not keen to offer such an option. Thanks for the suggestion anyway.
