### ISSUE TITLE
When I generate the zip file with (Ctrl+Enter)

### ISSUE THREAD

**Issue by alisonjs** [spring-io/start.spring.io#421]
The zip is generate normally, but in the screen appears the following error:

![image](https://user-images.githubusercontent.com/8595464/78183731-c6c7d200-743e-11ea-8907-51cf589f2922.png)

**Comment by KevinBlandy** [comment]
This is just a fools day joke。

**Comment by snicoll** [comment]
This was a joke indeed @alisonjs and it only applied on April 1st. You should be fine now.
