### ISSUE TITLE
Upgrade to Oracle JDBC 19.6.0.0 (and groupId)

### ISSUE THREAD

**Issue by aalmiray** [spring-io/start.spring.io#430]
The latest version of the Oracle JDBC drivers is `19.6.0.0`.
The groupId was updated in Feb 21st 2020 to `com.oracle.database.jdbc`.

**Comment by snicoll** [comment]
Thanks but this project has no opinion whatsoever on that.

Duplicate of https://github.com/spring-projects/spring-boot/issues/20333

**Comment by snicoll** [comment]
@wilkinsona also reminded me that we have an explicit mapping for the driver which is an oversight since Spring Boot is providing dependency management for it. I've created #431
