### ISSUE TITLE
Fix metadata for "spring-cloud-starter-consul-config"

### ISSUE THREAD

**Issue by snicoll** [spring-io/start.spring.io#433]
It looks like it's a proper starter in a recent version now.

**Comment by snicoll** [comment]
Turns out wha was fixed a few weeks ago had to be reverted. I didn't find what was changed in that project but this isn't a proper starter anymore.

**Comment by spencergibb** [comment]
what happened a few weeks ago?

**Comment by snicoll** [comment]
I have no idea. Something forced me to change the metadata because this starter changed the dependencies that it brings. And I had to revert that today. I've looked in the history of this repo to try to figure it out and gave up.

**Comment by snicoll** [comment]
Our validation tests (checking that all entries alone are configured to bring at least spring-boot-starter) were fixed by this change https://github.com/spring-io/start.spring.io/commit/420c284bf829104798029a0040921614b47fc2ae. What that means is that a recent (snapshot) spring cloud version started to bring `spring-boot-starter` for that entry. That stopped 3 days ago when our build started failing the other way around.

**Comment by spencergibb** [comment]
those poms for spring cloud consul haven't changed much in more than a year. I don't see anything that triggers something new three days ago.   :shrug: Anyway, it's been updated.

**Comment by snicoll** [comment]
A dependency of this project may have started bringing a starter. I definitely saw it was bringing `spring-boot-starter` transitively while it wasn't previously. 

Thanks for the quick turnaround. We'll have to update the metadata again following that change, both for the snapshot and the release once `SR5` is out.
