### ISSUE TITLE
Expose WebUI on a configurable context path

### ISSUE THREAD

**Issue by haydonchou** [spring-io/start.spring.io#434]
start-site configuration  server.servlet.context-path=/initializr。
Browser visit http://localhost:8080/initializr  ，static resource loading failed。
Can support custom context？Thanks！

**Comment by snicoll** [comment]
@haydonchou thanks for the report. The web UI is primarily for our own purpose and is not part of a library. As such, you should not expect the same level of flexibility (and API) than what you're used to from a library. We don't have a need to expose the site in a context so we haven't built that feature.

**Comment by haydonchou** [comment]
@snicoll  Ok i got it.Thanks！
