### ISSUE TITLE
Upgrade to Solace Spring Boot 1.1.0

### ISSUE THREAD

**Issue by Mrc0113** [spring-io/start.spring.io#445]
The `solace-spring-boot-starter` has been updated. This include compatibility with Spring Boot v2.3.0.RELEASE. More release info here: https://github.com/SolaceProducts/solace-spring-boot/releases/tag/1.1.0

Maven Central: https://mvnrepository.com/artifact/com.solace.spring.boot/solace-spring-boot-starter/1.1.0

**Comment by Mrc0113** [comment]
Thanks for alerting us of this @snicoll 👍

**Comment by snicoll** [comment]
@Mrc0113 thanks for the release. Let me know when `solace-spring-cloud` catches up and we'll enable the Spring Cloud Stream binder on 2.3 as well!
