### ISSUE TITLE
If "Generate" hits an error the FileSaver is still called

### ISSUE THREAD

**Issue by dsyer** [spring-io/start.spring.io#451]
If there's an error on "Generate" you get the expected popup error message, but you also get an ugly log in the console:

```
FileSaver.min.js:1 Uncaught (in promise) TypeError: Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided.
    at Function.a [as saveAs] (FileSaver.min.js:1)
    at Application.js:77
...
```

I think that's probably because the `onSubmit` catches the error, processes it, but doesn't prevent the call to `FileSaver`.

**Comment by oodamien** [comment]
See https://github.com/spring-io/start.spring.io/commit/c425ac3a3ea9607c5bf94933576e0bf67e4badbb
