### ISSUE TITLE
Absolute URL links to JS files

### ISSUE THREAD

**Issue by BoykoAlex** [spring-io/start.spring.io#456]
The `index.html` has absolute path links:

![image (1)](https://user-images.githubusercontent.com/6433390/83474921-32d4af80-a45b-11ea-9c23-30a408be327e.png)

It is best to replace them with relative links for hosting Initilizr via a proxy in k8s cluster

**Comment by snicoll** [comment]
@BoykoAlex thanks for the suggestions. FTR, if you intend to submit a PR there is no need to create an issue as one supersedes the other.
