### ISSUE TITLE
I want to add the project to spring-io

### ISSUE THREAD

**Issue by ThierrySquirrel** [spring-io/start.spring.io#459]
## Code of Conduct
I follow the code of conduct

## Well-established project with a vibrant community
It's a complete project

Address of the project: https://github.com/ThierrySquirrel/rocketmq-spring-boot-starter

## Ongoing maintenance
The springboot used is the latest version and remains updated

## Licence
 Licence  Apache-2.0

## Issue Tracker URL
https://github.com/ThierrySquirrel/rocketmq-spring-boot-starter/issues

## Continuous integration
I don't quite understand this part. Can you help me?

## Maven Central
Project already exists in Maven central warehouse

## Configuration metadata
It has automatic configuration
`@ConfigurationProperties` 

## Version mappings
For example, do you need a snapshot version?

## Links to additional resources
This is my project address: https://github.com/ThierrySquirrel/rocketmq-spring-boot-starter

My English is poor. It's my pleasure to join you.

**Comment by wilkinsona** [comment]
Thanks for the proposal. At the moment, I think your starter is better-suited to being listed in [Spring Boot's README](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-starters/README.adoc) that contains a table of third-party starters. Once it has become a bit more established and has a wide range of users and contributors, we could then consider it for inclusion on start.spring.io.

Please feel free to open a Spring Boot pull request that updates the table of third-party starters to include yours.
