### ISSUE TITLE
Default to Java 11

### ISSUE THREAD

**Issue by gtiwari333** [spring-io/start.spring.io#462]
I have seen lot of cases where developers(students and professionals both) are unknowingly using JDK 8 in their Spring Boot apps because it's the default option.

I believe we need to encourage people to use the latest stable version. If someone must use older version they should be able to choose from the options.

**Comment by snicoll** [comment]
Thanks for the suggestion. I've moved it to the appropriate issue tracker.

**Comment by snicoll** [comment]
We've discussed this one at our team meeting today and agreed it's time to move the default to Java 11.

**Comment by snicoll** [comment]
Blocked by #484
