### ISSUE TITLE
Validation selection should include "hibernate-validator-annotation-processor"

### ISSUE THREAD

**Issue by candrews** [spring-io/start.spring.io#465]
When the "Validation" option is selected, it currently only adds a dependency on `spring-boot-starter-validation`. It would be a nice improvement to also add a dependency on "org.hibernate.validator:hibernate-validator-annotation-processor"

For Gradle:
`annotationProcessor 'org.hibernate.validator:hibernate-validator-annotation-processor'`

For Maven:
```
<dependency>
  <groupId>org.hibernate</groupId>
  <artifactId>hibernate-validator-annotation-processor</artifactId>
</dependency>
```
"org.hibernate.validator:hibernate-validator-annotation-processor" is really helpful:
> Have you ever put a constraint annotation to an unsupported location and wished to find out about that at build time rather than at runtime? Then the Hibernate Validator Annotation Processor is the right thing for you.
>
> It helps to detect glitches such as:
>
>    * Putting a constraint to bean properties which are not supported by that constraint (e.g. putting `@Date` to a String)
>    * Annotating the setter of a bean property instead of the getter
>    * Adding constraints to static fields or methods
> When detecting these and other unsupported constraint usages, the Hibernate Validator Annotation Processor will raise an error at build time, saving you valuable time.

--- https://hibernate.org/validator/tooling/

**Comment by candrews** [comment]
> Thanks for the suggestion but that use case isn't common enough to warrant us to do this automatically.

The use case is that anyone who uses the JSR-303 and/or Hibernator Validator annotations would get compile time checking that the annotations are used appropriately. Everyone who selects the "Validation" option would benefit which seems very common.

I'm curious - who wouldn't benefit? In what way wouldn't this benefit be common?

Thank you in advance!

**Comment by snicoll** [comment]
I didn't write it wouldn't be useful or benefit anyone. I wrote that adding an annotation processor to validate your code every time you compile should be opt-in IMO.

If this way of working with hibernate validator becomes popular, other members in the community will request a similar feature and we can of course reconsider.
