### ISSUE TITLE
Add documentation and example links in README file when generating project

### ISSUE THREAD

**Issue by maheshwarLigade** [spring-io/start.spring.io#487]
Add spring boot or spring framework documentation and example link in README.md file when someone generates the project using start.spring.io

We should add documentation specific link let us say when someone adds the dependency of spring-starter for web, couchbase, and Kafka, so we should add spring documentation link for the starter which are included here and if some examples GitHub link if we have already in place from spring community. 
e.g 
https://spring.io/projects/spring-kafka
https://spring.io/projects/spring-boot
https://spring.io/projects/spring-data-couchbase

As stated above when anyone creates a project using spring initializer we know that what dependencies added by end-user and what kind of project user wants to create so based on that we can create README.md file and in that we will add sample example and documentation link so end-user will get info handy. This will definitely add value to the developer.

**Comment by snicoll** [comment]
@maheshwarLigade this template is used when requesting the addition of new entries on `start.spring.io`. I can see some comments from you in the middle. Can you please edit your description to remove the template and describe your suggestion?

**Comment by maheshwarLigade** [comment]
@snicoll  Thank you for your quick reply. I am new one in open source contribution.  updated my comment

**Comment by snicoll** [comment]
> As stated above when anyone creates a project using spring initializer we know that what dependencies added by end-user and what kind of project user wants to create so based on that we can create README.md file and in that we will add sample example and documentation link so end-user will get info handy. This will definitely add value to the developer.

I am confused. We already do that and we generate an `HELP.md` with such information. Can you please clarify the scope of this issue? Is this about adding more links? If so, we can have a general pass but if you've found specific entries listing them would be most welcome.

**Comment by maheshwarLigade** [comment]
My bad we have already in HELP.md file. this is due to the I am used to with the README.md file and never look into the HELP.md file. 
@snicoll  Thank you so much.
