### ISSUE TITLE
Add an option to generate java module-info.java file

### ISSUE THREAD

**Issue by hantsy** [spring-io/start.spring.io#489]
Currently, most of the open-sourced projects required in Spring supports Java 9 Java Module System. If possible to add a checkbox option for developers to determine if using Java Module when selecting Java 11 or above.

**Comment by snicoll** [comment]
Thanks for the suggestion but generating a module-info is something that should be determined by the maintainer of the module and all IDEs have great support for that. We can't reliably determine upfront an initial structure for the file either.

We also try to limit as much as possible options to keep the creating workflow as simple as possible.
