### ISSUE TITLE
suggest: build.gradle indent using space instead of tab

### ISSUE THREAD

**Issue by sinkcup** [spring-io/start.spring.io#505]
choose Gradle on https://start.spring.io/

It will generate `build.gradle`, the indent is tab.

suggest: use space not tab

**Comment by wilkinsona** [comment]
Thanks for the suggestion, but if we switch to spaces we'd then see those that prefer tabs asking to switch back. We've also [considered offering a setting](https://github.com/spring-io/start.spring.io/issues/392) but prefer not to complicate the configuration settings. We believe that the best option is to use your IDE or text editor to reformat the generated project if it doesn't match your style.

**Comment by sinkcup** [comment]
@wilkinsona but all the other codes generated by Spring Initializr  is using space now, only the `build.gradle` is using tab, why?
maybe they should be the same.

**Comment by snicoll** [comment]
> but all the other codes generated by Spring Initializr is using space now, only the build.gradle is using tab

I don't this that's accurate. A project generated from https://start.spring.io uses tab for both the code and the build.

> why?

I suspect you're already using the suggestion Andy made. If you're generating the project from your IDE, it could reformat the code according to your preference. If it does so for the source code but not the build, you may want to ask them to consider reformatting build files as well.
