### ISSUE TITLE
Restore parallel execution of integration tests

### ISSUE THREAD

**Issue by snicoll** [spring-io/start.spring.io#51]
We can't run them in parallel at the moment as there is a concurrent request to download the wrapper and that leads to corrupted zip file.

There might be a way to prepare the right wrapper version so that they aren't downloaded on CI.

**Comment by wilkinsona** [comment]
It's not just the wrapper that's problematic, but Maven's local repository too. We can run the tests in parallel if we configure Maven with a thread-specific locations for the wrapper download and for the local repository.
