### ISSUE TITLE
Invalid POM when "Description" contains an ampersand (&)

### ISSUE THREAD

**Issue by steveschnepp** [spring-io/start.spring.io#517]
If you
1. go to https://start.spring.io 
1. choose `Maven Project`
1. enter `Demo project for Spring Boot & Others` in the _Description_ field

The generated POM is invalid XML, as it contains an unescaped ampersand.

    <description> Demo project for Spring Boot & Others </description>

The correct way would be:

    <description> Demo project for Spring Boot &amp; Others </description>

**Comment by snicoll** [comment]
Thank you for the report.  This is a duplicate of https://github.com/spring-io/initializr/issues/1066.
