### ISSUE TITLE
start.spring.io site does not render (blank page)

### ISSUE THREAD

**Issue by JSosaRDZ** [spring-io/start.spring.io#519]
I haven't been able to load start.spring.io on Edge. I'm able to load the page on Safari. I'm on a MacBook Pro 2018, running on Catalina.

I Get the following errors on the console:  Failed to load resource: the server responded with a status of 404 ()... main-f77c14a….js:1

I was getting a SameSite cookie warning, but that's not showing up anymore.

I tried to delete my cookies, delete my history, add site to trusted list, disable all browser security, and reinstalling Edge, but nothing worked. Please, advice.

**Comment by snicoll** [comment]
We are aware of a production issue where resources are too aggressively cached. Usually a hard refresh of the page fixes it (CTRL-R I guess). Can you please try that?

**Comment by JSosaRDZ** [comment]
I cleared all data from the settings. That worked.

Hard refresh didn't seem to work, though.

Thank you!

On Aug 17, 2020 7:22 AM, Stéphane Nicoll <notifications@github.com> wrote:

We are aware of a production issue where resources are too aggressively cached. Usually a hard refresh of the page fixes it (CTRL-R I guess). Can you please try that?

**Comment by snicoll** [comment]
Alright, thanks for letting us know.

There has been a number of similar reports so let's keep this one open until we figure out why the HTML is outdated when we redeploy the app.

**Comment by bclozel** [comment]
Just had the problem again in production and finally found the issue.

The `index.html` page is served as a static resource by the application.
When running the application locally, the HTTP response contains the following response header:

> Last-Modified: [BUILD DATE FOR THE CLIENT APP] GMT

This is a bit strange in the first place to send such a header for an HTML page and we probably shouldn't do that.

When running the application in production (no CDN involved), we're getting the following response header:

> Last-Modified: Tue, 01 Jan 1980 00:00:01 GMT

I assume that the image building process is changing the metadata for the static resources for reproducability / image layer optimization.

I guess there are two points here:

1. avoid sending that header for the main HTML page
2. considering whether we should reset the metadata for static resources when building the container image, as it's generally useful information and Spring Framework is looking at that information for static resource handling.
