### ISSUE TITLE
Upgrade to Azure spring 2.3.3

### ISSUE THREAD

**Issue by yiliuTo** [spring-io/start.spring.io#524]
The azure-spring-boot-bom of version 2.3.3 has been release to Maven: https://repo1.maven.org/maven2/com/microsoft/azure/azure-spring-boot-bom/2.3.3/
Please help to upgrade the version of bom to the latest.
Thanks

**Comment by yiliuTo** [comment]
Hi @snicoll, could you help to take a look of this upgrade issue?

**Comment by snicoll** [comment]
Hi @yiliuTo, there is no need to mention me, the whole team already received a notification when the issue was created.

**Comment by yiliuTo** [comment]
> Hi @yiliuTo, there is no need to mention me, the whole team already received a notification when the issue was created.

**Comment by yiliuTo** [comment]
> Hi @yiliuTo, there is no need to mention me, the whole team already received a notification when the issue was created.

OK, thanks

**Comment by yiliuTo** [comment]
Hi @snicoll thanks for the PR, I saw it merged but when I checked the Spring initializr, I selected spring boot 2.3.3 and added Azure Active Directory as a dependency, then the `azure.version` in `pom.xml` is still 2.3.1, shouldn't it be 2.3.3?

![image](https://user-images.githubusercontent.com/63028776/91115050-e72d4d00-e6bb-11ea-9657-e13cdff0bc10.png)

**Comment by snicoll** [comment]
Thanks for letting us know. Our CI had some issues yesterday and didn't deploy the latest version. We're investigating.

**Comment by snicoll** [comment]
@yiliuTo it's live now. Sorry for the delay.

**Comment by yiliuTo** [comment]
@snicoll  Thanks !
