### ISSUE TITLE
Upgrade to Azure Spring 2.3.5

### ISSUE THREAD

**Issue by zhoufenqin** [spring-io/start.spring.io#534]
Hi,
The azure-spring-boot-bom of version 2.3.5 has been release to Maven: https://repo1.maven.org/maven2/com/microsoft/azure/azure-spring-boot-bom/2.3.5/
Please help to upgrade the version of bom to the latest, thanks.

Another problem:
The bom has this dependency before:
```
name: Azure Storage
id: azure-storage
groupId: com.microsoft.azure
artifactId: azure-storage-spring-boot-starter
```
But now we update the artifactId. Current storage dependency is
```
name: Azure Storage
id: azure-storage
groupId: com.microsoft.azure
artifactId:spring-starter-azure-storage
```
The `com.microsoft.azure:spring-starter-azure-storage` supports Spring Boot 2.3.x, so could you support that providing different storage library when user choose the different Spring Boot version?

Thanks

**Comment by snicoll** [comment]
Thanks for following up on the release! 

> spring-starter-azure-storage

@zhoufenqin I find changing the artifactId of a starter in a maintenance release a bit odd. What is the rationale for changing the name this way? This is not [compliant with how third party starter should be named](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-custom-starter-naming).

**Comment by jialindai** [comment]
Hi @snicoll , we are considering to change the naming convention of azure Spring starters to following convention:

azure-spring-boot-starter-<service>[-<feature>]

Where <service> is the corresponding azure service, <feature> is one feature of this azure service.

Hope this is OK from Spring framework perspective?

**Comment by jialindai** [comment]
@snicoll , we are planning to change the artifact ids as:

azure-active-directory-spring-boot-starter  =>  azure-spring-boot-starter-active-directory
azure-keyvault-secrets-spring-boot-starter  =>  azure-spring-boot-starter-keyvault-secrets

The storage starter's current artifact id is spring-starter-azure-storage, and its id will be changed to azure-spring-boot-starter-storage.

I think for now, we can just increase the azure-spring-boot-bom version to 2.3.5.

After we change the artifact id (and increase the major version number), we will need your help to update and include the storage starter.

**Comment by snicoll** [comment]
> azure-spring-boot-starter-[-]

That sounds good to me. A simple prefix and then the suffix used to qualify sounds like a good approach.

> I think for now, we can just increase the azure-spring-boot-bom version to 2.3.5.

Isn't that going to break users though? You mentioned that the artifactId for storage was renamed there (something I still don't understand btw). Can you please bring back the artifactId as it was and release `2.3.6`? As I've mentioned, we can't promote something that doesn't comply with our naming conventions.

**Comment by zhoufenqin** [comment]
Hi @snicoll, because of some of our internal rule, in next spring boot release version, all the azure spring boot starter library will be renamed, as Jialin said:
azure-active-directory-spring-boot-starter => azure-spring-boot-starter-active-directory
azure-keyvault-secrets-spring-boot-starter => azure-spring-boot-starter-keyvault-secrets

The spring boot storage artifactId will be updated again in the next release version.
Because we have already released the azure spring boot starter 2.3.5 version, in Spring Initializer,  can we just increase the azure-spring-boot-bom version to 2.3.5, except azure spring boot storage library (Keep it as disable as it is now)? 
Thanks

**Comment by zhoufenqin** [comment]
any update?

**Comment by jialindai** [comment]
hi @snicoll, I think we can ignore the spring-starter-azure-storage starter for now.

As 2.3.5 release is already out, on Spring initializer, we would like to make 2.3.5 the version for:
- azure-active-directory-spring-boot-starter
- azure-keyvault-secrets-spring-boot-starter
- azure-spring-boot-starter

Today, no Spring initializer, the 2.3.3 version is still used.
