### ISSUE TITLE
Spring aop dependency not available at Spring Initializr

### ISSUE THREAD

**Issue by MuthiahPrabhakaran** [spring-io/start.spring.io#541]
Hi,
I am trying to generate a project through https://start.spring.io/ and trying to add aop dependency.
If I type AOP or Aspect while adding the dependency, nothing shows up. I can see a lot of duplicate issues on the same topic. But, everything is closed. Not sure, whether it is a bug in latest versions.
I tried with spring boot version 2.2.10 and 2.3.4
Thanks.

**Comment by snicoll** [comment]
>  I can see a lot of duplicate issues on the same topic. But, everything is closed. 

One of those duplicate issue is #180 where we explain why we intentionally removed the entry.

**Comment by MuthiahPrabhakaran** [comment]
Got it. Thanks
