### ISSUE TITLE
Spring Shell dependency is not available 

### ISSUE THREAD

**Issue by Ayushnita** [spring-io/start.spring.io#546]
In the dependencies section, there is no option for Spring Shell related dependencies.

**Comment by snicoll** [comment]
@Ayushnita I am assuming you mean on start.spring.io? This is the wrong issue tracker to report that so I've moved your issue to the appropriate issue tracker.

**Comment by snicoll** [comment]
Not every dependency has to be on start.spring.io. We used to have Spring shell on the site and decided to remove it as his usage was very low and the project has not seen a release in a while. Of course, nothing prevents you to add it to your project once you've created it from start.spring.io.
