### ISSUE TITLE
Add a dependency on spring-restdocs-webtestclient rather than spring-restdocs-mockmvc when using WebFlux or Jersey

### ISSUE THREAD

**Issue by jnizet** [spring-io/start.spring.io#55]
When creating a project with webflux and restdocs, I expect a dependency to `spring-restdocs-webtestclient` to be added to the project. But instead, a dependency to `spring-restdocs-mockmvc` is added.

**Comment by snicoll** [comment]
paging @wilkinsona

**Comment by wilkinsona** [comment]
I agree with the suggestion. It make sense to flip the `spring-restdocs-mockmvc` dependency to a dependency on `spring-restdocs-webtestclient` when the WebFlux starter is being used.
