### ISSUE TITLE
Improvement for Spring Initialzr

### ISSUE THREAD

**Issue by halimpuckjava** [spring-io/start.spring.io#550]
hi

i have 2 suggestions :

1.  with graalvm native image & docker, why not add NATIVE -IMAGE & DOCKER_IMAGE as new packages type with jar & war 
2. add spring native image dependencie as default in spring boot project

**Comment by wilkinsona** [comment]
Thanks for the suggestions.

We deliberately limit the number of packaging types that are offered. This is done to avoid over-complicating the user interface. Furthermore, with the new image building support in Spring Boot running `./gradlew bootBuildImage` (or the Maven equivalent) in a project generated from start.spring.io will produce a Docker image with no additional configuration required.

Native images are a niche at the moment. They're great for certain use cases but have significant drawbacks for others. As such, it wouldn't be appropriate to add native image dependenies by default. As the Spring Graal Native project evolves, we may make some changes on start.spring.io in the future but it's not yet clear what, if anything, those changes should be.

**Comment by sandys** [comment]
@wilkinsona wanted to add my support for creating a dockerfile (not as a separate option...but along with the war or jar output).

AWS ECS, Fargate, AKS, Google Cloud GKE, etc are all container centric. 

Java has not been docker friendly for a long time. Its only in the last year or so has the uptake started - https://www.docker.com/blog/improved-docker-container-integration-with-java-10/

It will be brilliant if you can consider generating Dockerfiles along with the outputs, so that these can be single click deployed anywhere.

**Comment by wilkinsona** [comment]
@sandys Sorry, we still have no plans to automatically generate a Dockerfile. As described above, our recommended approach for creating a container image is to use [Spring Boot's buildpack integration](https://docs.spring.io/spring-boot/docs/2.4.4/reference/htmlsingle/#boot-features-container-images-buildpacks). Running `./gradlew bootBuildImage` or `./mvnw spring-boot:build-image` will create a container image for your application without any further configuration.

**Comment by sandys** [comment]
@wilkinsona understood. 

FWIW Spring Native and Docker solve different problems. One is a JIT ..the other is around deployment infrastructure. I would still like to deploy Spring Native compiled output on AWS/GAE/Azure or any other kubernetes platform using Docker.

**Comment by wilkinsona** [comment]
I'm well aware that they solve different problems. The original description of this issue had a native image focus so my second paragraph above was providing an update on things from a native image perspective. Nothing that I have described above prevents your from deploying a native image on AWS/GAE/Azure or any other Kubernetes platform using Docker. Once you have built the image you can deploy it to any platform that can consume a Docker image.
