### ISSUE TITLE
Define spring-geode-bom for projects generated with 'Spring for Apache Geode'

### ISSUE THREAD

**Issue by jxblum** [spring-io/start.spring.io#565]
**... and generated Gradle build file.**

BACKGROUND

Currently, _Spring Initializer_ at [start.spring.io](https://start.spring.io) only includes the following dependency declaration for the "_Spring for Apache Geode_" dependency (a.k.a. SBDG) in the "_generated_" project Maven POM:

```xml
    <dependency>
      <groupId>org.springframework.geode</groupId>
      <artifactId>spring-geode-starter</artifactId>
      <version>1.4.0-M4</version>
    </dependency>
```

[EXAMPLE](https://start.spring.io/#!type=maven-project&language=java&platformVersion=2.4.0.RC1&packaging=jar&jvmVersion=11&dependencies=geode)

This dependency declaration is insufficient if users, and customers alike, wish to use other features of the SBDG project, such as (HTTP) Session state replication with _Spring Session_ backed by Apache Geode.  In this case, users/customers would also need the `org.springframework.geode:spring-geode-starter-session` dependency; for example:

```xml
    <dependency>
      <groupId>org.springframework.geode</groupId>
      <artifactId>spring-geode-starter-session</artifactId>
      <version>1.4.0-M4</version>
    </dependency>
```

Invariably, users and customers alike start mangling "versions" when they have to declare 2 or more modules in their project Maven POM (or Gradle build) files.

Currently, the SBDG project (under `org.springframework.geode`) includes 5 starter modules: [ [`spring-geode-starter`,](https://github.com/spring-projects/spring-boot-data-geode/tree/master/spring-geode-starter) [`spring-geode-starter-actuator`,](https://github.com/spring-projects/spring-boot-data-geode/tree/master/spring-geode-starter-actuator) [`spring-geode-starter-logging`](https://github.com/spring-projects/spring-boot-data-geode/tree/master/spring-geode-starter-logging), [`spring-geode-starters-session`](https://github.com/spring-projects/spring-boot-data-geode/tree/master/spring-geode-starter-session), [`spring-geode-starter-test`](https://github.com/spring-projects/spring-boot-data-geode/tree/master/spring-geode-starter-test) ].  In the future, there will be a number of new modules added to the SBDG project to handle other application concerns (e.g. distributed compute, streaming, etc).

As for SBDG `1.2`, I introduced a new [`spring-geode-bom`](https://github.com/spring-projects/spring-boot-data-geode/tree/master/spring-geode-bom) dependency to help users effectively manage their SBDG dependencies, depending on their application use case and workflows.

You can see that the `spring-geode-bom` is available in all the "_Spring for Apache Geode_" (i.e. SBDG) versions currently (or that will be) listed on [start.spring.io](https://start.spring.io):

* [`1.2.11.RELEASE`](https://repo1.maven.org/maven2/org/springframework/geode/spring-geode-bom/1.2.11.RELEASE/)
* [`1.3.5.RELEASE`](https://repo1.maven.org/maven2/org/springframework/geode/spring-geode-bom/1.3.5.RELEASE/)
* [`1.4.0-RC1`](https://repo.spring.io/milestone/org/springframework/geode/spring-geode-bom/1.4.0-RC1/)

ASK

Therefore, I'd like to modify the Maven POM (and _Gradle_ build file) "generated" by _Spring Initiallizer_ at [start.spring.io](https://start.spring.io) to appear as follows (in-part):

```xml
<properties>
    <spring-geode.version>1.4.0-RC1</spring-geode.version>
</properties>

<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>org.springframework.geode</groupId>
            <artifactId>spring-geode-bom</artifactId>
            <version>${spring-geode.version}</version>
            <scope>import</scope>
            <type>pom</type>
        </dependency>
    </dependencies>
</dependencyManagement>

<dependencies>
    <dependency>
        <groupId>org.springframework.geode</groupId>
        <artifactId>spring-geode-starter</artifactId>
    </dependency>
</dependencies>
```

Here is an [example of a complete Maven POM](https://github.com/jxblum/past-year-in-spring-for-apache-geode/blob/master/pom.xml) file using the `spring-geode-bom` along with the `spring-geode-starter` dependency.

Of course, the version specified in the `spring-geode.version` property will vary depending on the version of _Spring Boot_ (e.g. `2.2.11`, `2.3.5`, `2.4.0`, etc) selected.

Like the currently "generated" Maven POM, it **will (still) only include** the `org.springframework.geode:spring-geode-starter` dependency, however, without the `version` specifier since the "generated" Maven POM will now include a `dependencyManagement` declaration with the `org.springframework.geode:spring-geode-bom` along with a `spring-geode.version` property enabling users/customers to easily and quickly change SBDG versions as desired or needed.

In addition, if users/customers need to include additional SBDG project modules (e.g. `spring-geode-starter-session`), then they can do so without worrying about version!

This is not unlike when users/customers add "_Azure Support_" dependency, which includes a `dependencyManagement` section for the Spring Boot Azure dependencies in the generated Maven POM.

[EXAMPLE](https://start.spring.io/#!type=maven-project&language=java&platformVersion=2.3.5.RELEASE&packaging=jar&jvmVersion=11&dependencies=geode,azure-support)

I waited to submit this request until all supported versions (i.e. `1.2`, `1.3` and `1.4`) of "_Spring for Apache Geode_" (i.e. SBDG) on _Spring Initializer_ at [start.spring.io](https://start.spring.io) made the `spring-geode-bom` available so that the "generated" Maven POM (or Gradle build file) will be consistent across versions, minus the version, of course.

**Comment by snicoll** [comment]
Thanks for the suggestion, that's a great idea.

**Comment by jxblum** [comment]
Thank you @snicoll; this is very much appreciated.
