### ISSUE TITLE
Improve getting started experience with Okta with a dedicated section in HELP.md

### ISSUE THREAD

**Issue by arvindkrishnakumar-okta** [spring-io/start.spring.io#568]
When a new user wants to generate a project that uses Okta Spring Boot Starter, below steps have been noted (per https://github.com/oktadeveloper/okta-maven-plugin#spring-boot-quick-start):

```
curl https://start.spring.io/starter.tgz -d dependencies=web,okta \
  -d baseDir=okta-spring-security-example-app | tar -xzvf -

cd okta-spring-security-example-app
```

Next, the user has to execute below 'hard to remember' steps to use the `okta-maven-plugin` to register and configure the new app:

Register:
`./mvnw com.okta:okta-maven-plugin:register`

Configure:
`./mvnw com.okta:okta-maven-plugin:spring-boot`

It would be nice if `start.spring.io` can include the `okta-maven-plugin` in generated project's pom.xml so the user can easily do a `mvn okta:register` & `mvn okta:spring-boot`.

**Related Issue:**

https://github.com/okta/okta-spring-boot/issues/205

**Comment by snicoll** [comment]
Thanks for the explanation but can you provide an actual example (a build config with the plugin defined)?

**Comment by snicoll** [comment]
@arvindkrishnakumar-okta any feedback for me?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by mraible** [comment]
@snicoll Here's what the build config should look like:

```
<project>
  ...
  <build>
    <plugins>
      <plugin>
        <groupId>com.okta</groupId>
        <artifactId>okta-maven-plugin</artifactId>
        <version>0.4.0</version>
      </plugin>
      ...
    </plugins>
  </build>
  ...
</project>
```

From https://oktadeveloper.github.io/okta-maven-plugin/plugin-info.html.

> Why is this specific to Maven?

Because we only have a Maven plugin. We do not have one for Gradle. @cc bdemers.

**Comment by snicoll** [comment]
Thanks Matt. Following your tweets, shouldn't we promote https://github.com/okta/okta-cli in `HELP.md` rather?

I am not really keen to add something that's build system specific if there is a solution that's independent. Also, having to hardcode (and therefore maintain) the version of the Okta Maven Plugin doesn't seem warranted for the added value here. 

If you agree, it would be helpful to craft a small section here in Markdown format (a couple sentences with links) and we can include that whenever Okta is selected.

**Comment by mraible** [comment]
@snicoll Yes, that's a good idea. The Okta Maven Plugin started it all, and I believe they share code, so that was my original motivation. I don't know if @bdemers plans on creating a Gradle plugin too. 

I [created an app](https://start.spring.io/#!type=maven-project&language=java&platformVersion=2.4.0.RELEASE&packaging=jar&jvmVersion=11&groupId=com.example&artifactId=demo&name=demo&description=Demo%20project%20for%20Spring%20Boot&packageName=com.example.demo&dependencies=security,devtools,web,data-jpa,h2) on start.spring.io and looked at the generated `HELP.md`. It just has links to tutorials. Is that what you're looking for or can we add sentences and such? An example would help a lot.

**Comment by snicoll** [comment]
I've asked you to write a section with what you'd envision. If you need an example, select wavefront and look at the generated help. 

Based on your section we can refine and I can take care of adding it to production.

**Comment by mraible** [comment]
OK, here's a suggestion. It's in Markdown, so hopefully you can edit this comment to see the raw code. If not, I can create a gist.

* [Okta Spring Boot documentation](https://github.com/okta/okta-spring-boot#readme)
* [Okta CLI documentation](https://cli.okta.com)
* [Okta CLI repository](https://github.com/okta/okta-cli)

## OAuth 2.0 and OIDC with Okta

If you don't have a free Okta developer account, you can create one with the Okta CLI:

```
okta register
```

Then, register your Spring Boot app on Okta using:

```
okta apps create
```

Select **Web** > **Okta Spring Boot Starter** and accept the default redirect URIs.
```

**Comment by snicoll** [comment]
That sounds very nice, thank you! I'll give it a try.

**Comment by snicoll** [comment]
I've rephrase the section to provide the link to the CLI directly in the text. It should land in production once all the smoke tests have completed. Let me know what you think and if the initial text needs to be further polished. Thanks again!
