### ISSUE TITLE
spring-javaformat

### ISSUE THREAD

**Issue by ziodave** [spring-io/start.spring.io#570]
I hope this is the right place... I think [spring-javaformat](https://github.com/spring-io/spring-javaformat) would be a nice addition to the dependencies list.

**Comment by wilkinsona** [comment]
This is the right place and thank you for the suggestion. We've [considered this in the past](https://github.com/spring-io/start.spring.io/issues/306) and decided not to add the dependency. I don't think our opinion has changed since then.
