### ISSUE TITLE
Upgrade to Spring Cloud GCP 2.0.0-RC2

### ISSUE THREAD

**Issue by ttomsu** [spring-io/start.spring.io#578]
Companion PR: https://github.com/spring-io/start.spring.io/pull/577

Context: Spring Cloud GCP 1.x rides along the Spring Cloud Release train up to the Hoxton release. With Ilford+, we are no longer on the release train and did a version bump to 2.x. As mentioned in the PR, we need this for 1.x

```
- name: Google Cloud Platform
  bom: spring-cloud
```
 and this for 2.x
```
- name: Google Cloud Platform 2.0
  bom: spring-cloud-gcp
```
otherwise I would have kept them lumped together.

Currently 2.0.0-RC1 is in Maven Central, but RC2 is coming soon and we'll be able to release the GA shortly after the full Ilford release (currently slated for mid Dec 2020)

**Comment by snicoll** [comment]
Thanks for the additional context @ttomsu. We need to be able to map a different pom so I've created https://github.com/spring-io/initializr/issues/1155

**Comment by snicoll** [comment]
For the record, the `groupId` also changed. @ttomsu thanks again for the original draft, see c14f4f3 for more details.

**Comment by ttomsu** [comment]
@snicoll The way this is implemented means someone looking for an older version of Spring Boot + GCP can't get it. Do you have data on how often the older GA versions are selected when there is a newer GA version available?

**Comment by snicoll** [comment]
> The way this is implemented means someone looking for an older version of Spring Boot + GCP can't get it.

I don't understand what you mean by that. What way and what do you mean by "can't get it?"

**Comment by ttomsu** [comment]
As in if someone selects Boot 2.3.6 and "GCP Support", won't the new 2.0.0-RC2 version be added when they actually need the most recent Hoxton version (1.2.6 IIRC)?

**Comment by snicoll** [comment]
> As in if someone selects Boot 2.3.6 and "GCP Support", won't the new 2.0.0-RC2 version be added 

No. Have you tried it?

**Comment by ttomsu** [comment]
I guess it works as expected. Thanks for pushing this through!
