### ISSUE TITLE
Please Allow Spring Initializr Remember my Settings

### ISSUE THREAD

**Issue by pbkh-bunthai** [spring-io/start.spring.io#588]
# Requirements

I would like to request allowing to remember my setting after the first time set such, **Project (Maven, Gradle) &  Language & Java Version**. 

Or 

- you can provide presetting options to users to do preset.
- when they init a project the users can use their preset.
- allow the users to set the default to any preset
Example:

A user creates:

**Preset-1**
- Name: Java8Project
  + Project: Gradle
  + Java: Java
  + Version: 8
  + etc

**Preset-2**
- Name: Kotlin11Project
  + Project: Maven
  + Java: Kotlin
  + Version: 11
  + etc

**Other preset**
....

You can save those setting at the client-side (local storage ...)

Thank you :smile:

**Comment by snicoll** [comment]
@pbkh-bunthai the entry proposal section is for requesting the addition of a new entry on the site. This has been requested before (see #290). The share feature lets you create a link that allows you to restore the UI in whatever state you want.
