### ISSUE TITLE
Gradle project with spring-cloud-stream does not build

### ISSUE THREAD

**Issue by henriquels25** [spring-io/start.spring.io#591]
I created a project with the options shown in the following image:

<img width="1112" alt="spring_initializer_cloud_stream" src="https://user-images.githubusercontent.com/4086440/101295643-9fab7680-37fd-11eb-9ca7-baa18a6d5275.png">

When I extract the project and run `./gradlew clean build` it throws the following error:

```
Execution failed for task ':compileTestJava'.
> Could not resolve all files for configuration ':testCompileClasspath'.
   > Could not find org.springframework.cloud:spring-cloud-stream:test-binder.
     Required by:
         project :
   > Could not find org.springframework.cloud:spring-cloud-stream:test-binder.
     Required by:
         project :
   > Could not find org.springframework.cloud:spring-cloud-stream:test-binder.
     Required by:
         project : > org.springframework.cloud:spring-cloud-stream-binder-kafka-streams:3.0.9.RELEASE > org.springframework.cloud:spring-cloud-stream-binder-kafka-core:3.0.9.RELEASE
```

I set up a simple project to demonstrate the problem: https://github.com/henriquels25/cloud-stream-gradle. This sample project is the same one the [start.spring.io](https://start.spring.io) generated.

The error can be observed in [this](https://github.com/henriquels25/cloud-stream-gradle/runs/1507698149) CI execution.

The cause for the error is the following dependency:

`testImplementation 'org.springframework.cloud:spring-cloud-stream:test-binder@test-jar'`. 

When I remove it, the project builds successfully, as it can be observed in the branch `remove_test_dependency` and in [this](https://github.com/henriquels25/cloud-stream-gradle/actions/runs/404228729) CI execution.

**Comment by henriquels25** [comment]
I just found the issue [#1159](https://github.com/spring-io/initializr/issues/1159) in the [spring-io/initializr](https://github.com/spring-io/initializr) repo. It is the same problem I am facing.

**Comment by snicoll** [comment]
Thanks @henriquels25, closing this one as a duplicate. I've disabled this pos-processor for Gradle in the meantime so that projects using this dependency can build properly.
