### ISSUE TITLE
Spring Cloud Contract Gradle plugin configuration does not work with the latest version of the plugin

### ISSUE THREAD

**Issue by plamentotev** [spring-io/start.spring.io#612]
There are two issues with the generated configuration for Spring Cloud Contract Gradle plugin that breaks the build when the latest version of Spring Cloud Contract is used:

- `targetFramework` was deprecated attribute and it is now removed. This causes the Gradle configuration script to break and not compile
- Since Spring Cloud Contract Gradle plugin 2.2.0.M1 the generated tests are executed in separate task - `contractTest`. It need additional configuration in order to run the generated tests.

**Comment by snicoll** [comment]
@plamentotev thanks for the report. For the record, there is no need to open both an issue and a PR as the latter supersedes the former.
