### ISSUE TITLE
Fix job that builds CI images

### ISSUE THREAD

**Issue by mbhave** [spring-io/start.spring.io#615]
Following the change to use the `registry-image` type, the CI image job is failing. We need to do something similar to [Spring Boot's pipeline](https://github.com/spring-projects/spring-boot/blob/66598ed4ad287ca65df3c337412f9d5b4075433e/ci/pipeline.yml#L220).

**Comment by snicoll** [comment]
@mbhave I tried to harmonise things so that this CI setup is similar to the one of the library. Unfortunately, I've stumbled a number of issues. I've started a temporary pipeline [on a branch](https://github.com/spring-io/start.spring.io/tree/ci-refactoring).

**Comment by snicoll** [comment]
With the help of @wilkinsona, I discovered I broke that in b7369aa600252c18df1f71bb4ad9f5f821d72bac
