### ISSUE TITLE
"metrics" missing from Micrometer registry entries

### ISSUE THREAD

**Issue by shakuzen** [spring-io/start.spring.io#617]
Datadog, Influx, Graphite, New Relic, and Prometheus have entries but they do not show up in a search on start.spring.io's dependencies if using the keyword `metrics` or `micrometer`, which was surprising to me. Currently the descriptions are a general description of the service/product. I wonder if a more uniform description across the entries that describes what the dependency enables for a Spring Boot user rather than what (various) things a user can do with the service/product would be better in this context.

For example, something along the lines of "Publish Micrometer metrics to {BACKEND} for long-term storage/analysis". While the backends have functionality beyond metrics (e.g. tracing, graphing, alerting), the dependency here only enables publishing the registered Micrometer metrics to that backend, which is why I've proposed limiting the description to that.

**Comment by snicoll** [comment]
Thanks for the report. I agree that "metrics" and "micrometer" should be part of the description. 

I am not keen to add a generic description for those though. I like the idea that each entry provides unique characteristics of the backend. This, of course, doesn't help making sure the description isn't too length. 

Here is an attempt at mixing the two:

Datadog:
> Publish Micrometer metrics to Datadog, a dimensional time-series SaaS with built-in dashboarding and alerting.

Influx:
> Publish Micrometer metrics to InfluxDB, a dimensional time-series server that support real-time stream processing of data.

Graphite:
> Publish Micrometer metrics to Graphite, a hierarchical metrics system backed by a fixed-size database.

New Relic:
> Publish Micrometer metrics to New Relic, a SaaS offering with a full UI and a query language called NRQL.

Prometheus:
> Publish Micrometer metrics to Prometheus, an in-memory dimensional time series database with a simple built-in UI, a custom query language, and math operations.

Wavefront:
> Publish Micrometer metrics to Tanzu Observability by Wavefront, a SaaS-based metrics monitoring and analytics platform that lets you visualize, query, and alert over data from across your entire stack (infrastructure, network, custom app metrics, business KPIs, etc.)

Technically the prometheus entry is a bit misleading since prometheus is scrapping the data. Flagging to get more feedback from the team.

**Comment by wilkinsona** [comment]
They look good to me, other than the Wavefront one being a bit too long (in comparison to the others at least). Perhaps get rid of the section in parenthesis?

**Comment by shakuzen** [comment]
> Technically the prometheus entry is a bit misleading since prometheus is scrapping the data.

How about "Expose Micrometer metrics in Prometheus format..." for that one then?

**Comment by snicoll** [comment]
Thanks both!
