### ISSUE TITLE
Reference Vaadin-specific plugin when generating a project with Vaadin

### ISSUE THREAD

**Issue by mvysny** [spring-io/start.spring.io#622]
The Vaadin Gradle Plugin is now available at https://github.com/vaadin/vaadin-gradle-plugin/ . The plugin will generate all files necessary for Vaadin to work properly, which will also fix spring-io/initializr#1122 .

When using Vaadin, could you please add the following line:

* `id 'com.vaadin' version '0.14.3.7'` to `build.gradle`
* `id("com.vaadin") version "0.14.3.7"` to `build.gradle.kts`

**Comment by snicoll** [comment]
Alright, I'll give that a try. Thanks both for the feedback.

**Comment by mstahv** [comment]
Great! This will become my primary method to create Vaadin projects 😯

**Comment by snicoll** [comment]
@mstahv I thought it was already the case 😜 - Alright, the build plugins should be configured accordingly. This should hit production in 10 minutes or so once the smoke tests have ran. Let me know if we can improve the developer experience any further.

**Comment by mstahv** [comment]
🥳 Works like a charm! Tested both Maven and Gradle projects.
