### ISSUE TITLE
Use Gradle 5 with projects that use Java 11

### ISSUE THREAD

**Issue by wilkinsona** [spring-io/start.spring.io#63]
Officially, it's only Gradle 5 that will support Java 11. When it's released (and when we know Boot's plugin and the dependency management plugin are compatible with it), we should use Gradle 5 with Java 11-based projects.

**Comment by snicoll** [comment]
See also https://github.com/spring-io/initializr/issues/847

**Comment by snicoll** [comment]
Turns out that Spring  Boot 2.1 uses Gradle 5 by default so this case is already covered.
