### ISSUE TITLE
Upgrade to Azure Spring 3.1.0

### ISSUE THREAD

**Issue by chenrujun** [spring-io/start.spring.io#634]
The azure-spring-boot-bom of version 3.1.0 has been release to Maven: 
https://repo1.maven.org/maven2/com/azure/spring/azure-spring-boot-bom/3.1.0/
It's work for spring-boot-2.3.x
Please help to upgrade to the latest version.

Thanks

**Comment by wilkinsona** [comment]
@chenrujun Does this one just work with 2.3.x or does it support 2.4.x as well? I'm guessing that it's just 2.3.x, [with a 3.2.0 that supports 2.4](https://github.com/spring-io/start.spring.io/issues/606#issuecomment-755171215) to come.

**Comment by chenrujun** [comment]
@wilkinsona .

`3.1.0` just work with 2.3.x.
Now 2.4.x is not supported. We plan to support 2.4.x in next release.
