### ISSUE TITLE
Update devtools with gradle to use a custom configuration

### ISSUE THREAD

**Issue by philwebb** [spring-io/start.spring.io#64]
See https://github.com/spring-projects/spring-boot/issues/14451 for details.

**Comment by wilkinsona** [comment]
We could hopefully simplify things a bit by implementing https://github.com/spring-projects/spring-boot/issues/16599 on the Boot side. That would remove the need to define the custom configuration. The remaining piece would be to map a dependency on DevTools to the `developmentOnly` configuration.

**Comment by snicoll** [comment]
The custom configuration is actually easy but I am glad to see our plugin can create that boilerplate automatically. The blocker at this point is to be able to defined custom scopes (see https://github.com/spring-io/initializr/issues/850)
