### ISSUE TITLE
Modify lowerbound of compatibility range of Azure related libraries.

### ISSUE THREAD

**Issue by yiliuTo** [spring-io/start.spring.io#650]
Hi, the compatibility range of [Azure Active Directory](https://github.com/spring-io/start.spring.io/blob/4804cc9b5fa9055a7945f8776c7aef63aec867f8/start-site/src/main/resources/application.yml#L1310), [Azure Key Vault](https://github.com/spring-io/start.spring.io/blob/4804cc9b5fa9055a7945f8776c7aef63aec867f8/start-site/src/main/resources/application.yml#L1325) and [Azure Storage](https://github.com/spring-io/start.spring.io/blob/4804cc9b5fa9055a7945f8776c7aef63aec867f8/start-site/src/main/resources/application.yml#L1340) is [2.0.0.RELEASE,2.4.0-M1), however, it actually is [2.2.11.RELEASE,2.4.0-M1).

Can someone help to update it? Thanks~

<img src="https://user-images.githubusercontent.com/63028776/109263083-a4505b80-783d-11eb-8977-fd9eadfcbb1f.png" width="50%" height="50%">

**Comment by snicoll** [comment]
That's a good catch. We pruned the Azure bom mappings for Spring Boot 2.0 and 2.1 and we forgot to change the compatibility range accordingly.

Can you share why 2.2.4 requires Spring  Boot 2.2.11? Strictly speaking I don't expect anyone to create a project with Spring Boot `2.2.0.RELEASE` at this point but I'd like to understand why it needs to be so strict.

**Comment by yiliuTo** [comment]
Hi @snicoll , we hope the lowerbound could be 2.2.11 is because, there are version conflicts of netty between our libraries and spring boot 2.2.10 backwards. And from spring boot 2.2.11, we found that bug and adjusted our dependency version to be aligned with spring boot.

**Comment by snicoll** [comment]
Thanks for the feedback. It's worth documenting this here, thank you.
