### ISSUE TITLE
Add gradle wrapper hash

### ISSUE THREAD

**Issue by MarcelCoding** [spring-io/start.spring.io#659]
Since [gradle 6.8.3](https://github.com/gradle/gradle/releases/tag/v6.8.3) you can include the hash of the gradle wrapper in the `gradle-wrapper.properties`. If you do a gradle update with the new command on the [GitHub release](https://github.com/gradle/gradle/releases/tag/v6.8.3), the will be also added. Please include the hash by out of the box.

```properties
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionSha256Sum=7faa7198769f872826c8ef4f1450f839ec27f0b4d5d1e51bade63667cbccd205
distributionUrl=https\://services.gradle.org/distributions/gradle-6.8.3-bin.zip
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
```

**Comment by wilkinsona** [comment]
Thanks for the suggestion. What benefit do you see in start.spring.io setting the checksum? The Gradle [documentation says that it's to protect against man-in-the-middle attacks](https://docs.gradle.org/current/userguide/gradle_wrapper.html#sec:verification), however we're using an HTTPS distribution URL I don't that a MitM attack is a risk.

/cc @JLLeitschuh

**Comment by MarcelCoding** [comment]
Ok, then I think it is not necessary.

**Comment by JLLeitschuh** [comment]
The SHA checksum also operates as a kind of community protection against replacement. By using the checksum, you know that you're getting the same version today as you are a year from now. Having it set by default is a good security control to have if possible.

**Comment by wilkinsona** [comment]
With that goal in mind, wouldn't it be better if Gradle set the checksum itself? If I trust the distribution URL today, then it can presumably also be trusted to provide a checksum for the binary. The checksum can then be used in a year's time to check that what I trusted today is still trustworthy.

**Comment by MarcelCoding** [comment]
As I mentioned in my issue, if you run the "new" update command the hash will be set in the gradle.properties.
```bash
./gradlew wrapper --gradle-version=6.8.3 --gradle-distribution-sha256-sum 7faa7198769f872826c8ef4f1450f839ec27f0b4d5d1e51bade63667cbccd205
```

**Comment by wilkinsona** [comment]
Thanks, @MarcelCoding. I understood that. I am questioning the need for `--gradle-distribution-sha256-sum` when generating the wrapper. If the distribution URL is https and trusted, I am wondering why the checksum can't be added to `gradle-wrapper.properties` automatically without having to look it up in the release notes on GitHub or from https://gradle.org/release-checksums/. It's all HTTPS so requiring manual copy-paste seems like a step that could be eliminated. If Gradle did provide the checksum automatically, I think we'd be more inclined to include it in the pre-generated wrapper that's part of an app created by start.spring.io.

**Comment by MarcelCoding** [comment]
Currently I don't know any way to let gradle do this step automatically. But with the argument of https I think it is ok as it is.

**Comment by JLLeitschuh** [comment]
Related gradle/gradle issue: https://github.com/gradle/gradle/issues/12412
