### ISSUE TITLE
希望提供项目 maven libraries  依赖包 jar 文件包的下载 (Google translation: Hope to provide the download of the project maven libraries dependency package jar file package)

### ISSUE THREAD

**Issue by 15678871232** [spring-io/start.spring.io#668]
网络有问题，下载会很慢，1小时或2小时 jar才会下载完成。

**Comment by wilkinsona** [comment]
> 网络有问题，下载会很慢，1小时或2小时 jar才会下载完成。

Google translation: There is a problem with the network, the download will be very slow, and the jar will be downloaded in 1 or 2 hours.

**Comment by wilkinsona** [comment]
@15678871232 Is it downloading the zip file for a project generated on start.spring.io that's very slow, or are the downloads very slow when you are building the generated project with Maven?

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
