### ISSUE TITLE
Upgrade to Azure Spring Boot 3.3.0

### ISSUE THREAD

**Issue by saragluna** [spring-io/start.spring.io#670]
Hello there, we've just released the azure-spring-boot-bom of version [3.3.0](https://repo1.maven.org/maven2/com/azure/spring/azure-spring-boot-bom/3.3.0/
). For 3.3.0, it supports Spring Boot 2.4.3 and onwards. Please help to upgrade these entries for Azure.

**Comment by snicoll** [comment]
@saragluna congratulations on the release.
