### ISSUE TITLE
Blank page on start.spring.io after a redeploy

### ISSUE THREAD

**Issue by MikailaAkeredolu** [spring-io/start.spring.io#682]
Unable to generate a springboot project because start.spring.io is just showing a blank page. Thanks

**Comment by snicoll** [comment]
Thanks but that's a deployment problem that has nothing to do with the library. I've moved your issue to the appropriate issue tracker.

@bclozel looks like we're still having those JS resources not being found after a redeploy. I experienced that myself yesterday.

@MikailaAkeredolu it is a cache problem that goes away after a couple of minutes. We'll keep this issue open to investigate how we can avoid it.

**Comment by MikailaAkeredolu** [comment]
Thanks. I cleared my cache and it was resolved. Thanks

**Comment by snicoll** [comment]
Looking at the symptoms and how we fixed it before, it may be related to https://github.com/spring-projects/spring-boot/issues/26212.
