### ISSUE TITLE
Gradle project for Spring Boot 1.5.x with Lombok defines dependency twice

### ISSUE THREAD

**Issue by tgeens** [spring-io/start.spring.io#69]
```
curl start.spring.io/build.gradle -d dependencies=lombok -d bootVersion=1.5.19.RELEASE
```

results in:

```
...
dependencies {
	compile 'org.springframework.boot:spring-boot-starter'
	compileOnly 'org.projectlombok:lombok'
	compileOnly 'org.projectlombok:lombok'
	testCompile 'org.springframework.boot:spring-boot-starter-test'
}
```

**Comment by snicoll** [comment]
Good catch, thank you for reporting it! I've noticed we were also tuning the `annotationProcessor` for no good reason as we're not using it with Gradle 3. I've [just fixed that](https://github.com/spring-io/initializr/issues/848#issuecomment-471272932) and am looking in that faulty customization now.

**Comment by snicoll** [comment]
Thank you very much, this should be available in production shortly.
