### ISSUE TITLE
link to azure storage user guidance is broken

### ISSUE THREAD

**Issue by Shashi-rk** [spring-io/start.spring.io#693]
link to guidance document for azure-spring-boot-starter-storage are broken. 
https://github.com/Microsoft/azure-spring-boot/tree/master/azure-spring-boot-starters/azure-storage-spring-boot-starter
https://github.com/Microsoft/azure-spring-boot/tree/master/azure-spring-boot-samples/azure-storage-spring-boot-sample

**Comment by snicoll** [comment]
@Shashi-rk thank you for the report.
