### ISSUE TITLE
Add support for Java 17

### ISSUE THREAD

**Issue by joshlong** [spring-io/start.spring.io#760]
Java 17 is an LTE release and generally available from a number of vendors / distributions including Java.NET (OpenJDK), Azul, Liberica, AWS Coretto, etc. Thank you for your consideration and thank you for helping move the java ecosystem forward by proactively supporting the next LTE version of Java. this is also fruitful because Java 16 is technology no longer supported, anyway

**Comment by snicoll** [comment]
The plan is to add Java 17 as soon as we have a Spring Boot release that officially supports it. This is happening this Thursday so I'll prepare the ground work to be ready on time. Thanks for raising it!
