### ISSUE TITLE
Spring State Machine Not listed

### ISSUE THREAD

**Issue by jalexcole** [spring-io/start.spring.io#785]
Spring State Machine does not come up in the initializr. It also is not able to be added manually.

**Comment by snicoll** [comment]
@jalexcole I've transfered your request to the appropriate issue tracker. Going forward, please use the link you'll find on start.spring.io.

> Spring State Machine does not come up in the initializr

Yes, we are aware. Not every single spring project has to be on the site. 

>  It also is not able to be added manually.

I don't know what you mean by that. I did find a problem on the quickstart section of the project so I've created https://github.com/spring-projects/spring-statemachine/issues/1008 - Please follow-up there. If you have more questions, please ask them on StackOverflow.
