### ISSUE TITLE
Upgrade to Azure Spring Boot 3.12.1

### ISSUE THREAD

**Issue by yiliuTo** [spring-io/start.spring.io#828]
Hello there, we've just released the azure-spring-boot-bom of version [3.12.1](https://mvnrepository.com/artifact/com.azure.spring/azure-spring-boot-bom/3.12.1). For 3.12.1, it supports Spring Boot versions of 2.5.8. Please help to upgrade these entries for Azure. Thanks.

**Comment by snicoll** [comment]
Thanks for keeping us current @yiliuTo. I understand that Azure Spring Boot `3.13.x` is going to be the release compatible with Spring Boot `2.6.x`. Is that right?

**Comment by yiliuTo** [comment]
Hi @snicoll , yes Azure Spring Boot 3.13.x will support 2.6.x. In fact the latest 3.12.1 also supports Spring Boot 2.6.0 and 2.6.1, but due to those versions have already been hiden from Spring Initializr thus I didn't mention them

**Comment by snicoll** [comment]
If the project is building against `2.6.x`, then we can open up the range. We're quite conservative in maintenance mode so if you have something that's testing against `2.6.1` then it should work with `2.6.x` in general. Do you want me to open up the range?

**Comment by cicorias** [comment]
any idea when this propagates to [Spring Initializer](https://start.spring.io/)? Still seeing the Set of Azure parts listed as constrained to `< 2.6.M1` or similar.

**Comment by snicoll** [comment]
I've asked a question in the comment above yours that hasn't got a reply yet.

**Comment by yiliuTo** [comment]
Cool @snicoll, then please help us to open up the range for 2.6.x, thanks for your explanation.

**Comment by snicoll** [comment]
@yiliuTo alright. That's done as part of #829 and in production once the CI build completes.

**Comment by yiliuTo** [comment]
Thanks @snicoll !
