### ISSUE TITLE
Selecting Spring Boot 3.0 should default to Java 17

### ISSUE THREAD

**Issue by philwebb** [spring-io/start.spring.io#832]
It would be nice if when Spring Boot 3.0+ is selected then the default JVM changes to 17 automatically and other options are disabled.

**Comment by snicoll** [comment]
Doing what you described should be expressed as constraints in the metadata and we don't have that feature yet. We've been downgrading versions when users were picking a Spring Boot version that didn't support a given JDK so we're going to do the opposite here and upgrade them to 17.
