### ISSUE TITLE
Upgrade to Spring Cloud Azure 4.0.0

### ISSUE THREAD

**Issue by saragluna** [spring-io/start.spring.io#871]
We are going to GA the next major version of Spring Cloud Azure later this month, and this version will have breaking changes in both artifact names and APIs. The next major version will be **4.0.0** and it's compatible with Spring Boot 2.5.x and 2.6.x, and we have released several beta versions already. So I am reaching out before the GA release to discuss the changes. 

- Azure Support: from `azure-spring-boot-starter` to [spring-cloud-azure-starter](https://repo1.maven.org/maven2/com/azure/spring/spring-cloud-azure-starter/)
- Azure Active Directory: from `azure-spring-boot-starter-active-directory` to [spring-cloud-azure-starter-active-directory](https://repo1.maven.org/maven2/com/azure/spring/spring-cloud-azure-starter-active-directory/)
- Azure Cosmos DB: from `azure-spring-boot-starter-cosmos` to [spring-cloud-azure-starter-data-cosmos](https://repo1.maven.org/maven2/com/azure/spring/spring-cloud-azure-starter-data-cosmos/)
- Azure Key Vault: from `azure-spring-boot-starter-keyvault-secrets` to [spring-cloud-azure-starter-keyvault-secrets](https://repo1.maven.org/maven2/com/azure/spring/spring-cloud-azure-starter-keyvault-secrets/)
- Azure Storage: from `azure-spring-boot-starter-storage` to [spring-cloud-azure-starter-storage-blob](https://repo1.maven.org/maven2/com/azure/spring/spring-cloud-azure-starter-storage-blob/)
- The BOM: from `azure-spring-boot-bom` to [spring-cloud-azure-dependencies](https://repo1.maven.org/maven2/com/azure/spring/spring-cloud-azure-dependencies/)

**Comment by saragluna** [comment]
Hi @snicoll, the release has finished. Could you help update the entries with the following changes?

- Azure Support: from `azure-spring-boot-starter` to [spring-cloud-azure-starter](https://repo1.maven.org/maven2/com/azure/spring/spring-cloud-azure-starter/4.0.0)
- Azure Active Directory: from `azure-spring-boot-starter-active-directory` to [spring-cloud-azure-starter-active-directory](https://repo1.maven.org/maven2/com/azure/spring/spring-cloud-azure-starter-active-directory/4.0.0)
- Azure Cosmos DB: from `azure-spring-boot-starter-cosmos` to [spring-cloud-azure-starter-data-cosmos](https://repo1.maven.org/maven2/com/azure/spring/spring-cloud-azure-starter-data-cosmos/4.0.0)
- Azure Key Vault: from `azure-spring-boot-starter-keyvault-secrets` to [spring-cloud-azure-starter-keyvault-secrets](https://repo1.maven.org/maven2/com/azure/spring/spring-cloud-azure-starter-keyvault-secrets/4.0.0)
- Azure Storage: from `azure-spring-boot-starter-storage` to [spring-cloud-azure-starter-storage-blob](https://repo1.maven.org/maven2/com/azure/spring/spring-cloud-azure-starter-storage-blob/4.0.0)
- The BOM: from `azure-spring-boot-bom` to [spring-cloud-azure-dependencies](https://repo1.maven.org/maven2/com/azure/spring/spring-cloud-azure-dependencies/4.0.0)

**Comment by snicoll** [comment]
@saragluna it would be nice if we had links to samples that are not pointing directly to a GitHub folder. Right now the samples are pointing to a branch, which can I see being changed and break. Would it be possible to add links to samples in the reference guide maybe?

**Comment by saragluna** [comment]
Hi @snicoll, could you point out to me which links are broken now? And what is the reference guide link?

**Comment by snicoll** [comment]
They aren't any broken links. I could add links to sample using https://github.com/Azure-Samples/azure-spring-boot-samples/releases/tag/spring-cloud-azure_4.0.0 but I am not feeling comfortable doing so as they are for a fixed version and I'd rather have something that evolves over time. 

Ideally we should be able to add a token to replace the version in the URL but we don't have that feature yet.

**Comment by saragluna** [comment]
@snicoll how about using this https://aka.ms/spring/samples, it will point to our sample repo.

**Comment by snicoll** [comment]
It's not a link to "the samples". We need a link to "a sample". Each entry can have a number of links. One for the documentation, one for the sample, etc. Try it out on start.spring.io for more details.

**Comment by saragluna** [comment]
Okay, we can use the following links:
- https://aka.ms/spring/samples/latest/storage
- https://aka.ms/spring/samples/latest/aad
- https://aka.ms/spring/samples/latest/cosmos
- https://aka.ms/spring/samples/latest/keyvault

**Comment by saragluna** [comment]
Hi @snicoll,  one more question about the site, when I choose the `Azure Support` with `Azure Cosmos` it uses version 4.0.0, but when I remove either one of them, it uses version 3.14.0. Is it because of some cached value? 

<img width="595" alt="image" src="https://user-images.githubusercontent.com/31124698/161222805-5a41892c-3c15-47df-a83b-57fd93d5d489.png">

<img width="598" alt="image" src="https://user-images.githubusercontent.com/31124698/161223083-49a4af63-ae3c-4d29-bb8c-7132e35123fc.png">
