### ISSUE TITLE
Upgrade to Solace Spring Boot 1.2.1 and Solace Spring Cloud 2.3.0

### ISSUE THREAD

**Issue by Mrc0113** [spring-io/start.spring.io#878]
Upgrade to solace-spring-cloud v2.3.0 when including Cloud Stream & Solace.
The release included Spring Boot upgrading to `2.6.4` and Spring Cloud `2021.0.1`. 

Also note that Solace has setup dependabot to auto-open PRs to test against the new Spring Boot & Spring Cloud releases. 
Example PRs against spring boot `2.6.5`
* https://github.com/SolaceProducts/solace-spring-boot/pull/30
* https://github.com/SolaceProducts/solace-spring-cloud/pull/132

**Comment by Mrc0113** [comment]
FYI @snicoll, new version available 🎉

And we added some automation as you can see above :)

**Comment by snicoll** [comment]
Thanks @Mrc0113. More importantly, Solace Spring Boot was stuck on 1.1.0. Thanks to the link above, I found out that `1.2.1` is available so I upgraded to that.

**Comment by Mrc0113** [comment]
Thanks @snicoll! Now that we have automated tests going against future Spring versions is there a way we can avoid having the Solace dependencies disabled when you add a new Spring Boot / Cloud version to start.spring.io?

**Comment by snicoll** [comment]
I am not sure what you'd expect us to do there. If you test against `2.7.x`, you can say so in an issue with the versions that are tested and I can open up the range. I don't expect the same version of the starter to "just" work with a major new feature of Spring Boot & Spring Cloud so the automated tests won't be sufficient  for Spring Boot 3.x

The long story short is that if you can test the milestone before the release (2.7) at the moment, we can open up the range for sure before it becomes the default.
