### ISSUE TITLE
A Boot 3.0-based app that depends on PostgreSQL and Spring Data R2DBC uses the wrong coordinates for its r2dbc-postgresql dependency

### ISSUE THREAD

**Issue by wilkinsona** [spring-io/start.spring.io#881]
It has [moved into the `org.postgresql` group](https://github.com/r2dbc/r2dbc-bom/issues/44) in Borca-M2. `R2dbcBuildCustomizer` should be updated accordingly.

**Comment by tisonkun** [comment]
Thanks for filing this issue! I'd like to see whether I can prepare a patch now :P

**Comment by snicoll** [comment]
Closing in favor of PR #882
