### ISSUE TITLE
Incompatible version of Gradle and JDK 18 cause error at start step.

### ISSUE THREAD

**Issue by donhuvy** [spring-io/start.spring.io#887]
![image](https://user-images.githubusercontent.com/1328316/161366991-d854401d-e700-4049-985b-62d23695591f.png)

![image](https://user-images.githubusercontent.com/1328316/161367024-33afed1f-b0ad-4c02-81a0-0849d13d0285.png)

![image](https://user-images.githubusercontent.com/1328316/161366993-d366877c-8132-4884-9832-e3774eda5609.png)

Error (due too long, I paste to gist) https://gist.github.com/donhuvy/e5d7b25f0767586380699ad699b672d3

**Comment by wilkinsona** [comment]
From Gradle’s error output:

> Incompatible because this component declares an API of a component compatible with Java 17 and the consumer needed a runtime of a component compatible with Java 16

Spring Boot 3 requires Java 17 but you are building your project with Java 16.

**Comment by donhuvy** [comment]
I think you has mistake. I have JDK 18 on my machine.
