### ISSUE TITLE
Upgrade to Spring Cloud Open Service Broker 2.1.1

### ISSUE THREAD

**Issue by goober** [spring-io/start.spring.io#89]
A generated project from start.spring.io that has a single dependency to Open Service Broker does not compile

## Reproduce
Create a new spring boot application with the following settings:
Project: Gradle
Language: Java
Spring Boot: 2.1.3
Packaging: Jar
Java Version: 11
Dependencies: Open Service Broker

## Expected behavior:
A generated project that compiles when running `./gradlew clean build`

## Actual behavior
 ```bash
error: package org.springframework.boot does not exist
import org.springframework.boot.SpringApplication
```

## Why?
The dependency `implementation 'org.springframework.boot:spring-boot-starter'` is missing from the generated `build.gradle` file

Generated `build.gradle` from the above steps:
```gradle
dependencies {
	implementation 'org.springframework.cloud:spring-cloud-starter-open-service-broker-webmvc:2.1.0.RELEASE'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
}
```

Generated `build.gradle` when creating a project without any dependencies:
```groovy
dependencies {
	implementation 'org.springframework.boot:spring-boot-starter'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
}
```

When `implementation 'org.springframework.boot:spring-boot-starter'` has been added manually to build.gradle everything compiles as expected.

**Comment by wilkinsona** [comment]
@royclarkson Can you please add a note in your release process to open an issue or PR to upgrade `start.spring.io` so that users can pick up your bug fixes in a timely manner?

**Comment by royclarkson** [comment]
@wilkinsona thanks for the reminder. We'll do that.
