### ISSUE TITLE
Add dekorate (kubernetes-spring-starter, knative-spring-starter, openshift-spring-starter)

### ISSUE THREAD

**Issue by iocanel** [spring-io/start.spring.io#904]
# Requirements
To ensure the ongoing health of the Spring Boot community, a starter that is included on
start.spring.io must meet the following requirements.

## Code of Conduct
- [x] This project adheres to the Contributor Covenant code of conduct. By participating, you
are expected to adhere to this code. If you have not already done so, we also encourage
you to adopt a code of conduct in your own project.

## Well-established project with a vibrant community
- [x] To avoid overwhelming users with too much choice, we aim for each starter to be of
interest to a broad range of start.spring.io's users. One way to ensure this is for each
starter to represent a well-established project with a vibrant community.

Repository: https://github.com/dekorateio/dekorate
Website: https://dekorate.io
Github stars: 362
Contributors: 42
Forks: 85

## Ongoing maintenance
- [x] To ensure that the Spring Boot community has a good experience with your starter,
it should be kept up-to-date with the latest Spring Boot releases and maintenance
releases should be shipped as needed. When a new release is made, a pull request
should be made to this project to ensure that the Spring Boot community are using the
latest version

## Licence
- [x] Please provide details of your project's licence. If you starter pulls in any
dependencies with a different license to the  starter's own licence, please provide
details of those dependencies' licences as well.

[Apache 2.0](https://github.com/dekorateio/dekorate/blob/main/license.txt)

## Issue Tracker URL
- [x] To allow users of your starter to contribute and provide feedback, please provide
the URL of its issue tracker.
[Dekorate Github Issue Tracker](htps://github.com/dekorateio/dekorate/issues)

## Continuous integration
- [x] To help to ensure the ongoing compatibility of your starter with Spring Boot, please
provide a link to the CI jobs that verify its compatibility. Compatibility should
be achieved using Spring Boot's dependency management without overriding.

[Github Actions](https://github.com/dekorateio/dekorate/actions)
![Build](https://github.com/dekorateio/dekorate/actions/workflows/build.yml/badge.svg)
![Integration Tests](https://github.com/dekorateio/dekorate/actions/workflows/integration-tests.yml/badge.svg)

## Maven Central

Starters that are included on start.spring.io must be available on Maven Central.

- [x] Starter and all of its dependencies are available on Maven Central.

[![Kubernetes Spring Starter](https://img.shields.io/maven-central/v/io.dekorate/kubernetes-annotations.svg?label=Kubernetes%20Spring%20Starter)](https://search.maven.org/search?q=g:%22io.dekorate%22%20AND%20a:%22kubernetes-spring-starter%22)

[![Knative Spring Starter](https://img.shields.io/maven-central/v/io.dekorate/kubernetes-annotations.svg?label=Knative%20Spring%20Starter)](https://search.maven.org/search?q=g:%22io.dekorate%22%20AND%20a:%22knative-spring-starter%22)

[![Openshift Spring Starter](https://img.shields.io/maven-central/v/io.dekorate/kubernetes-annotations.svg?label=Openshift%20Spring%20Starter)](https://search.maven.org/search?q=g:%22io.dekorate%22%20AND%20a:%22openshift-spring-starter%22)

## Configuration metadata
If you starter provides `@ConfigurationProperties` it should provide metadata for those
properties to enable auto-completion in the IDE. Metadata can be provided by adding
field level documentation on each of the properties and adding the
`spring-boot-configuration-processor` to your build.

~[ ] Starter provides metadata, including documentation, for all its configuration
properties.~

The starter does does not provide @ConfigurationProperties.
[Configuration refence](https://dekorate.io/configuration-guide/)

## Version mappings
- [x] Spring Initializr allows different versions of a starter to be used with different
versions of Spring Boot. For example, if a project is being generated with Spring
Boot version W you may want to use Starter version X and if a project is being
generated with Spring Boot version Y you may want to use Starter version Z.

The starters are expected to work with all version of Spring Boot, as they do not depend neither directly nor transitively to any spring boot artifact. The starters are mostly annotation processors that are triggered by the presence of annotations like `SpringApplication`, `RestoController` etc. These are referenced only as fully qualified names.

## Links to additional resources
- [x] Each entry can be associated with one or several links. Please provide at least a link to
a sample and the reference documentation:

* Reference documentation: https://dekorate.io/docs/get-started/
* Sample: 
  - [Spring Boot on Kubernetes](https://github.com/dekorateio/dekorate/tree/main/examples/spring-boot-on-kubernetes-example)
  - [Spring Boot on Openshift](https://github.com/dekorateio/dekorate/tree/main/examples/spring-boot-on-openshift-example)

**Comment by wilkinsona** [comment]
Thanks for the proposal and for being part of the Spring Boot ecosystem.

start.spring.io is somewhat opinionated in terms of the dependencies that it offers and it is our opinion that, generally speaking, applications that are going to be deployed to Kubernetes shouldn't be aware of that. We believe that external tools such as Skaffold and Kustomise are a better fit for easing deployment to Kubernetes. As such, we don't want start.spring.io to encourage a development model such as Dekorate's that requires Kubernetes-specific dependencies and annotations.

We have a less opinionated [list of community-developed starters in the Spring Boot repository](https://github.com/spring-projects/spring-boot/tree/main/spring-boot-project/spring-boot-starters#community-contributions). If you would like your starters to be listed there we would be happy to do so. Please feel free to open a Spring Boot pull request for their addition.

**Comment by iocanel** [comment]
@wilkinsona It seems that your opinion is set on the matter, still I'd like to share my perspective.

The way I see things, adding a compile time jar to the project and and tuning things via the `application.properties` or build arguments does not make the application kubernetes-aware. It does make however the manifest generation process application-aware, as it allow the manifest generation process to detect things like: 

- RestController annotation
- JAXRS annotations
- Spring Cloud Kubernetes
- Beans and more

... in order to tune the manifests accordingly.

I strongly feel that this approach produces manifests tailored to the needs of the application, without forcing the users to pickup a new tool.

Should you ever decide to reconsider I am at your disposal to further discuss about it, as I am committed to delivering the best possible user experience for spring boot developers wanting to get on kubernetes.

**Comment by cmoulliard** [comment]
@wilkinsona I'm not opposite again the fact to use an external project/tool as you proposed but the main goal of Dekorate and this new starter is to offer for the Spring(Boot) developers a Java project (= jar files only) able to generate the k8s manifests (json/yaml) using Java annotations or properties which can be next deployed on the k8s cluster. No additional tools are needed locally for the developer except a docker | podman daemon and kubectl. 

- To use kustomize and/or skafffold, then it is needed to install some additional tools
- kustomize is a templating engine which presupposes that some k8s resources exist while Dekorate will generate them 
- skaffold is a tool handling the innerloop development lifecycle while dekorate is focusing around populating the k8s resources for several frameworks, domains (kubernetes or Openshift deployment, routing, knative, helm, ...)
