### ISSUE TITLE
Upgrade to Spring Cloud Azure 4.1.0

### ISSUE THREAD

**Issue by yiliuTo** [spring-io/start.spring.io#909]
Hi, we now published `com.azure.spring:spring-cloud-azure-dependencies` of version `4.1.0` to Maven: https://repo1.maven.org/maven2/com/azure/spring/spring-cloud-azure-dependencies/4.1.0/
Please help to upgrade the version of bom to the latest. Thanks!

**Comment by wilkinsona** [comment]
With which versions of Spring Boot is Spring Cloud Azure 4.1.0 compatible?

**Comment by yiliuTo** [comment]
oh forgot to mention that. It's compatible with Spring Boot 2.5.0~2.5.13 and 2.6.0~2.6.7, thanks
