### ISSUE TITLE
Override the version of jOOQ when the user selects Boot 2.7, Java 11+, and H2

### ISSUE THREAD

**Issue by wilkinsona** [spring-io/start.spring.io#925]
See https://github.com/spring-projects/spring-boot/issues/31168 for background. The summary is that the versions of H2 and jOOQ in Spring Boot 2.7 are incompatible due to breaking changes in H2 2.x. Open source versions of jOOQ that are compatible with H2 2.x are available but they require Java 11.

If a user creates a Spring Boot 2.7 project using Java 11+, jOOQ, and H2, we should consider overriding the version of jOOQ that's used. If they select Java 8 and H2, we could also consider disabling jOOQ. Overriding the version may be a little tricky as we'd have to find a way of keeping the version up-to-date.

**Comment by snicoll** [comment]
With Spring Boot 2.7 being in maintenance mode nowadays, I am not convinced this is worth doing this anymore.
