### ISSUE TITLE
Upgrade to Spring Cloud Azure 4.2.0

### ISSUE THREAD

**Issue by chenrujun** [spring-io/start.spring.io#929]
1. Maven: https://repo1.maven.org/maven2/com/azure/spring/spring-cloud-azure-dependencies/4.2.0/
2. Compatible Spring Boot version: https://github.com/Azure/azure-sdk-for-java/blob/spring-cloud-azure_4.2.0/sdk/spring/CHANGELOG.md#420-2022-05-26

**Comment by snicoll** [comment]
Congrats on the release!
