### ISSUE TITLE
Vaadin Gradle Plugin does not use Vaadin version as recommended

### ISSUE THREAD

**Issue by phantasia15** [spring-io/start.spring.io#935]
Currently, when generating with `Vaadin` as dependency, the outdated plugin version `0.14.6.0` is used and it doesn't work properly.

According to [this](https://vaadin.com/docs/latest/flow/guide/start/gradle/#build-file), the plugin version must match with Vaadin version.

Link to the new plugin version: https://plugins.gradle.org/plugin/com.vaadin
```
plugins {
  id "com.vaadin" version "23.0.11"
}
```

**Comment by snicoll** [comment]
Thanks for the report @phantasia15 

cc @mstahv

**Comment by mstahv** [comment]
@ZheSun88 Can you take a look and suggest a change? The Gradle plugin ought to be updated like Maven when the platform version get updated.

**Comment by snicoll** [comment]
@mstahv this was for your information. We'll update the code so that the version is aligned automatically.

**Comment by mstahv** [comment]
👌 Sounds even better!
