### ISSUE TITLE
Broken links in the generated HELP.md for Spring Cloud Function and Azure

### ISSUE THREAD

**Issue by stliu** [spring-io/start.spring.io#942]
How to reproduce

`https://start.spring.io/#!type=maven-project&language=java&platformVersion=2.7.0&packaging=jar&jvmVersion=17&groupId=com.example&artifactId=demo&name=demo&description=Demo%20project%20for%20Spring%20Boot&packageName=com.example.demo&dependencies=cloud-function,azure-support,native`

in the generated HELP.md, contains broken link

> Check the documentation for detailed information on [using the Azure adapter](https://cloud.spring.io/spring-cloud-static/spring-cloud-function/3.2.5/azure.html) and [setting up the maven build, along with a full build setup sample](https://cloud.spring.io/spring-cloud-static/spring-cloud-function/3.2.5/azure.html#_build_file_setup).

**Comment by wilkinsona** [comment]
The correct links appear to be https://docs.spring.io/spring-cloud-function/docs/3.2.5/reference/html/azure.html and https://docs.spring.io/spring-cloud-function/docs/3.2.5/reference/html/azure.html#_build_file_setup
