### ISSUE TITLE
Upgrade to Spring Cloud Azure 4.3.0

### ISSUE THREAD

**Issue by hui1110** [spring-io/start.spring.io#955]
1. Maven: https://repo1.maven.org/maven2/com/azure/spring/spring-cloud-azure-dependencies/4.3.0/

2. Compatible Spring Boot version: https://github.com/Azure/azure-sdk-for-java/blob/spring-cloud-azure_4.3.0/sdk/spring/CHANGELOG.md#430-2022-06-29

**Comment by hui1110** [comment]
Hi @snicoll, can you help take a look?

**Comment by snicoll** [comment]
@hui1110 apologizes for the delay, I was on PTO.
