### ISSUE TITLE
Support generating a Java project that uses Gradle with the Kotlin DSL

### ISSUE THREAD

**Issue by G0ldmember** [spring-io/start.spring.io#956]
Is there a way to create a Java-based Spring-Boot project with gradle using Kotlin DSL? The tool always uses groovy DSL for Java based gradle projects. Only if Kotlin is chosen as language, the DSL is also in Kotlin. Would be great if this was selectable.

**Comment by G0ldmember** [comment]
Thanks @wilkinsona for you honest feedback. It was just a thought to make it more flexible for those wanting to rely on Kotlin DSLs together with gradle. Let's see what the rest of the team thinks about it. Have a nice weekend

**Comment by hanct** [comment]
I second this.

Why not simply add an option to the project type, and rename the existing one , i.e maven, gradle (groovy dsl) and gradle (kotlin dsl)

I personally think the design of spring initializer should be independent from the capability of existing ide to support kotlin dsl. Cos there are developers  like me, who do not leverage on the editing capability of the IDE. I prefer copy and paste from internet's working one, and modify from there..hehe.

**Comment by snicoll** [comment]
I am afraid I don't think that anything has changed. Offering a dedicated option while having an opinion on which DSL to use based on the language makes it really hard to implement consistently. If you select a different DSL then pick a language, we shouldn't override that. Yet, if you don't express any opinion, we'd like the Kotlin DSL to be used by default for Kotlin (and certainly not for Groovy).

**Comment by sdeleuze** [comment]
@jamesward I am glad to hear Gradle, JetBrains and Google want to push for making the Kotlin DSL the default, and I think that could be compatible "at some point* with the alternative @wilkinsona mentioned previously.

> The alternative is to switch the default for everyone so that all Java-based Gradle projects use the Kotlin DSL.

Despite being a huge Kotlin fan, I think we have not yet reached a point where we can change the default. I personally see 3 blockers.

**Kotlin DSL autocomplete is Eclipse and VS code**

You said in the other issue:

> We know the editing experience isn't great right now in Eclipse but that is true for both Groovy build scripts and Kotlin build scripts.

That's true for both Groovy build scripts and Kotlin build scripts, but without code completion Groovy DSL is simpler to write than Kotlin DSL and people are used to Groovy DSL ot the Kotlin one, so I think changing the default to Kotlin DSL without a reasonable auto-complete is not going to fly for the average user, even if you improve the documentation. Is there some plan to contribute `gradle.kts` autocomplete via Kotlin language server for example?

I also think that Gradle, JetBrains and Google should reduce the technical noise and push for an idiomatic way to build Gradle Kotlin builds. IMO https://github.com/gradle/gradle/issues/9268 is IMO a must have before considering a wide switch for everybody.

Last point, maybe not a blocking one, but K2 compiler is very much needed to improve the compilation time to improve the DevXP and we would be interested to know if there is an approximate ETA to make it used with Gradle Kotlin DSL.

**Comment by jamesward** [comment]
Thanks @sdeleuze for the thoughts.  A few responses...

IDE Support: The vast majority of users get a much better experience editing KTS and from what I've seen even those not using IntelliJ get a somewhat better experience.  In this context we are primarily referring to start.spring.io users who likely aren't experienced Gradle build engineers (Groovy or Kotlin).  Both Groovy & Kotlin are likely foreign to most of these users but the error messages are much better with Kotlin and are eager (i.e. Groovy errors are often not uncovered until the task with the error is run).  I'll ask about Gradle's plan for improving KTS in Eclipse & VS Code but given the direction of going KTS as the default, there will likely be more improvements in KTS tooling than for Groovy.

KTS Syntax: There will be improvements to the KTS syntax, including the `=` assignment operator for `Property<T>` to keep the syntax more declarative looking.  For me those improvements are not a blocker as most of the users we are targeting get a much better experience by default with KTS and that experience will continue to improve over time.

Compile Times: K2 likely won't have a big impact on the start.spring.io DX (compile times).  But there are other compile improvements that will.  Some of those are still being worked out.  A nice thing with KTS is that the compile output can be cached, even remotely cached for multiple users to take advantage of.  So while a KTS cold start is a bit slower than with the interpreted Groovy, the warm start is often faster.

Overall, I get your concerns and I want the KTS experience to be so great that this is an obvious choice.  For the vast majority of users I think we are already there and we do have some places where improvements will continue to make KTS better.  The more we can shift to KTS by default the sooner those improvements will be fully realized.

As an aside, we are working on a KTS style guide where hopefully Gradle, JetBrains, Google, Spring, etc can agree on a more consistent KTS style.  It'd be great to have someone from Spring on the team that puts that together.  Let me know who'd be a good person for me to include in that.

**Comment by yalishevant** [comment]
>  Is there some plan to contribute *.gradle.kts autocomplete to Eclipse and VS Code via Kotlin language server for example?

In VSCode it now works. There are quite well Extension and LSP impl. for Kotlin. Also, *.gradle.kts are supported in Java LS.

**Comment by sdeleuze** [comment]
@yalishevant Nice, I will test that, thanks for sharing. Do you know if there is any plans to do the same on Kotlin side?

@jamesward Thanks for your feedback. Do you know if an official communication from Gradle like "Gradle Kotlin DSL is now the default/recommended variant" is expected at some point? Does that mean Gradle will switch their documentation to use the Kotlin DSL by default?

> For me those improvements are not a blocker as most of the users we are targeting get a much better experience by default with KTS

I think I disagree on that one. The "= assignment operator for Property<T>" may sounds like a detail, but in practice there is no predicable way to set a property with Gradle Kotlin DSL, forcing some plugins but not others to provide some handwritten workaround, which means no consistency and no predictable idiomatic behavior across the ecosystem on one of the most basic thing a build DSL should allow. Fixing this will make Kotlin DSL much more loved by developers IMO.

**Comment by yalishevant** [comment]
> is there any plans to do the same on Eclipse side?
Eclipse plugins is now supported mostly by community contributors. Kotlin team only maintain the infrastructure, processes contributions and update the plugin. So, Kotlin team has no such plans but that may come from contributors with no guaranty.

**Comment by wilkinsona** [comment]
Unfortunately, I think that makes switching to the Kotlin DSL without a way to switch back a non-starter. Looking at Gradle projects generated from an IDE using start.spring.io in the last 90 days, Eclipse was used roughly 33% of the time. In my opinion, this means that the editing experience of build.gradle.kts files in Eclipse needs to improve significantly before we could consider such a change.

If we want to make a change here, I think our best option would be to somehow offer the Kotlin DSL as a choice but continue defaulting to the Groovy DSL. I think that could be possible if we revisit [this reasoning](https://github.com/spring-io/start.spring.io/issues/956#issuecomment-1181728585).

> we'd like the Kotlin DSL to be used by default for Kotlin

Up until recently, this wasn't much of a default. You had to select `Gradle` as the build system before Groovy vs Kotlin DSL became an issue. If we'd had `Gradle – Groovy DSL` and `Gradle – Kotlin DSL` options, a Kotlin and Gradle user would still have had a single click to get what they wanted.

Now that we've switched to Gradle by default, a Kotlin user doesn't have to select anything to get a Gradle build that uses the Kotlin DSL. I'm sure this is a convenience that they enjoy, but it comes at the cost of not being able to offer the Kotlin DSL for Java (or Groovy) projects. I think that cost's rather high. I've just checked the stats and in the last year only 15% of Gradle projects were Kotlin projects.

> If you select a different DSL then pick a language, we shouldn't override that. Yet, if you don't express any opinion, we'd like the Kotlin DSL to be used by default for Kotlin (and certainly not for Groovy).

I think we could address this by keeping it simple (and requiring an extra click from Kotlin users). We'd split the existing `Gradle` option into two: `Gradle – Groovy DSL` and `Gradle – Kotlin DSL`. It would default to `Gradle – Groovy DSL` and this wouldn't change irrespective of the language that you pick. If someone clicks `Kotli`n they'd probably also have to click `Gradle – Kotlin DSL` but that's no worse than before when `Maven` was the default and they had to click `Gradle`.

Requiring a maximum of 15% of users generating Gradle projects to make an extra click opens up the possibility of the other 85% being able to use the Kotlin DSL if they wish. That feels like a good trade off to me.

**Comment by sdeleuze** [comment]
Decoupling language from Gradle DSL and allowing Java developers to use Gradle Kotlin DSL sounds like a step into the right direction, even if I am a bit sad that we will force Kotlin developers to select the Kotlin DSL every time (almost nobody uses Groovy DSL there).

I guess we can see it as a necessary pain before a potential later switch to Kotlin DSL by default when the conditions will be ok.

**Comment by jamesward** [comment]
Selectable Gradle DSL does add some decision overhead but does probably help put us on the path to KTS by default.  It seems that with this option in place having Groovy build scripts be the default for Java & Groovy, and Kotlin build scripts be the default for Kotlin, makes sense for now.

Question on the cited stats... 33% Eclipse seems higher than I'd expect. Can you provide more details on how that stat was derived?  If a user creates a project from start.spring.io how do you know which IDE they then open the project in?

**Comment by wilkinsona** [comment]
> It seems that with this option in place having Groovy build scripts be the default for Java & Groovy, and Kotlin build scripts be the default for Kotlin, makes sense for now

That is not what is being proposed as it adds too much complexity:

- What should happen if the user selects and build system and then selected a language?
- What should happen if the user selects a language and then selects a build system?
- How should this work across the web UI, Eclipse, IntelliJ, and NetBeans?

Anything that requires one setting to somehow change in response to another setting is a non-starter. It's too difficult to implement consistently across clients and even if it could be implemented consistently, I don't think it's possible for us to infer the user's intent. This is the problem that Stephane [already described above](https://github.com/spring-io/start.spring.io/issues/956#issuecomment-1181728585).

My proposal is that we avoid this problem by simplify thing things: the default for all projects, irrespective of language, would be `Gradle – Groovy DSL`. `Gradle – Kotlin DSL` and `Maven` would be available as options. This does have a cost as I've described above but I think the benefits outweigh that cost quite significantly.

> 33% Eclipse seems higher than I'd expect. Can you provide more details on how that stat was derived? If a user creates a project from start.spring.io how do you know which IDE they then open the project in?

As I said [above](https://github.com/spring-io/start.spring.io/issues/956#issuecomment-1320176599), this is for Gradle projects generated from an IDE. We don't have IDE numbers for project generated in a browser. That said, it's pretty well-aligned with other numbers we see for IDE usage in the Spring community.

**Comment by jamesward** [comment]
Thanks for the details. That all makes sense now. I think that it is a reasonable tradeoff and does still set us up to switch the default to `Gradle – Kotlin DSL` once:
- The Eclipse kts editing is better
- The KTS `=` property assignment is available

Is that an accurate summary?

**Comment by wilkinsona** [comment]
Yes, that's accurate.

**Comment by eskatos** [comment]
About the assignment of `Property<T>` in the Gradle Kotlin DSL. A Kotlin compiler plugin shipped in the Kotlin distribution will enable direct assignment `=`. We (Gradle) will ship with it behind a feature flag at first and eventually make it the default. This will happen early 2023.
