### ISSUE TITLE
spring-boot-2.7.1.jar; zip file is empty

### ISSUE THREAD

**Issue by SaramZafar** [spring-io/start.spring.io#959]
When a new spring-boot project is downloaded, I am not being able to run it. I didn't faced such issue while having spring boot version 2.7.0. Since 2.7.1 I am facing the issue of : Users/user .m2/repository/org/springframework/boot/spring-boot/2.7.1/.

In order to run it, I have to manually change the version to 2.7.0 and then add 

```
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-bootstrap</artifactId>
</dependency>
```

to pom.xml in order to run the project successfully. 

Apologies I am new to spring boot.

**Comment by wilkinsona** [comment]
Thanks for the report. Unfortunately, I don't think we can do anything about this here. The `spring-boot-2.7.1.jar` file is not empty [on Maven Central](https://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot/2.7.1/) where it has a size of 1443055. Please check your local network and proxy configuration. You may also want to delete Maven's local cache to force Maven to download the jar again.

**Comment by SaramZafar** [comment]
> Thanks for the report. Unfortunately, I don't think we can do anything about this here. The `spring-boot-2.7.1.jar` file is not empty [on Maven Central](https://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot/2.7.1/) where it has a size of 1443055. Please check your local network and proxy configuration. You may also want to delete Maven's local cache to force Maven to download the jar again.

Thank you
