### ISSUE TITLE
Add Apache Ignite

### ISSUE THREAD

**Issue by sdarlington** [spring-io/start.spring.io#960]
# Requirements

## Code of Conduct

As an ASF project, we follow their standard [CoC](https://www.apache.org/foundation/policies/conduct.html).

## Well-established project with a vibrant community

[Apache Ignite](https://ignite.apache.org/) is a distributed, in-memory database. It's a [Top 5 ASF project](https://blogs.apache.org/ignite/entry/apache-ignite-momentum-highlights-from), has over [4k stars on GitHub](https://github.com/apache/ignite) and has been an active and growing project since it joined the ASF in 2014.

## Ongoing maintenance

Spring Boot Starter has been [maintained for two years already](https://issues.apache.org/jira/browse/IGNITE-12525) (and Spring Boot support for much longer than that!). There are no plans to discontinue this!

## Licence

As part of the ASF, it uses the [Apache 2.0 licence](https://github.com/apache/ignite-extensions/blob/master/LICENSE).

## Issue Tracker URL

The bug tracker can be found [here](https://issues.apache.org/jira/projects/IGNITE). More details on how people can get help and contribute can be found on the [community page of the website](https://ignite.apache.org/our-community.html).

## Continuous integration

https://ci.ignite.apache.org/buildConfiguration/IgniteExtensions_Tests_SpringBootThinClientAutoconfigure?mode=branches#all-projects

## Maven Central

Artifacts: https://search.maven.org/artifact/org.apache.ignite/ignite-spring-boot-thin-client-autoconfigure-ext

[X] Starter and all of its dependencies are available on Maven Central.

## Configuration metadata

Configured as [per the documentation](https://ignite.apache.org/docs/latest/extensions-and-integrations/spring/spring-boot).

If you starter provides `@ConfigurationProperties` it should provide metadata for those
properties to enable auto-completion in the IDE. Metadata can be provided by adding
field level documentation on each of the properties and adding the
`spring-boot-configuration-processor` to your build.

[ ] Starter provides metadata, including documentation, for all its configuration
properties.

## Version mappings
Spring Initializr allows different versions of a starter to be used with different
versions of Spring Boot. For example, if a project is being generated with Spring
Boot version W you may want to use Starter version X and if a project is being
generated with Spring Boot version Y you may want to use Starter version Z.

Please provide the details of any mappings between particular version of Spring
Boot and particular versions of your starter.

## Links to additional resources
Each entry can be associated with one or several links. Please provide at least a link to
a sample and the reference documentation:

* Reference documentation:
* Ignite docs: https://ignite.apache.org/docs/latest/
* Spring Starter docs: https://ignite.apache.org/docs/latest/extensions-and-integrations/spring/spring-boot

* Sample:
* Example: https://github.com/apache/ignite-extensions/tree/master/modules/spring-boot-thin-client-autoconfigure-ext/examples

**Comment by snicoll** [comment]
@sdarlington thanks for the suggestion. I had a look to the documentation and I couldn't really find if there is a starter that brings Spring Data support. Is there auto-configuration for Spring Data? This isn't blocking this request but since the support exists, it would be nice to showcase that.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by sdarlington** [comment]
The current version of the starter (1.0.0) does not auto-configure Spring Data, however, that code _is_ in the master branch and we're looking to see if we could release 1.1.0 relatively soon.

**Comment by snicoll** [comment]
@sdarlington the request is missing the following

> Please provide the details of any mappings between particular version of Spring
Boot and particular versions of your starter.

The reason I pick this bit in particular is that it seems that the starter is built against Spring Boot `2.2.x` that is End Of Life for over a year now. We need to make sure that new versions are picked up switfly to consider adding an entry here.
