### ISSUE TITLE
Valid project state cannot be related using shared URL

### ISSUE THREAD

**Issue by dbses** [spring-io/start.spring.io#984]
When open shared url of https://start.spring.io/#!type=maven-project&language=java&platformVersion=2.6.11&packaging=jar&jvmVersion=17&groupId=com.example&artifactId=demo&name=demo&description=Demo%20project%20for%20Spring%20Boot&packageName=com.example.demo&dependencies=solace, the dependency is invalid.

However, when I click on the spring boot version of 2.6.11, the dependency becomes valid.

I think it's a bug

**Comment by snicoll** [comment]
Fixed by https://github.com/spring-io/start.spring.io/commit/ed791a3b989fd89bb9ab5e37f518a9a532c235f9
