### ISSUE TITLE
Error message "could not connect to server" is misleading in case of server error

### ISSUE THREAD

**Issue by Cat-Lord** [spring-io/start.spring.io#990]
When configuring a project I encountered a weird error. I don't know the suggested way of naming project but since it isn't the artifact name I though of naming it more 'commercially' using proper diacritics of my language. Pressing 'Generate' resulted in an 'Could not connect to server. Please check your network.' error.

Edit: Tested with Firefox and Chrome.

**Expected result:** Correct project generation or an "Invalid name " error within the form.

**Actual result:** "Could not connect to server. Please check your network." popup error (see screenshot)

Sample input:
![image](https://user-images.githubusercontent.com/32105793/188468462-23c1abe7-2725-4d03-8867-6cd4ce373bec.png)

Error preview:
![image](https://user-images.githubusercontent.com/32105793/188468710-37acb2cf-c67f-4952-b925-b73ba5b0225c.png)

**Comment by wilkinsona** [comment]
The error message is rather misleading as it isn't a connection failure but a server side error. Generating the project results in a 500 response from the server:

```
{
    "timestamp": "2022-09-05T14:39:37.471+00:00",
    "status": 500,
    "error": "Internal Server Error",
    "message": "Malformed input or input contains unmappable characters: MixérApplication.java",
    "path": "/starter.zip"
}
```

**Comment by snicoll** [comment]
Perhaps we could split this in two, keeping this issue for improving the error message?

**Comment by wilkinsona** [comment]
Yeah, I think that sounds good. It really is two separate problems.

**Comment by ZenaAssamman** [comment]
I solved the problem with "could not connect to server " by changing the name of the artifact, previously the name had an umlaut

**Comment by vinayak-gaikwad** [comment]
@snicoll, I would like to work on this, could you assigned me this?

**Comment by mhalbritter** [comment]
Hey @vnayakg, i've assigned it to you. Have fun!

**Comment by mhalbritter** [comment]
Hey @vnayakg, how's it going? Are you still working on it?

**Comment by vnayakg** [comment]
Hey @mhalbritter, @oodamien had already raised pr for this, unassigned myself

**Comment by mhalbritter** [comment]
Superseded by https://github.com/spring-io/start.spring.io/pull/1624.
